### ISSUE TITLE
Form::submit should create a button element

### ISSUE THREAD

**Issue by JosephSilber** [LaravelCollective/html#101]
I think it would make more sense for `Form::submit('Save')` to create this:

```html
<button type="submit">Save</button>
```

instead of this:

```html
<input type="submit" value="Save">
```

`input` elements are harder to style (iOS Safari always causing problems).

**Comment by xitude** [comment]
+1

**Comment by adamgoose** [comment]
You can simply use `Form::button($value, array $options = ['type' => 'submit']);`
