### ISSUE TITLE
Form::model around @yield doesn't persist the model

### ISSUE THREAD

**Issue by elliotlings** [LaravelCollective/html#106]
I'm not sure if this is fixable, but if you do the following:

```php
{!! Form::model($model, ...) !!}
    @yield('content')
{!! Form::close() !!}
```

Any fields inside the yield will see the model as equal to null.

I think what we are doing is a rare edge case and can probably get around it using an `@include` inside.

Just wondered if you know what maybe causing this, are `@yield`s compiled before the view it extends?

**Comment by RobinMalfait** [comment]
Why would you want to do that?

You can do something like this

```php
{!! Form::model($model, ...) !!}
    @include('some.blade.file')
{!! Form::close() !!}
```

**Comment by adamgoose** [comment]
I agree with Robin. This is due to the way that the blade compiler works, and the form builder won't be able to get around it. Try using a partial.
