### ISSUE TITLE
Suggestion Form::multicheckbox

### ISSUE THREAD

**Issue by eullercristian** [LaravelCollective/html#113]
Dears, i have a sugestion for yours. Laravel could have a element form multicheckbox/radio. See a example of implementation of Zend Framework: http://migre.me/s5V0J What do you think about that?

The element could be Form::multicheckbox('name', array('L' => 'Large', 'S' => 'Small'));

**Comment by canerdogan** [comment]
+1

**Comment by adamgoose** [comment]
If I'm understanding you correctly, you're asking for the ability to call a simple method, which will return several checkboxes. However, this is impractical, as most websites require additional DOM & CSS around the checkbox elements.

We'll be releasing a new feature with 5.2 that will make it easier for you to create templates for things such as this.

**Comment by eullercristian** [comment]
Excelent @adamgoose  , i will wait for new feature 5.2 thanks!

**Comment by eullercristian** [comment]
@adamgoose  When the version 5.2 will ready?

**Comment by adamgoose** [comment]
Not until Laravel 5.2 is released.
