### ISSUE TITLE
Component should be more extendable

### ISSUE THREAD

**Issue by spiritix** [LaravelCollective/html#114]
It is pretty hard to add custom element types or even modify the behavior of existing elements. It would be great if we could make this component more extendable in an object oriented way, writing macros it not really nice.

**Comment by tshafer** [comment]
Why not just use straight html?

**Comment by spiritix** [comment]
Then why create such a library if you suggest people to use plain HTML as soon as it doesn't fit the requirements anymore? Extensibility should be a fundamental of every piece of software...

**Comment by arcanedev-maroc** [comment]
@spiritix You can extend the library by using the laravel service container.

Check the docs : http://laravel.com/docs/5.1/container.

**Comment by judgej** [comment]
@arcanedev-maroc so is the idea to extend the service classes here, then tell laravel to use your class in place of the default class in this package?

**Comment by arcanedev-maroc** [comment]
@judgej, Laravel offers the ability to extend each dependencies/components via the service container.

**You want to know how ?**

First, you start by editing the `app.php` config file:

```php
<?php
// config/app.php

return [
    // ...

    /* ------------------------------------------------------------------------------------------------
     |  Autoloaded Service Providers
     | ------------------------------------------------------------------------------------------------
     */
    'providers' => [
        // Laravel Framework Service Providers...
        // ...


        // Other Service Providers...
        Collective\Html\HtmlServiceProvider::class,
        // ...

        // Application Service Providers...
        App\Providers\AppServiceProvider::class,
        // ...
    ],

    // ...
];
```

Then you create you custom class (eg: `HtmlCustomBuilder`):

```php
<?php namespace App;

use Collective\Html\HtmlBuilder;

class HtmlCustomBuilder extends HtmlBuilder
{
    public function bsAlert($title, $message, $type = 'success', $closeButton = false)
    {
        $button = '';

        if ($closeButton) {
            $button = implode(PHP_EOL, [
                '<button type="button" class="close" data-dismiss="alert" aria-label="Close">',
                    '<span aria-hidden="true">&times;</span>',
                '</button>',
            ]);
        }

        return implode(PHP_EOL, [
            '<div class="alert alert-' . $type . ' alert-dismissible" role="alert">',
                $button,
                '<strong>' . $title . '</strong> ' . $message,
            '</div>',
        ]);
    }
}
```

Now you need to override the `html` builder with the custom one inside a Service Provider (eg: `AppServiceProvider`):

```php
    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton('html', function ($app) {
            return new \App\HtmlCustomBuilder($app['url'], $app['view']);
        });

        $this->app->alias('html', \App\HtmlCustomBuilder::class);
    }
```

Done !!

**Comment by judgej** [comment]
Presumably you could also create a custom service provider and point to that from the providers array in the `app.php` config? That way you don't effectively create the base service provider then override it. That's how I have extended providers such as `Mail` in the past, but it does feel kind of clumsy.

However, I believe there is clever stuff in Laravel core that can switch service providers automatically based on certain contexts, so maybe this way is more flexible. Not yet got my head around that though.

The other way of extending is to use the macro extension. I've just done that to create a `money` field type that will accept a `Money\Money` object as its value from model and will know how to convert it to the correct format for editing. This does not involve any "form accessors" in the model, so saves a lot of code to maintain when dealing with models that have lots of money amount fields. The form accessors in the model are great for one-off special fields, but you don't want to have to keep creating them for multiple fields of the same type over and over in a project.

The documentation in this package does not even touch on the possibilities with macros - I can extend that with a PR example that extends the `number` field type, if that is going to be useful to others?

**Comment by judgej** [comment]
Okay, I'll just paste some code here for others. This macro is set up in AppServiceprovider::boot(). There may be better/other places to put it.

~~~php
        /**
         * Extend the form builder.
         * Support a monetary amount field, with a Money\Money getter on the bound model.
         */
        Form::macro('amount', function($name, $value = null, $options = []) {
            // $this is the FormBuilder instance.
            $value = $this->getValueAttribute($name, $value);

            // Make sure the value is a Money instance.
            $value = AppHelper::parseMoney($value);

            // We are converting the value into a float here before formatting it.
            // There must be a better way?
            $formatted_value = AppHelper::formatMoneyValue($value);

            // We need to know the decimal places to set the steps (for HTML5 validation).
            $decimals = AppHelper::moneyDecimals($value);

            // Set the step, if not already set.
            if (! array_key_exists('step', $options)) {
                $options['step'] = 1 / pow(10, $decimals);
            }

            // Set the placeholder to a formatted "0" amount, if not already set.
            if (! array_key_exists('placeholder', $options)) {
                $options['placeholder'] = AppHelper::formatMoneyValue(AppHelper::parseMoney(0));
            }

            return $this->number($name, $formatted_value, $options);
        });
~~~

My helper class does this:

* `AppHelper::parseMoney()` takes an amount (number or string) and parses it into a `Money` object. If it already is a `Money` object - which it normally is in this case as my model has an accessor method to always return a `Money` class for the money value attributes.
* `AppHelper::moneyDecimals()` tells me how many decimal places the `Money` value uses.
* `AppHelper::formatMoneyValue()` will take a `Money` object and format its *value* to a string, with any necessary leading or trailing zeros and a decimal point.

I use this in a form like any other form item:

    {!! Form::amount('my_acount_field', null, ['class' => 'form-control']) !!}

If the bound model returns a `Money` object for its `my_acount_field` attribute, then it all gets formatted nicely. I use this to extend the `number` form field, but I could do more to extend it by including the currency symbol in the ford field as a bootstrap icon.

The mutator for the model, used when submitting and saving the form, will take either a `Money` object (in minor units) or a string (which it assumes are major units, which are then parsed to minor units). That closes up the loop.

**Comment by judgej** [comment]
So my conclusion: this package is pretty extendable already, but the documentation needs more examples, even if it does stray into stuff that is more core to laravel. Like most laravel documentation, if you already know it, it is great, but learning from it can be quite an uphill struggle.
