### ISSUE TITLE
Problem with Vue.js

### ISSUE THREAD

**Issue by eullercristian** [LaravelCollective/html#116]
Dears in vue.js i need to pass the parameter v-el:element but in  the form collective i cant pass this directive. 

I tried "v-el:element" but the form returns v-el:element="v-el:element" and i need only the directive v-el:element em my input text. 

How i can solve this question? 

I guess that you could change that, when i pass a value in the form collective that not have a key, collective return only the parameter, example: 

Form::text('name', null,  ['v-el:name']) 
return input type="text" name="name" v-el:name

**Comment by adamgoose** [comment]
We still have plans for this particular issue, however we now have a new feature called [Components](https://laravelcollective.com/docs/5.2/html#custom-components). This might help!

**Comment by mlantz** [comment]
Is this resolved?
