### ISSUE TITLE
Issue with populating select from Model in Laravel 5.1

### ISSUE THREAD

**Issue by canerdogan** [LaravelCollective/html#117]
At this line
https://github.com/LaravelCollective/html/blob/master/src/FormBuilder.php#L1035

In Laravel 5.1 data_get returns Collection instead of Array. So [getValueAttribute](https://github.com/LaravelCollective/html/blob/master/src/FormBuilder.php#L1009) returns Collection instead of Array. But in [getSelectedValue](https://github.com/LaravelCollective/html/blob/master/src/FormBuilder.php#L657-L665) it should be an array!

I think best solution is added Collection control to change getSelectedValue to:

```
protected function getSelectedValue($value, $selected)
  {
      if (is_array($selected)) {
          return in_array($value, $selected) ? 'selected' : null;

      // If selected value getting from Model we should get value from Collection with all() method to array.
      } elseif ($selected instanceof Collection) {
          return in_array($value, $selected->all()) ? 'selected' : null;
      }

      return ((string) $value == (string) $selected) ? 'selected' : null;
  }
```

**Comment by tshafer** [comment]
Can you please submit a P.R. with tests?
