### ISSUE TITLE
FormBuilder value as array issue

### ISSUE THREAD

**Issue by andkom** [LaravelCollective/html#122]
When I submit the following form:

```
<form>
...
        {!! Form::text('test[]') !!}
...
</form>
```

I get the following error:

```
ErrorException in helpers.php line 469: htmlentities() expects parameter 1 to be string, array given 
```

Stacktrace:

```
1. in helpers.php line 469
2. at HandleExceptions->handleError('2', 'htmlentities() expects parameter 1 to be string, array given', '/xxx/vendor/laravel/framework/src/Illuminate/Support/helpers.php', '469', array('value' => array('asdf')))
3. at htmlentities(array('asdf'), '3', 'UTF-8', false) in helpers.php line 469
4. at e(array('asdf')) in HtmlBuilder.php line 410
5. at HtmlBuilder->attributeElement('value', array('asdf')) in HtmlBuilder.php line 382
6. at HtmlBuilder->attributes(array('name' => 'test[]', 'type' => 'text', 'value' => array('asdf'), 'id' => null)) in FormBuilder.php line 258
7. at FormBuilder->input('text', 'test[]', null, array()) in FormBuilder.php line 272
8. at FormBuilder->text('test[]') in Facade.php line 216
9. at Facade::__callStatic('text', array('test[]')) in 3da9884bcf07895aaafc9a097bb0ec7d line 23
10. at FormFacade::text('test[]') in 3da9884bcf07895aaafc9a097bb0ec7d line 23
```

Solution:

function getValueAttribute() in FormBuilder.php:248 should return string

**Comment by Decadence** [comment]
The same for me. I was looking for support of array notation in this module and found this issue.
Can you fix it to support names with [] brackets? Don't forget about implicit incrementing indexes in case of empty brackets.

So:
input name="test[]"
input name="test[]"

will be test[0], test[1] on server.

**Comment by andreasba** [comment]
Same for me. I had to use hardcoded HTML because I spent hours trying to figure this out without avail!

**Comment by michaeljcoyne** [comment]
I am not sure why this issue is closed. I have the same issue. You would think it was a basic requirement for a form builder to deal with arrays.  I am not happy using indexes if it can be helped so may have to revert back to plain old html.

**Comment by tshafer** [comment]
What exactly is the issue. Code samples please.


— 
Tom Shafer

**Comment by michaeljcoyne** [comment]
Instead of having to use indices as follows:

<div class="form-group 
{{ $errors->has('minAnswersReq.0') ? ' has-error' : '' }} ">
{!! Form::label('minAnswersReq', 'Minimum amount of answers required') !!}
{!! Form::text('minAnswersReq[0]', Input::old('minAnswersReq[0]'), array('class' => ' form-control ', 'placeholder' => 'Minimum amount of answers required') ) !!}
 <p class="help-block">{{ $errors->first('minAnswersReq.0') }}</p>
</div> 

- I would like to use  minAnswersReq[]  

However looking into it a bit further and how the validation is handled in Laravel - this may be the only way to do it anyway.

**Comment by socieboy** [comment]
Have the same issue! it should be supported work with arrays

**Comment by Yahav** [comment]
Anything on this issue yet?

**Comment by chaiwei** [comment]
Code Sample, tested with laravel/framework v5.2.45, laravelcollective/html v5.2.4

```
{!! Form::open(array('method' => 'post')) !!}
  {{ Form::text('test[]','' , array('class' => 'form-control')) }}
  {{ Form::text('test[]','' , array('class' => 'form-control')) }}
  {{ Form::text('test[]','' , array('class' => 'form-control')) }}
  {{ Form::submit('save')  }}
{!! Form::close() !!}
```

Controller

```
public function store(Request $request){
    $rules = array(
        'test.0' => 'required',
    );
     
    $validator = Validator::make($request->all(), $rules);
    if ($validator->fails()){
		return redirect()->back()->withInput()->withErrors($validator);
    }else{
        //INSERT INTO DATABASE 
        $request->session()->flash('status', 'Data has been added.');
        return redirect()->back();
    }
}
```
After form submit, the form trying to retrieve the old input value, 
$value = $this->getValueAttribute($name, $value); 


in vendor/laravelcollective/html/src/FormBuilder.php
```
public function getValueAttribute($name, $value = null)
{     ...
        if (! is_null($this->old($name))) {
            return $this->old($name);
        }
}
public function old($name)
{
        if (isset($this->session)) {
            return $this->session->getOldInput($this->transformKey($name));
        }
}
protected function transformKey($key)
{
        return str_replace(['.', '[]', '[', ']'], ['_', '', '.', ''], $key);
}
```
The transformKey function remove the [], so the value return is array() instead of the specify array value..

Below is the stacktrace log.
```
htmlentities() expects parameter 1 to be string, array given in helpers.php line 531
at HandleExceptions->handleError('2', 'htmlentities() expects parameter 1 to be string, array given', '/var/www/clients/client1/web1/web/_subdomain/cwcac/vendor/laravel/framework/src/Illuminate/Support/helpers.php', '531', array('value' => array('', '', '')))
at htmlentities(array('', '', ''), '3', 'UTF-8', false) in helpers.php line 531
at e(array('', '', '')) in HtmlBuilder.php line 434
at HtmlBuilder->attributeElement('value', array('', '', '')) in HtmlBuilder.php line 403
at HtmlBuilder->attributes(array('class' => 'form-control', 'name' => 'test[]', 'type' => 'text', 'value' => array('', '', ''), 'id' => null)) in FormBuilder.php line 272
at FormBuilder->input('text', 'test[]', '', array('class' => 'form-control')) in FormBuilder.php line 286
at FormBuilder->text('test[]', '', array('class' => 'form-control')) in Facade.php line 221
```

**Comment by basherr** [comment]
why isn't this being solved?

**Comment by Decadence** [comment]
@basherr Maintainers don't have time to even consider PRs.

**Comment by bskscmn** [comment]
I already saw some other issues about this subject since 2014. If there wont be any solution about this problem at least I would like to know the reason.

**Comment by Decadence** [comment]
@bskscmn Maintainers don't want to solve this issue by themselves and suggest to make PR. But PRs they don't consider too. So there is vicious circle.

**Comment by PH-F** [comment]
Weirdly this can be solved by adding an indexnr to the array of the form elements

  {{ Form::text('test[0]','' , array('class' => 'form-control')) }}
  {{ Form::text('test[1]','' , array('class' => 'form-control')) }}
  {{ Form::text('test[2]','' , array('class' => 'form-control')) }}

good luck.

**Comment by chaiwei** [comment]
Yeah, the reason we need to use test[] (without index) is easier for javascript manipulation, example add a new textbox using jquery, without having to worry about the number of index to use. 

Example if we have form element 
```
<input name="test[]" value="1" />
<input name="test[]" value="2" />
<input name="test[]" value="3" />
<input name="test[]" value="4" />
```

After form submit to PHP, we can retrieve with below array

```
echo $_POST['test'][0]; // 1
echo $_POST['test'][1]; // 2
echo $_POST['test'][2]; // 3
echo $_POST['test'][3]; // 4
```

When laravel form builder try to retrieve the old value for Form::text, example 

```
Form::text('test[0]') it will look for $_POST['test][0] = int 1
Form::text('test[]') it will look for $_POST['test] = array(0=>1, 1=>2, 2=>3, 3=>4), due to [] was removed in formBuilder->transformKey() function.
```
So that's why the Error: htmlentities() expects parameter 1 to be string, array given in helpers.php line 531 is happen.. 

I am thinking if we use `static` variable to store the element name will help to identify the issue..

**Comment by mlantz** [comment]
Is this still an issue or is this an edge case?

**Comment by andkom** [comment]
Yes, the issue is not fixed:

```
ErrorException in HtmlBuilder.php line 65

htmlentities() expects parameter 1 to be string, array given (View: xxxx.blade.php)
```

**Comment by tarreislam** [comment]
This macro allow you to do this, but it wont work when using `Form::Model`

```
        Form::macro('_input', function ($type, $name, $value = null, $options = array()) {
            $opt = "";
            foreach ($options as $k => $v) {
                $opt .= sprintf('%s="%s"', $k, $v ? $v : $k);
            }
            $value = $value ? $value : old($name);
            return sprintf('<input type="%s" name="%s" value="%s" %s>', $this, $name, $value, $opt);
        });
```
place it inside your `boot()` method @ `AppServiceprovider` (Or any other registered provider)


### Example
```
{{ Form::_input('text', 'test[]', 1) }}
{{ Form::_input('text', 'test[]', 2) }}
{{ Form::_input('text', 'test[]', 3) }}
{{ Form::_input('text', 'test[]', 4) }}
{{ Form::_input('text', 'test[]', 8) }}

// will yield

['test'] => [0, 1, 2, 3, 4, 8]
```

**Comment by marwan2** [comment]
Any new news about fixing this issue !!!!
It still has the same bug

**Comment by mlantz** [comment]
I'll try and sort this out in the next day or so and get another release out

**Comment by andkom** [comment]
seems that original issue is fixed now

**Comment by mlantz** [comment]
:)

**Comment by jaminscript** [comment]
I'm happy to see this has been fixed, but this doesn't work for situations like this: `users[][name]`
