### ISSUE TITLE
Passing class value overrides the Model value Laravel 5.1

### ISSUE THREAD

**Issue by iamgaurav** [LaravelCollective/html#123]
I'm using the following code 

                {!! Form::model($property, array('route' => array('agent.properties.update', $property->id)) ) !!}

                <div class="form-group">
                {!! Form::label('name', 'Name') !!}
                {!! Form::text('name','',['class' => 'form-control']) !!}
                </div>

                <div class="form-group">
                    {!! Form::label('location', 'Location') !!}
                    {!! Form::text('location','',['class' => 'form-control']) !!}
                </div>

                <div class="form-group">
                {!! Form::label('description', 'Description') !!}
                {!! Form::textarea('description','',['class' => 'form-control']) !!}
                </div>

                {!! Form::submit('Update Property!') !!}

                {!! Form::close() !!}

If i remove the class array and the second parameter the model binding starts working fine.

**Comment by tshafer** [comment]
Not sure what you mean here.

**Comment by iamgaurav** [comment]
Well when I try adding a class value to the form field it no longer shows
the default value from the database

**Comment by iWader** [comment]
You should pass `null` as the value parameter if you want to add a class to the input. If you pass an empty string, then that will be used as the value, as it specifically looks for null using `is_null()`. https://github.com/LaravelCollective/html/blob/5.1/src/FormBuilder.php#L1073-L1075

```
{!! Form::text('acme', null, ['class' => 'form-control']) !!}
```

**Comment by adamgoose** [comment]
@iWader is correct. Instead of passing `null`, you've passed an empty string, which will take precidence over the model value.
