### ISSUE TITLE
Method number does not exist

### ISSUE THREAD

**Issue by graphicgeek** [LaravelCollective/html#125]
The docs list a method for number inputs:

https://laravelcollective.com/docs/5.1/html#number

But when I use this I get a Method number does not exist error

**Comment by tshafer** [comment]
Code example please.

**Comment by graphicgeek** [comment]
@tshafer I used it in a blade template, exactly as the Docs show:

{!! Form::number('name', 'value') !!}

**Comment by tshafer** [comment]
please paste your requirement for this package from composer

**Comment by adamgoose** [comment]
The `number()` method does exist. You might be calling an old version of the package. https://github.com/LaravelCollective/html/blob/5.1/src/FormBuilder.php#L330-L342
