### ISSUE TITLE
Please add support for 5.2

### ISSUE THREAD

**Issue by goyote** [LaravelCollective/html#133]

**Comment by arthurkirkosa** [comment]
There is in master

**Comment by freekmurze** [comment]
Now that Laravel 5.2 is available could you please tag the current master branch?

**Comment by netopvh** [comment]
It is available for Laravel 5.2 ?

**Comment by yajra** [comment]
+1

**Comment by agentphoenix** [comment]
:+1:

**Comment by rappasoft** [comment]
+1

**Comment by adamgoose** [comment]
Will be working on this tonight! Sorry, have been traveling today otherwise I would have had it done sooner.

**Comment by jedkirby** [comment]
+1

**Comment by garlian** [comment]
+1

**Comment by yasinkocak** [comment]
+1

**Comment by arcanedev-maroc** [comment]
Hi everyone,

You can use the [arcanedev/laravel-html](https://github.com/ARCANEDEV/LaravelHtml) package if you want. It has the same functionalities as the `laravelcollective/html`.

**Comment by yasinkocak** [comment]
Thanks!

**Comment by mreschke** [comment]
You need to make your master a stable 5.2 tag for proper composer usage without minimum-stability:dev

**Comment by adamgoose** [comment]
Folks, we're working on it! I gotta work today, but will be able to get everything sorted out tonight.

**Comment by juan55860** [comment]
It is available for Laravel 5.2 ? I need support for this. thanks.

**Comment by filljoyner** [comment]
@adamgoose Thanks!

**Comment by chutch1122** [comment]
@adamgoose Thanks! We appreciate it.

**Comment by adamgoose** [comment]
Support added! :)

**Comment by juan55860** [comment]
Great ! :+1: Thanks
