### ISSUE TITLE
Can the FormBuilder returns form methods except POST and GET ?

### ISSUE THREAD

**Issue by jiaojie1989** [LaravelCollective/html#134]
There is one method named `getMethod` in `FormBuilder` class.
```php
protected function getMethod($method)
	{
		$method = strtoupper($method);

		return $method != 'GET' ? 'POST' : $method;
	}
``` 

I just want to know if I put `PUT` method into the `$method` field, then I got a `POST` however.

But I want a `PUT` method indeed.

**Comment by arthurkirkosa** [comment]
You should see a hidden input named _method with it's value set to PUT

**Comment by jiaojie1989** [comment]
Okey, I see there is a hidden area with `PUT`. 
Thanks a lot !
