### ISSUE TITLE
Empty csrf token value

### ISSUE THREAD

**Issue by camohub** [LaravelCollective/html#137]
Hello,
documentation says "CSRF token will be added to your forms as a hidden field automatically".
But it produces only token input with no value. 
``` html
<input name="_token" type="hidden">
```
I am on Laravel 5.2.5 
Can you tell me what's the matter?

**Comment by tshafer** [comment]
Please provide an example of your code.

**Comment by camohub** [comment]
Example can be whatever what starts with {!! Form::open() !!}. I found solution here http://stackoverflow.com/questions/34422751/why-is-my-csrf-token-empty-when-using-formopen and it works. But is it a best practice?

**Comment by tshafer** [comment]
Try clearing your sessions and cookies. Did you disable any session related middleware?

**Comment by arthurkirkosa** [comment]
In 5.2 you must nest your routes under a group that implements the ['web'] middleware group.

**Comment by camohub** [comment]
It should be mentioned in documentation. But ther is only "will be added to your forms .... automaticaly". How can people know it?

**Comment by tshafer** [comment]
How can people know what?

**Comment by arthurkirkosa** [comment]
In Laravel 5.2 ... it has nothing to do with the Html package.

**Comment by camohub** [comment]
I mean this https://laravelcollective.com/docs/5.2/html documentation not Laravel core doc. Is this an extension of Laravel isn't it?

**Comment by tshafer** [comment]
No, its not, Taylor didn't want to maintain it anymore so we took it over. Its just another package you can use now.

**Comment by camohub** [comment]
When did it happen? I return to Laravel after cca 2 months and csrf tokens worked right before. After 2 months people must search solution for csrf around the internet. I dont understand it.

**Comment by tshafer** [comment]
We took over while ago. CSRF has always worked, but @arthurkirkosa is right, you have to wrap it in a web middleware group, this is new for 5.2.

**Comment by camohub** [comment]
And that is the only thing which I would like to have in documentation.

**Comment by tshafer** [comment]
Send taylor a pull request.

**Comment by camohub** [comment]
Ok thanks. Have a nice day and whole new year.

**Comment by arthurkirkosa** [comment]
@tshafer a hint in the Html docs would help anyone using this package.

**Comment by tshafer** [comment]
@arthurkirkosa We are open to pull requests.

**Comment by arthurkirkosa** [comment]
Done https://github.com/LaravelCollective/docs/pull/18
