### ISSUE TITLE
[Laravel 5.2] Can't install LaravelCollective/html

### ISSUE THREAD

**Issue by nandanvrs** [LaravelCollective/html#138]
Can't install LaravelCollective/html package on Laravel 5.2.

Getting error from composer cmd. 
check screen shot below

![laravel-form](https://cloud.githubusercontent.com/assets/7125393/12075434/be5907ec-b1a6-11e5-8474-89297bbfd347.png)

**Comment by tshafer** [comment]
This isn't a problem with the package, please try here.

https://github.com/composer/composer/issues/4121

**Comment by nandanvrs** [comment]
Thanks @tshafer .
