### ISSUE TITLE
CSRF field doesn't has value attribute

### ISSUE THREAD

**Issue by fahmilatib** [LaravelCollective/html#139]
I tried to `open()` a form with the following code

```
{!! Form::open() !!}
{!! Form::close() !!}
```

Below is the generated HTML

```
<form method="POST" action="http://localhost/ongoing/laravel/public/articles/create" accept-charset="UTF-8"><input name="_token" type="hidden">
    </form>
```

Why is the CSRF token field doesn't has a value attribute? I've followed the installation guide properly https://laravelcollective.com/docs/5.2/html#installation

By the way I'm using your v5.2 and Laravel 5.2

**Comment by tshafer** [comment]
Take a look at middleware groups.

https://laravel.com/docs/5.2/middleware

**Comment by fahmilatib** [comment]
Ah sorry my bad. Thank you @tshafer

**Comment by tshafer** [comment]
Not a problem.
