### ISSUE TITLE
Generate form action attribute with parameter using "url"

### ISSUE THREAD

**Issue by fahmilatib** [LaravelCollective/html#140]
The [documentation](https://laravelcollective.com/docs/5.2/html#opening-a-form) shows how to pass in route parameters using `route` and `action` but how do we do the same using `url` ?

I tried this:

```
Form::open(['url' => ['articles/{id}/edit', $article->id]])
```

What I got:

```
action="http://localhost/ongoing/laravel/public/articles/{id}/edit/7"
```

What I was expecting

```
action="http://localhost/ongoing/laravel/public/articles/7/edit"
```

**Comment by StefanPrintezis** [comment]
This is what happens to your attributes when you send them as an array:
$this->url->to($options[0], array_slice($options, 1));
Everything but the first item is url parameter that is added to the end of the first element as you can determine from your example. If you're interested in how this is processed take a look at the to() function in the laravel UrlGenerator:
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Routing/UrlGenerator.php#L152

I think printing the id directly into the url is the best option for you if using routes is not an option.
'articles/' . $article->id . '/edit';

**Comment by fahmilatib** [comment]
Yes I guess that's the best option for now.
