### ISSUE TITLE
Form doesn't take route into account when deciding method

### ISSUE THREAD

**Issue by jamiehd** [LaravelCollective/html#141]
If I use Form::open with a named route, the __method field is not appended unless I also specify the method.

# Example:
## routes.php
`Route::patch('/foo/{thing}', ['uses' => 'FooController@doSomething', 'as' => 'named.route']);`

## View
```
{!! Form::open(['route' => ['named.route', $thing->id]]) !!}
{!! Form:close() !! }
```
### Expected Output
```
<form method="POST" action="http://myapp.local/foo/id" accept-charset="UTF-8" class="form-horizontal">
<input name="_token" type="hidden" value="x">
<input name="_method" type="hidden" value="patch">
</form>
```
### Actual Output
```
<form method="POST" action="http://myapp.local/foo/id" accept-charset="UTF-8" class="form-horizontal">
<input name="_token" type="hidden" value="x">
</form>
```
### Way to achieve expected output
```
{!! Form::open(['route' => ['named.route', $thing->id, 'method' => 'patch']]) !!}
{!! Form:close() !! }

**Comment by manureggi** [comment]
@jamiehd, I believe they did not add automatic method discovery mainly because it could cause issues when having multiple routes of the same name.
Consider, for example a situation where you have these routes:
```
Route::post('/foo/{id}', ['uses' => 'FooController@create', 'as' => 'foo']);
Route::update('/foo/{id}', ['uses' => 'FooController@update', 'as' => 'foo']);
Route::delete('/foo/{id}', ['uses' => 'FooController@destroy', 'as' => 'foo']);
```
How could the form tell which method to use?

**Comment by kimfarrell** [comment]
Why would you have multiple routes with the same name? That defeats half the point in naming them.

**Comment by jamiehd** [comment]
Why would you have multiple routes with the same name? That defeats half the point in naming them.

**Comment by manureggi** [comment]
Sometimes it is useful to have routes with the same name but that execute different actions based on http method (also, there is no restrictions in place, which means it is possible). That said, adding such functionality would mean considering this option as well (if you used the latter approach it might throw an exception and cause you app to crash in case you update the extension).

**Comment by mlantz** [comment]
I don't see this as a common issue. If you would like it changed please submit a PR. Thanks.
