### ISSUE TITLE
HtmlBuilder

### ISSUE THREAD

**Issue by alesl** [LaravelCollective/html#142]
It seems url should be escaped here:
https://github.com/LaravelCollective/html/blob/5.2/src/HtmlBuilder.php#L161

``` php
return $this->toHtmlString('<a href="' . $this->entities($url) . '"' . $this->attributes($attributes) . '>' . $this->entities($title) . '</a>');
```

**Comment by StefanPrintezis** [comment]
Url's should be encoded not escaped.

The url is generated using the UrlGenerator::class which already encodes it in the to() function if i'm correct. Where it's called:
https://github.com/LaravelCollective/html/blob/5.2/src/HtmlBuilder.php#L155

The parameters are encoded here.
https://github.com/laravel/framework/blob/5.2/src/Illuminate/Routing/UrlGenerator.php#L163

**Comment by alesl** [comment]
If this is intentional, then Html::link is not safe to be called by user provided url (at least without some whitelisting).

This:
`Html::link('" onclick="alert(1)', 'foo')`

Output:
`<a href="http://10.11.10.10:8000/" onclick="alert(1)">foo</a>`

Since browsers don't mind (from my experience at least) if url is escaped, I wouldn't mind if output would be against standards but safe by default.

**Comment by StefanPrintezis** [comment]
We could only print the href if it validates as an url.
I added filter_var when printing the url. It returns false if it's not valid and the url if it is, so an invalid url would be printed like this <a href="">foo</a>

`$this->toHtmlString('<a href="' . filter_var($url, FILTER_VALIDATE_URL) . '"' . $this->attributes($attributes) . '>' . $this->entities($title) . '</a>')`

Also found out that in the  laravel\UrlGenerator if an url starts with 'http://' then it would be consider valid. https://github.com/laravel/framework/blob/4.2/src/Illuminate/Routing/UrlGenerator.php#L488
`'http://;" onclick="alert(1)'` Would be considered a valid url...
