### ISSUE TITLE
Laravel 5.2 FormBuilder checkbox Model Error

### ISSUE THREAD

**Issue by erayaydin** [LaravelCollective/html#143]
Hello,

After 5.2 Form::checkbox doesn't work because its trying $this->model->toArray(); and $this->model is NULL. Because there is no "Form::model".

LaravelCollective/html - 5.1 branch - 1091. Line: 
```
return data_get($this->model, $this->transformKey($name));
```

LaravelCollective/html - 5.2 branch - 1110. Line:
```
return data_get($this->model->toArray(), $this->transformKey($name));
```

`$this->model->toArray()` to `$this->model` works.

Thank you.

**Comment by arcanedev-maroc** [comment]
Check this : #135

**Comment by erayaydin** [comment]
I tried `composer update` but its say **Nothing to install or update**

**Comment by joeybeninghove** [comment]
I'm getting this same error after upgrading to 5.2.  Any updates?

**Comment by pixelone** [comment]
Same issue here after upgrading from 5.1 to  L 5.2

I am getting:  

FormBuilder.php line 1110:
Call to a member function toArray() on null .. seems to only affect checkboxes. If I manually build out the input works fine. No issues in 5.1.

**Comment by joeybeninghove** [comment]
Yep, same here @pixelone.  We're only using a few checkboxes right now so I just manually built them out for now until this issue is resolved.

**Comment by codingquark** [comment]
I am getting the same error with radio controls.

**Comment by icedfish** [comment]
+1 checkbox run into error because of the v5.2.1  release

**Comment by arcanedev-maroc** [comment]
Like @codingquark said, try to use the 5.2.0 version, the 5.2.1 version is corrupted.

**Comment by KIDJourney** [comment]
Both checkbox and the radio failed

**Comment by pixelone** [comment]
Just tested what @arcanedev-maroc  mentioned, setting to 5.2.0 fixes it.  "laravelcollective/html": "5.2.0".

**Comment by adamgoose** [comment]
Reverted. Thanks!
