### ISSUE TITLE
Tests failed!

### ISSUE THREAD

**Issue by halaei** [LaravelCollective/html#144]
Please do not tag a commit with failed tests. v5.2.1 tag should be removed.
Thanks.

**Comment by skovmand** [comment]
+1 ... It floods my site with errors, suddenly 18 tests fail.

**Comment by sontdhust** [comment]
I run into the same problem with my checkbox input:
`{!! Form::checkbox('remember') !!}`
When I comment out this line, the error has gone away.
__Work around__: roll back to last release `composer require laravelcollective/html 5.2`
Please fix it.

**Comment by adamgoose** [comment]
Sorry, guys... It's been reverted!
