### ISSUE TITLE
Form Model Binding with Multiple Parameter

### ISSUE THREAD

**Issue by gandhyonly** [LaravelCollective/html#147]
How to make Form::model with multiple parameter?
i have example route like this.
www.domain.com/product/2/product-attributes/3/edit
in normal form i can do it like this:

form
method="POST" action="{{ route('product.{product}.product-attributes.update', [product->id, $product-attribute->id ]) }}"
endform

but if im trying to use laravelcolective/html Form::model() like this:

Form::model($productattributes, array('method' => 'POST', array('route' => array('product.{product}.product-attributes.update', [product->id, $product-attribute->id ])))

i get an error array to string conversion...

**Comment by adamgoose** [comment]
Try this:

```php
Form::model($product, ['method' => 'post', 'route' => ['product.product-attributes.update', $product->id, $product->attribute->id]])
```

Notice how the route name and *all* of the Route Parameters are included in one single flat array.
