### ISSUE TITLE
Form::select with placeholder should use 'disabled'

### ISSUE THREAD

**Issue by MartinWickman** [LaravelCollective/html#148]
```
echo Form::select('size', array('L' => 'Large', 'S' => 'Small'), null, ['placeholder' => 'Pick a size...']);
```

This generates an option

```
<option selected="selected" value="">Pick a size...</option>
```

But imo it should add a 'disabled' attribute to make it a "real" (unselectable) placeholder

```
<option selected="selected" disabled value="">Pick a size...</option>
```

**Comment by Skintillion** [comment]
So make a PR

**Comment by csspcc** [comment]
@MartinWickman Totally agree.

**Comment by MECU** [comment]
If the select element is optional, there would then be no way to deselect an option, essentially making this field required.

**Comment by Skintillion** [comment]
Good point @MECU. It has no value so detecting null in your validation makes more sense than making it always disabled.

**Comment by cyntechtic** [comment]
I noticed the select option with both 
Form::select('size', array('L' => 'Large', 'S' => 'Small'), null, ['placeholder' => 'Pick a size...']); and Form::select('size', array('L' => 'Large', 'S' => 'Small'), null, ['disabled' => 'disabled', placeholder' => 'Pick a size...']); conflict with jquery-ui

![capture](https://cloud.githubusercontent.com/assets/6288225/23512887/7cc20eea-ff62-11e6-92b5-9e9ef6ca1fa1.JPG)
the above design view shows the output applying the Form::select "null and placeholder" option for the current station label select option . How can we resolve this?

**Comment by natelloyd** [comment]
I'm fine with the change, but breaking changes like this SHOULD be listed somewhere. This radically changed the functionality for those who were using it as a selectable empty option, and there was nothing noted in the upgrade suggestions for this.

**Comment by bradgenereux** [comment]
This change makes it impossible for a select to be optional. I understand the why others want this, but it would probably be best as a parameter, something like `['disablePlaceholder' => true]`.

**Comment by natelloyd** [comment]
There are 2 distinct uses, one a placeholder that is required to be changed and once a selection is made it is not reversible (like checking a radio button), and the other is an option that has no value, but can be selected. 

The latter is useful to avoid having to push in the empty option to your option array. We have in house extended it to include that as well - 'placeholder' for forced selection and 'emptyoption' as selectable no-value option.

**Comment by michaelk83** [comment]
HTML5 has a standard `required` option for `select` tags, which is suitable for the concerns that were raised above - https://www.w3schools.com/tags/att_select_required.asp
If the `select` is required, its placeholder should be disabled. Otherwise it should be selectable.

**Comment by gbelot2003** [comment]
maybe as standard, but is annoying, what happen when I want to deselect a selected field and I don't want to select any others?? it's a real life case so is conflicted with that particular standard!!

**Comment by saidbakr** [comment]
In some cases adding `disabled` leads to problems with validation of input array.
```
<select name="cat[]">
<option disabled="disabled">Select</option>
```
In other words the placeholder should be submitted as an empty value.

**Comment by JoseDguez** [comment]
I think this should be an attribute like @bradgenereux suggested and set it to _true/false_, with this change my users are asking me to return the functionality to not select any of the options listed in the select if an option as already been selected...

**Comment by tshafer** [comment]
Please provide a pull request. Please note I wont accept boolean parameters in a function. The will all be removed at a later version.

**Comment by mvysh** [comment]
Still need a fix for this.
