### ISSUE TITLE
Wrong form method after redirecting with errors

### ISSUE THREAD

**Issue by chekovsky** [LaravelCollective/html#149]
Hi there!

I have the following form:

![bug0](https://cloud.githubusercontent.com/assets/12160864/12492071/95c30120-c065-11e5-9896-dd2bdc775928.png)

The first one post a PUT, and the second one post a DELETE.

When I first call this view, both forms are created as expected, one with _method PUT and the other with _method DELETE.

But, if I submit the PUT, and return to the same view with the following command:

``` php
return back()->withErrors(['some error on put'])->withInput();
```

then, both forms are created with PUT as method, as you can see here:

![bug](https://cloud.githubusercontent.com/assets/12160864/12492129/f822bf36-c065-11e5-86c9-af978d8046cd.png)

Could this be a bug?

Best regards,
Rafael.

**Comment by eric-famiglietti** [comment]
I am having this same issue.

**Comment by eric-famiglietti** [comment]
I am also seeing this issue. @rafael-renan-pacheco, have you found a workaround for this until it is fixed?

**Comment by rafael-renan-pacheco** [comment]
The workaround is to use pure html for your forms tag while my PR isn't merged :disappointed:

But pure html can be a problem if you use Form::modal to fillup lots of fields.

**Comment by eric-famiglietti** [comment]
The workaround I used was to explicitly define the method in the form.

```php
{!! Form::open(['url' => '...', 'method' => 'put']) !!}
    <!-- ... -->
{!! Form::close() !!}

{!! Form::open(['url' => '...']) !!}
    {!! method_field('delete') !!}
    <!-- ... -->
{!! Form::close() !!}
```

**Comment by rafael-renan-pacheco** [comment]
Of course! This will work too, thanks for the tip :smile:
