### ISSUE TITLE
htmlentities() expects parameter 1 to be string, array given (View:[path])

### ISSUE THREAD

**Issue by quiquegarcia** [LaravelCollective/html#15]
I want to send multiple values to my controller, but when I use:

```php
{!! Form::select('course_phases[]', $phases, null, ['class' => 'form-control', 'multiple']); !!}
```
or
```php
{!! Form::text('course_phases[]', null, ['class' => 'form-control', 'multiple']); !!}
```

I'm getting this exception

```php
htmlentities() expects parameter 1 to be string, array given (View:[path])
```

Then I switched to illuminate/html with no changes on my view and works fine, what I'm doing wrong with this package?

EDIT: Forget it, my problem was a javascript outside my form with an input text embbeded, don't know yet how happened!

**Comment by quiquegarcia** [comment]
Same problem with illuminate/html, only fails when I select an element from the list.

**Comment by Decadence** [comment]
How did you resolve this?
Look at https://github.com/LaravelCollective/html/issues/122

**Comment by quiquegarcia** [comment]
In this specific case it was a text field generated dynamically by a javascript with the same name but outside my form tag, it was a very extrange behaviour.

**Comment by Decadence** [comment]
Ok.
But name[] notation doesn't work properly now. Only if you assign explicit index: name[1].
I see your controls have [] names, does it work in your case?

**Comment by quiquegarcia** [comment]
I think that the mentioned  javascript it was doing that, injecting the indexes. That view it was removed from the project in favor of using VueJS

**Comment by mybigman** [comment]
I see it still is not resolved...

Have the same issue using -

name[]

I had to manually build the HTML form data as a workaround.
