### ISSUE TITLE
Form date not formatted correctly when taken from a model

### ISSUE THREAD

**Issue by magnusjt** [LaravelCollective/html#154]
Form::date() formats the date as 'Y-m-d' only if the value is given directly. If the value is taken from a model, the default formatting for Carbon is used instead (Y-m-d H:i:s). When the latter format is used, some browsers don't display the date at all.

**Comment by adamgoose** [comment]
Check out the docs here: https://laravelcollective.com/docs/5.2/html#form-model-accessors

There's a new feature in 5.2 that lets you control this.
