### ISSUE TITLE
Have Form Builder show $value before considering old input

### ISSUE THREAD

**Issue by samtheson** [LaravelCollective/html#164]
We have some forms in our app whose values get transformed on form submission (in a Form Request). So on validation failure when the form is shown again the transformed value will be shown which is not what we want, because we have our helper functions that change them back.

So that's one case. The general case being a field whose value comes from a custom helper function which produces a different value each time it is called, so when such a helper's output is displayed in the view with `Form::text('theField', ourHelper($params))` the Form Builder will go with what's in the session flash - which is fair.

I'm proposing to work on an optional extra option for the Form Builder calls which allows for such cases as these, where we tell the Form Builder to go with the value we've passed before (or without) looking for old input.

Thoughts?

**Comment by StefanPrintezis** [comment]
You could do the validation in the post function like this:
```
if (!$form->isValid()) {
  $input = request()->input();
  $input['field_name'] = 'new_random_value';
  redirect()->back()->withErrors($form->getErrors())->withInput($input);
}
```

**Comment by screenager** [comment]
Yes, this is also useful in another use case, in which you submit a form, redirects you to an overview that a form to filter on the data, but using (logically) the same field names.. Those fields will then display the flashed data

**Comment by tshafer** [comment]
We accept pull requests.
