### ISSUE TITLE
link_to_back feature idea

### ISSUE THREAD

**Issue by kneipp** [LaravelCollective/html#166]
Hi there!
https://gist.github.com/kneipp/263ca5cdf901814f74cf

The suggestion is add a helper with custom titles and attributes to redirect user back when click in some static html link.

But i'm not sure best way to add: back()->getTargetUrl() dependency to helper.
I check the package is included on composer: "illuminate/routing": "5.2.*",

What do you think?
If you like I can create PR with your code suggestion.
Thanks.

**Comment by mlantz** [comment]
I'm always a fan of PRs over issues/ feature requests :) but seems like a good idea
