### ISSUE TITLE
Unwanted Question Mark

### ISSUE THREAD

**Issue by tannernelson** [LaravelCollective/html#17]
`{!! link_to_route('users.index', 'Users') !!}`

Is resulting in

`url.com/users?`

There should be no extra question mark at the end of the URL

**Comment by tshafer** [comment]
Please provide your route.



—
Tom Shafer

**Comment by tannernelson** [comment]
`Route::resource('users', 'UserController');`

This?

**Comment by tshafer** [comment]
Are you using annotations anywhere for your resource?

**Comment by vitor-faiante** [comment]
@tannernelson I have just tried to do the same as you however my link does not cine with the ? question mark.

**Comment by tshafer** [comment]
I am not seeing this either. Is this still happening?

**Comment by bgoliveira** [comment]
Yep, still happening.

**Comment by raphaelbeckmann** [comment]
This also happened to me until I realised that the third parameter should be `[]` instead of `null` when you do not want to pass any route params.
