### ISSUE TITLE
Unchecked checkboxes value is not sent via form

### ISSUE THREAD

**Issue by pjmartorell** [LaravelCollective/html#172]
One option to solve this is to do it like in the Rails framework, as stated in this article: [http://nielson.io/2014/02/handling-checkbox-input-in-laravel/](http://nielson.io/2014/02/handling-checkbox-input-in-laravel/)

**Comment by socieboy** [comment]
This is not a issue! if you have to check in the server side if the check exists other way the check was unchecked.

**Comment by pjmartorell** [comment]
@socieboy It's not an issue, it's a suggestion/improvement based on what it's done in other frameworks.

**Comment by rafael-renan-pacheco** [comment]
As Mei Gwilym said on that link in your first post:

> $request->input('confirm', false);

This is very easy to read and understand. There is no need for duplicated inputs.

**Comment by pjmartorell** [comment]
@rafael-renan-pacheco I already knew this workaround but anyway
