### ISSUE TITLE
Defining class for Form::select

### ISSUE THREAD

**Issue by RanZix** [LaravelCollective/html#175]
I want do define class of select form. Tried this but didn't work. Couldn't find answer on documentation.

`echo Form::select('size', array('L' => 'Large', 'S' => 'Small'), array('class' => 'form-control'));`

**Comment by StefanPrintezis** [comment]
The third argument of Form::select is the selected element
public function select($name, $list = [], $selected = null, $options = [])

Try it like this.
echo Form::select('size', array('L' => 'Large', 'S' => 'Small'), NULL, array('class' => 'form-control'));

**Comment by RanZix** [comment]
Ok got it, thanks :)
