### ISSUE TITLE
submit doesn't take a custom value

### ISSUE THREAD

**Issue by DrowningElysium** [LaravelCollective/html#177]
Could the submit button be rewritten to use `<button type="submit">` instead of `<input>`? This way it is possible to add a custom value to the submit button.

**Comment by rafael-renan-pacheco** [comment]
https://laravelcollective.com/docs/5.2/html#buttons

One way:
```
echo Form::button('Click Me!', ['type' => 'submit']);
```

Another way, pure html:
```
<button type="submit">Click Me!</button>
```

In my projects, I don't use Form::submit or Form::button to render buttons, because pure html is much more simpler.

**Comment by DrowningElysium** [comment]
It's true that pure html is simpler, but when creating a select box(which we do a lot) we don't want to switch between styles. So we just went ahead and did full Form. 

And yes button would work. But I do think the form::submit should be of type button. This way it's possible to add some more options.

**Comment by tshafer** [comment]
We accept pull requests. I suggest making another function.
