### ISSUE TITLE
Fill value with current Request

### ISSUE THREAD

**Issue by Decadence** [LaravelCollective/html#180]
Hello. Thanks for great package.

Is there any way to make it fill form inputs with current Request values without making

```
return back()->withInput();
```

For example I have form with filters and it generates HTML-response from POST request (without redirect) and I want input values to stay filled.
AFAIK Form Facade gets value from old input (after redirect), from explicit value, from model attribute.
So can you add ability to auto refill fields without redirect and without writing every value with Request::get("is_there_any_value")?

**Comment by Decadence** [comment]
Does even anybody look at the issues here?

**Comment by tshafer** [comment]
You can manually set the value

https://github.com/LaravelCollective/html/blob/5.2/src/FormBuilder.php#L161

**Comment by Decadence** [comment]
I can manually set value with request() helper, but I want to Builder sets it for me based on input name like it does from old input automatically (or model attribute)

**Comment by tshafer** [comment]
There is no way to do this right now. We do consider pull requests.


— 
Tom Shafer

**Comment by Decadence** [comment]
I know there is no way :( It was not issue but more feature request.

**Comment by Decadence** [comment]
@tshafer I would like to make PR, but I have very basic knowledge about Laravel Package development.
Is this feature hard to implement? Something like this in getValueAttribute method:

```php
$request_value = Request::get($name);
if (! is_null($request_value)) {
    return $request_value;
}
```

I failed to test this because had "RuntimeException: A facade root has not been set." error and I was unable to find out the proper way to use Facade (or request() helper) inside package.

**Comment by Decadence** [comment]
@tshafer https://github.com/LaravelCollective/html/pull/217

**Comment by Decadence** [comment]
Bump.

**Comment by Decadence** [comment]
Seems like no one cares so I close it in prefer to PR.
