### ISSUE TITLE
Form attribute mutator not working for dates

### ISSUE THREAD

**Issue by nunomazer** [LaravelCollective/html#182]
I've created a formFooAttribute mutator but it is never executed for a Form::date field.

**Comment by ArondeParon** [comment]
Experiencing the same issue here.

**Comment by ArondeParon** [comment]
Did some digging around in the core code and it seems that the documentation on this feature is not complete.

In order to use the model accessor, you have to use the `FormAccessible` Trait in your model. Origins of this check can be found in `FormBuilder.php`:

 ```
   /**
     * Get the model value that should be assigned to the field.
     *
     * @param  string $name
     *
     * @return mixed
     */
    protected function getModelValueAttribute($name)
    {
        if (method_exists($this->model, 'getFormValue')) {
            return $this->model->getFormValue($name);
        }

        return data_get($this->model, $this->transformKey($name));
    }
```

**Comment by mlantz** [comment]
Hey @ArondeParon want to put in a PR to update the docs? Thanks.

**Comment by ArondeParon** [comment]
Nice to see this included @mlantz. Apologies for not picking this up myself; ironically, I only saw this notification and not the one you sent a year ago.

**Comment by mlantz** [comment]
No worries, I'm doing my best to do some clean up with a release soon with the updates that have been done to start getting things back on track :)
