### ISSUE TITLE
Form::text not render var js

### ISSUE THREAD

**Issue by alcir-junior-caju** [LaravelCollective/html#183]
Does anyone know why the Form::text does not render a var js and Form::label renders?

// var js incremented
x++
// Here rendering, I can get the value
{!! Form::label("answer[][answer_name_en]", "Opção Inglês", ["class" => "control-label"]) !!}

// Here does not render, and I can not get the value
{!! Form::text("answer[][answer_name_en]", null, ["class" => "form-control"]) !!}

**Comment by mlantz** [comment]
Is this still a concern?
