### ISSUE TITLE
Form::select selected value not determined correctly 

### ISSUE THREAD

**Issue by bioteck** [LaravelCollective/html#184]
The comparison to determine if a value is selected is not strict, and this is a problem if there is, for example, "1" and "01" in the list. Espacially with multiple select (both options are seen as selected even if there is only one who is).

**Comment by muvasco** [comment]
I had the same problem here. 

The string comparison on getSelectedValue function is using loose operator, so it evaluates equally "1" and "01".

http://ideone.com/6wt9JA

**Comment by tshafer** [comment]
Merged
https://github.com/LaravelCollective/html/pull/274
