### ISSUE TITLE
Form::number - model binding not working

### ISSUE THREAD

**Issue by sunnyjayjay** [LaravelCollective/html#185]
I am using all the collective Form facade functions in a large form and they work perfectly. Except Form::number does not return the value from the database (model binding).

```
{!! Form::number('price', null, ['id' => 'price', 'class' => 'form-control form-inline', 'style' => 'width:150px']) !!}
```

Any ideas?

**Comment by Decadence** [comment]
I can't reproduce this bug.
You should consider that browser can hide original value if it's unable to convert value to number.
You can check html source of your page and check if value is in code.

As you can see Builder sets the value, but browser deleted it as invalid.
![screenshot_1](https://cloud.githubusercontent.com/assets/1434668/17618997/636a3ab0-608b-11e6-8421-c4e966dde6b3.png)

**Comment by tshafer** [comment]
Closed due to inactivity.
