### ISSUE TITLE
Access form element attributes without needing to provide a default value

### ISSUE THREAD

**Issue by chrisbeaver** [LaravelCollective/html#186]
I find an issue with Form Model binding and passing form element attributes. Suppose I want to apply a class "form-control" to my text input which is using form model binding. I need to pass a total of three parameters now to the input;

Form::text('name', '', ['class' => 'form-control']);

This forced second parameter will now supersede the data attribute from the database. I'm suggesting we make a change to Form::input, checking $value to see if it's null, and if so allowing the session input or database attribute to populate the form element as it would normally.

**Comment by tshafer** [comment]
Pass it as null.


— 
Tom Shafer

**Comment by chrisbeaver** [comment]
Thanks!
