### ISSUE TITLE
can't use laravel 'old' helper in Form::select()

### ISSUE THREAD

**Issue by jagroop** [LaravelCollective/html#189]
Hello i am trying to add Laravel old [Helper](https://laravel.com/docs/5.2/helpers#method-old)

as follows => 
`Form::select('size', array('L' => 'Large', 'S' => 'Small'), old('value'));` [#laracollective](https://laravelcollective.com/docs/5.0/html#drop-down-lists)

> but it selects completely different value in case if validation fails :disappointed: 

Here is my code

`{!! Form::select('ingredientUnit', array(
                                                '' => 'Select Unit',
                                                'g' => 'g',
                                                'tbsp' => 'tbsp',
                                                'ml' => 'ml',
                                                'sprinkles' => 'Sprinkles'
                                            ), old('ingredientUnit')) !!}`

Thanks

**Comment by jackleblack** [comment]
I encounter the same problem.

**Comment by adamgoose** [comment]
Off the top of my head, I believe that you don't need to use the helper explicitly. The library checks for old input and uses it automatically. Try removing the helper.

**Comment by patrick-riemer** [comment]
I have the same problem with multiple select. It does not work with or without form helper.

**Comment by jagroop** [comment]
@mlantz Sir, what makes you think that this issue should be closed ?

**Comment by perskinet** [comment]
Hello I've made some investigation and the problem is in method in laravelcollective/html/src/FormBuilder.php:

`protected function getSelectedValue($value, $selected)
    {
        if (is_array($selected)) {
            return in_array($value, $selected, true) ? 'selected' : null;
        } elseif ($selected instanceof Collection) {
            return $selected->contains($value) ? 'selected' : null;
        }

        return ((string) $value == (string) $selected) ? 'selected' : null;
    }`


Especially:

` in_array($value, $selected, true) `


If you turn off strict mode at in_array function everything works well, now the question is how to put right type of value to this method. 

I am running code on php 7 if that helps.

Regarding to @patrick-riemer i thing it's a bug :)

**Comment by jakjr** [comment]
My solution was create an accessor for the attribute used to populate the select. Eg:

    {{ Form::select('role_id[]', $user->roles, null, ['class' => 'form-control', 'multiple' => true]) }}

On UserModel:

    public function getRolesAttribute()
    {
        return collect($this->attributes['roles'])->transform(function($item, $key){
            return (int)$item;
        })->toArray();
    }

This way, the value is an integer and the getSelectedValue works properly (is_array using strict mode)
