### ISSUE TITLE
could add other UI like datepicker, select2?

### ISSUE THREAD

**Issue by yuomtheara** [LaravelCollective/html#2]
I think that, it is good it add other UI like datepicker, select2...?

**Comment by tshafer** [comment]
Adam and I are discussing a lot of possibilities at this time. We will let you know.

**Comment by yuomtheara** [comment]
Thanks for your reply.

**Comment by adamgoose** [comment]
While discussing the best way to enhance these packages, we have decided that adding client-side libraries to this doesn't quite fit. This is precisely why Taylor decided to remove HTML from the core - he wants to encourage community packages to fill that need.
