### ISSUE TITLE
More elegant handling of unchecked checkboxes

### ISSUE THREAD

**Issue by archfrog** [LaravelCollective/html#200]
I know that HTTP does not send a value if a checkbox or radio button is unchecked, but for the sake of consistency and simplicity, I'd like to suggest that the HTML Form builder always synthesizes this value if necessary.  

As it is now, you have to do silly checks in your code to see if a checkbox has been set or not set, instead of simply using the value (false or true).

I personally think that the HTTP behavior, of not sending a value for an unchecked checkbox, just goes to show how many mushrooms the inventors of HTTP managed to consume in their younger years...

Right now I have code like this in my controller's store method:

'''

```
public function create_post(ContactFormRequest $request)
{
    $checkboxes = [ 'member', 'public_advisor', 'family_advisor', 'patient_advisor', 'other' ];

    $columns = Schema::getColumnListing('contacts');
    $values  = [];
    foreach ($columns as $column)
    {
        // Incrementing field, cannot be set.
        if ($column == 'contact')
            continue;

        // Handle checkboxes specially because HTML::FormBuilder doesn't help us.
        if (in_array($column, $checkboxes))
            $value = ($request->input($column, false) ? 1 : 0);
        else
            $value = $request->input($column);

        $values[$column] = $value;
    }

    $contact = new Contact($values);
    $contact->save();

    return redirect('contact/create')->with('message', 'Kontakt oprettet');
```

}

'''

I can see that many others on the 'net have similar issues and all sorts of incorrect and partially bogus fixes are suggested.  This should be solved at the source, i.e. the HTML Form builder, not in 20,000 different apps using more or less incorrect hacks.

**Comment by ZhangYiJiang** [comment]
I don't disagree with your sentiment, but what do you actually want the form builder to do? All it does is spit out HTML. Presumably [making it do this for checkboxes](http://stackoverflow.com/a/1992745/313758) will work 

    <input type='hidden' name='checkbox' value='0' />
    <input type='checkbox' name='checkbox' value='1' /> 

but this will break any existing apps that use a `is_null` check and form validation, which is a fairly major sticking point (no matter what the implementation is), and I can't tell if this isn't yet another of the 'more or less incorrect hacks' you talk about.

**Comment by archfrog** [comment]
I think maybe I submitted this issue the wrong place :-)  Would it be Laravel itself that should handle this case?  I guess so.  I read somewhere that there are issues with using the hidden field method as well as with most of the suggestions that people come up with.  Can't remember the issue right now, but it has something to do with Chrome or something.

I'll try resubmitting this issue with the Laravel folks instead.

**Comment by diogogomeswww** [comment]
What about creating a new method that returns
`<input type='hidden' name='checkbox' value='0' />`
`<input type='checkbox' name='checkbox' value='1' /> `

`Form::checkboxWithUnchecked` or something like this?

I'm sure that this will help a lot.
I'm happy to make the PR, just say so and choose the name for the new method...

**Comment by archfrog** [comment]
I remember the issue with hidden fields now; there's apparently a problem if you re-submit a form that includes a hidden field.  Either the field doesn't get included or something goes wrong.  I think the proper solution is that Laravel, not Form builder, synthesizes the false value when no value is present.

**Comment by diogogomeswww** [comment]
Ok, never heard about that problem.
Thanks
