### ISSUE TITLE
Impossible to override label "for" attribute

### ISSUE THREAD

**Issue by velosipedist** [LaravelCollective/html#201]
If i call

``` php
Form::model($myModel)
```

and later 

``` php
Form::label('attribute', 'Attribute', ['for' => 'custom_id']);
```

anyway i get

``` html
<label for="attribute">Attribute</label>
```

**Comment by velosipedist** [comment]
Also, for full consistency, `Form::checkbox()` should also implicitly generate id attribute if not specified, respecting brackets at `name[]` if specified.

**Comment by mrossa93** [comment]
Do

    Form::label('custom_id', 'Attribute');
