### ISSUE TITLE
Less than elegant handling of readonly fields.

### ISSUE THREAD

**Issue by archfrog** [LaravelCollective/html#208]
I have some fields that are sometimes read-only and sometimes not.  Naturally, I try to share the view between these two roles, so I added a `$readonly` variable, which the controller passes in, and tried the naïve way of doing this:

```
{!! Form::text('city', null, ['class' => 'form-control', 'readonly' => $readonly]) !!}
```

It turns out, according to my experiments, that the Form builder looks at the existence of the `readonly` attribute, not at its value.  It doesn't matter if `$readonly` is true or false, if it is present, the field becomes readonly.  So I have to do this:

```
    @if ($readonly)
    {!! Form::text('city', null, ['class' => 'form-control', 'readonly' => true]) !!}
    @else
    {!! Form::text('city', null, ['class' => 'form-control']) !!}
    @endif
```

Which I find less than elegant and also much more likely to introduce bugs as it is a copy-paste-and-edit piece of code.

I guess this can be handled in a backwards compatible fashion by always making the field read-only if there's no boolean value specied and otherwise make use of the boolean value.

**Comment by Decadence** [comment]
I think it corresponds HTML specification.
To make field readonly you usually do:

```html
<input readonly /> or <input readonly="readonly" />
```
It doesn't have true or false value, only existance.
So helper follows this logic and inserts key as attribute value if there is no value in attribute array for this key and doesn't consider true / false value for any of keys. I think handling some attributes with other fashion will complicate attributes output.

As workaround you can do something like this somewhere in controller action:
```php
if($readonly){
   $attributes["readonly"] = "readonly";
}
```

and pass it to the view.

**Comment by archfrog** [comment]
Okay, my view is just that Form Builder (and all software) should try to present a coherent API no matter what quirks exist in the underlying technologies.  As a form builder user, I really don't care too much how the code looks like in HTML, I simply want a logical and sensible API to use :-)  The fact that I have to use an @if/@endif block around the readonly attribute reveals that the underlying technology is strange.

**Comment by Decadence** [comment]
I agree but seems like authors don't attend too much on features request, so only way to implement this is your PR.

**Comment by Decadence** [comment]
https://github.com/LaravelCollective/html/pull/188

**Comment by archfrog** [comment]
Cool! :-)
