### ISSUE TITLE
getRadioCheckedState() incorrectly evaluates the checked state of radio buttons with numerical values

### ISSUE THREAD

**Issue by JackWH** [LaravelCollective/html#209]
Hi,

Excuse the lengthy description but hopefully this might help someone else who finds themselves in these very narrow set of circumstances 😄 

In my application I've been trying to allow the option to have radio buttons be all unchecked by default, and force the user to make a choice. However, the values of my radio buttons are all numeric integers, i.e.:

`<input name="my_field" type="radio" value="0"> First Label Goes Here<br/>`
`<input name="my_field" type="radio" value="1"> Second Label Goes Here<br/>`

etc.

This caused a problem in my app, as if a radio button was not selected, HTTP would not push an empty value - it just doesn't submit the field in the `POST` data at all.

So, to work around, I added a hidden input before each of the radio buttons:

`<input type="hidden" name="my_field" value="" />`

This servers to push through a blank value that I can use to validate against.

However, on page reload after submitting a blank value, I noticed the FormBuilder was checking the first option by default, every single time. I tracked it down to the `getRadioCheckedState` function:

```
protected function getRadioCheckedState($name, $value, $checked)
{
    if ($this->missingOldAndModel($name)) {
        return $checked;
    }

    echo "<code>".$this->getValueAttribute($name)." - ".$value."</code><br/>";

    return $this->getValueAttribute($name) == $value;
}
```

The evaluation `return $this->getValueAttribute($name) == $value;` will always return `TRUE` in my case, as `$this->getValueAttribute($name)` returns an empty string, which when compared with `==` to a `$value` of `0` is equal to `TRUE`.

So I then tried to set my hidden input value as follows: `<input type="hidden" name="my_field" value="not_set" />`, and thought I'd use a custom validation rule to prevent `not_set` being the value. However it turns out an empty string is `==` to `not_set` as well.

I believe the solution is to simply change this line:

`return $this->getValueAttribute($name) == $value;`

to this:

`return (string) $this->getValueAttribute($name) === (string) $value;`

to use a strict comparison, and convert both values to the same data type. I would make a pull request, but I'm not sure if there's something I've not considered (any advice would be appreciated) - or my situation is just too much of an edge case.

Thanks!

**Comment by tshafer** [comment]
We accept pull requests.
