### ISSUE TITLE
Issue with Form::date() when using form-model binding

### ISSUE THREAD

**Issue by ProjektGopher** [LaravelCollective/html#21]
When null is being passed as the value to Form::date() to allow form-model binding to automatically set it, it's not being formatted into Y-m-d as it would be if the value were to be input manually. Instead it's the full DateTime string.

Form::model() // edit.blade.php
Form::date('started_at', $model->started_at, $options) //_form.blade.php
// returns properly

Form::model() // edit.blade.php
Form::date('started_at', null, $options) // _form.blade.php
// returns full DateTime and doesn't get treated properly by the browser

Form::open() // create.blade.php
Form::date('started_at', $model->started_at, $options) // _form.blade.php
// throws an exception, as $model doesn't exist yet

Form::open() // create.blade.php
Form::date('started_at', null, $options) // _form.blade.php
// treated properly by browser

**Comment by ProjektGopher** [comment]
fixed by duplicating
$value = $this->getValueAttribute($name, $value);
from input() into date() resulting in
	/**
	 * Create a date input field.
	 *
	 * @param  string  $name
	 * @param  string  $value
	 * @param  array   $options
	 * @return string
	 */
	public function date($name, $value = null, $options = array())
	{
        $value = $this->getValueAttribute($name, $value);
		if ($value instanceof DateTime)
		{
			$value = $value->format('Y-m-d');
		}

		return $this->input('date', $name, $value, $options);
	}

**Comment by tshafer** [comment]
Can you make a pull request for this please, as well as a test?
