### ISSUE TITLE
Drop-Down with Disabled Empty Placeholder 

### ISSUE THREAD

**Issue by FilipQL** [LaravelCollective/html#210]
Hi,

There is an option for an Empty Placeholder:

`echo Form::select('size', ['L' => 'Large', 'S' => 'Small'], null, ['placeholder' => 'Pick a size...']);`

but, it would be nice to have an option to make it disabled, for example something like this:

'placeholder' => ['Pick a size...', **disabled**]

```
<select>
  <option value="" selected disabled>Pick a size...</option>
  <option value="saab">Saab</option>
  <option value="vw">VW</option>
  <option value="audi">Audi</option>
</select>
```

**Comment by Luizgpp** [comment]
I need this too. 
Can find a solution?

**Comment by FilipQL** [comment]
@Luizgpp No, for now. Of course, you can create drop-down (select) element without using LaravelCollective.

**Comment by Luizgpp** [comment]
OK thanks :)

**Comment by JoseCage** [comment]
@Luizgpp @FilipQL 
The disabled argument wont be in '' not??

Example:
```
 {!! Form::select('genre', array( 'm' =>'Male', 'f') => 'Female'), ['class' => 'class-name-here', 'placeholder' => 'Select your genre'] !!}
```

:computer: :package:

**Comment by mjpvandenberg** [comment]
I believe this should be default behavior.

**Comment by andres9366ha** [comment]
It work perfectly on chrome
                    {!! Form::select('genre', array('opt1' =>'Option1', 
                    'opt2' => 'Option2'), null, array('placeholder' => 'Select your option')) !!}

**Comment by tshafer** [comment]
We accept pull requests.

**Comment by sngrl** [comment]
May be some changes here after 3 years?
