### ISSUE TITLE
undefined getStatusCode() in Exceptions\Handler::render

### ISSUE THREAD

**Issue by loranger** [LaravelCollective/html#211]
Hello,

First, thank you so much for this awesome laravel package which makes development much easier.

I met a bug while implementing custom error pages: Laravel 5.2 provides a nice error pages system, but I need to fallback on a catch-all error page when the requested statusCode view does not exists.

So here is the (simplified) code I use in my `Exceptions\Handler.php` file:

``` php
public function render($request, Exception $e)
{
  $status = $e->getStatusCode();
  $view = 'errors.catch-all';

  if(view()->exists(sprintf($view_mask, $status))){
    $view = sprintf('errors.%s', $status);
  }

  return response()->view($view, ['code' => $status]);
}
```

It looks quite simple, but it fails: `getStatusCode`can be dumped but throws a fatal exception:

```
Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Debug\Exception\FatalThrowableError::getStatusCode() in /var/web/app/Exceptions/Handler.php
...
```

After some investigations, I tried to reproduce the bug with a fresh new laravel install and everything worked. So I tried to re-install all my beloved packages one by one and the issue came back with laravelcollective/html.

I went back to my initial code and commented the `Collective\Html\HtmlServiceProvider::class,` line and the fatal error was gone (but of course, a new one appeared regarding the lack of `FormFacade`)

I'm quite confused about this issue. how can I fix this, or at least bypass the ExceptionHandler in order to make my custom error page work ?

**Comment by kyranb** [comment]
I'm having the same issue. Would love some insight :)

**Comment by mlantz** [comment]
I believe `$e->getStatusCode` is the main issue there Exceptions have `getCode` not `getStatusCode` http://php.net/manual/en/exception.getcode.php

**Comment by josegus** [comment]
> I believe `$e->getStatusCode` is the main issue there Exceptions have `getCode` not `getStatusCode` http://php.net/manual/en/exception.getcode.php

Lie, some laravel excepcions has getStatusCode method (abort(), for example)

**Comment by Scott-Tresor** [comment]
J'ai le meme probleme sur  mon laravel 6
