### ISSUE TITLE
relative url in FormBuilder::open()

### ISSUE THREAD

**Issue by purificant** [LaravelCollective/html#212]
How can I use `FormBuilder::open()` to create a form action with relative url?

**Comment by purificant** [comment]
There does not seem to be a way to have relative urls instead of absolute urls with `FormBuilder`. Even though `UrlGenerator` supports building relative urls through a parameter in [UrlGenerator::route()](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Routing/UrlGenerator.php#L308)  and [UrlGenerator::action()](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Routing/UrlGenerator.php#L597)

Would the maintainers be open to a patch that adds support for using relative urls in [FormBuilder::open()](https://github.com/LaravelCollective/html/blob/5.2/src/FormBuilder.php#L114), [FormBuilder::getAction()](https://github.com/LaravelCollective/html/blob/5.2/src/FormBuilder.php#L955) and [FormBuilder::getRouteAction()](https://github.com/LaravelCollective/html/blob/5.2/src/FormBuilder.php#L1001)?

**Comment by tshafer** [comment]
Feel free to make a pull request.

**Comment by Decadence** [comment]
@tshafer
Does anybody review them? My PR (and many others) has no attention for a week already. I know you are not tech support for quick response but your repos look like dead and "feel free to make PR" sounds like "feel free to make some senseless work".

**Comment by mlantz** [comment]
Sorry @Decadence I have been intending to but my new company has been gaining traction and I've been trying to keep up. I assure you the repos will get time in the very near future and they are FAR from dead. Thank you for the concern though.

**Comment by tshafer** [comment]
Sorry, I've been out of the country for a while. Will get with Adam and Matt and run though these all when we get time.

**Comment by Decadence** [comment]
Still no time?
