### ISSUE TITLE
Html::style/script support for new attributes

### ISSUE THREAD

**Issue by thevukaslt** [LaravelCollective/html#213]
Hey,
as we know, new standarts are coming for resource hrefs and I strongly believe it should be supported by Html helper as well. There should be an option for integrity and crossorigin attributes.

Here's related example: http://stackoverflow.com/questions/32039568/what-are-the-integrity-and-crossorigin-attribute

**Comment by mlantz** [comment]
Is this still an issue?

**Comment by thevukaslt** [comment]
Does it support additional attributes?

To be honest, I'm no longer use Html::style/script shortcuts in my workflow so really don't know.
