### ISSUE TITLE
Laravel 5.3 Support

### ISSUE THREAD

**Issue by SuperlativeEntity** [LaravelCollective/html#220]
When installing Laravel 5.3, I get the following error:
laravelcollective/html v5.2 requires illuminate/view 5.2.*

**Comment by SuperlativeEntity** [comment]
Just read your twitter feed: require version `5.3.x-dev`

**Comment by mreschke** [comment]
Using 5.3.x-dev requires `"minimum-stability": "dev"` which pulls in ALL thousand dev packages, not good.  Please make an actual non dev branch.

**Comment by adamgoose** [comment]
You have two options:

1. Require `5.3.x-dev`
2. Require `5.3.*`, and add `"minimum-stability": "dev", "prefer-stable": true` to your `composer.json`.

**Comment by adamgoose** [comment]
The stable branch will land this weekend.
