### ISSUE TITLE
Can't install laravelcollective/html in Laravel 5.3

### ISSUE THREAD

**Issue by ggfernando94** [LaravelCollective/html#221]
when try to install in this way
`"laravelcollective/html": "5.3.*"`
get this error

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package laravelcollective/html 5.3.* is satisfiable by laravelcollective/html[5.3.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by socieboy** [comment]
When would be this repo ready for that?

**Comment by adamgoose** [comment]
https://github.com/LaravelCollective/html/issues/220#issuecomment-241861669

5.3 will be tagged stable this weekend
