### ISSUE TITLE
Forms for nesting resources

### ISSUE THREAD

**Issue by skys215** [LaravelCollective/html#222]
Hi
    I'm dealing with nesting resources right now, and found that I need to pass the parent resource variable manually to let the action url generate correctly.

```
// routes.php
Route::resource('user.address', 'AddressController');

//form blade
{!! Form::open([
    'route'=>[
            'user.address.store',
            'user'=>$user  //<-- Manually passing the 'parent resource'
            ]
    ])
!!}
```

Can it be done automatically?
Or there's no intention to implement such a feature?

Thanks.

**Comment by akiyamaSM** [comment]
I don't see any automatique way to do it to be honest. the form has no way to know what instance it will use unless you mention it.

**Comment by mlantz** [comment]
I agree with @akiyamaSM
