### ISSUE TITLE
Add support for laravel 5.3

### ISSUE THREAD

**Issue by shadoWalker89** [LaravelCollective/html#229]

**Comment by mlantz** [comment]
Its being worked on thank you.

**Comment by shadoWalker89** [comment]
@mlantz is there an eta please ??

**Comment by maniix123** [comment]
Yes please! I badly neeeeed this for L 5.3!!

**Comment by shadoWalker89** [comment]
@maniix123 use this for now https://github.com/LaravelCollective/html/issues/220#issuecomment-241861669

**Comment by maniix123** [comment]
@shadoWalker89 Thanks.
