### ISSUE TITLE
Undefined form

### ISSUE THREAD

**Issue by IndeDude** [LaravelCollective/html#230]
## {!! Form::open(...) !!} generates Undefined Form.

Even did a fresh install of laravel.

Laravel Framework version 5.3.6
PHP 7.0.10-2+deb.sury.org~xenial+1 (cli) ( NTS )

**composer.json** 
{
  //
"require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3._",
        "barryvdh/laravel-ide-helper": "^2.2",
        "laravelcollective/html": "^5.3"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9._",
        "phpunit/phpunit": "~5.0",
        "symfony/css-selector": "3.1._",
        "symfony/dom-crawler": "3.1._"
    },
//
}

**config/app.php**

'providers' => [
//
  Collective\Html\HtmlServiceProvider::class,
//

'aliases' => [
//
       'Form' => Collective\Html\FormFacade::class,
        'Html' => Collective\Html\HtmlFacade::class,

```
],
```

**Comment by adamgoose** [comment]
Can you please provide code and output examples?

**Comment by IndeDude** [comment]
Hi
Thank you for your quick response.
I reinstalled laravel and forms and everything is now working as
advertised.

I will close the ticket when I get back to my desk.
Thanks again for the awesome support.

**Comment by vlakoff** [comment]
Have you reached back to your deck?

:trollface:
