### ISSUE TITLE
Prefilling a form throws error for certain model properties

### ISSUE THREAD

**Issue by Cratyz** [LaravelCollective/html#235]
So I have created an issue here ( https://github.com/laravel/framework/issues/15394 ) that prevents me from having an eloquent model with a column-name/property named 'append'. When I use `{!! Form::model() !!}` in combination with that eloquent model (which is empty since its supposed to be a creation-form), it will throw an error when prefilling the input named `append` because it conflicts with a property of the abstract eloquent class.

I think i've tracked it down to a certain line of code, see:
https://github.com/LaravelCollective/html/blob/5.3/src/FormBuilder.php#L1096

Using `return $this->model->getAttributeValue($name);` here (or in the subsequent function, line nr 1115) seems to solve the issue.

My form does not error when I pass a filled model (which means an update-form).

Any thoughts on this?

---

EDIT: I've created a patch which solves it for me; simply adding the getFormValue to the model like:

```
public function getFormValue($name)
    {
        return $this->getAttributeValue($name);
    }
```

**Comment by mlantz** [comment]
At this time I'm not so sure its within the scope of this project to solve a case like that. I'm glad you found a solution
