### ISSUE TITLE
Html and Form macros in 5.3 with Service Provider

### ISSUE THREAD

**Issue by netm** [LaravelCollective/html#237]
I am trying to get macros working for Html and Forms with a service provider. The code is here [](https://gist.github.com/netm/8ad839e49fedfa7ba3cdade9ed993d3e) but I get an error I can't solve - can anybody put me on the right track? If I get it working I'll write it up somewhere for other newbies as a reference :-)

```
Type error: Argument 2 passed to Collective\Html\HtmlBuilder::__construct() must implement interface Illuminate\Contracts\View\Factory,...
```

**Comment by mlantz** [comment]
Is this still an issue for you?

**Comment by tshafer** [comment]
Closed due to inactivity.
