### ISSUE TITLE
HTML helps documentation

### ISSUE THREAD

**Issue by harrisoftware** [LaravelCollective/html#24]
Under Forms and HTML, in the documentation (readme) for this section, there's no mention of the HTML helpers that the package supports. Or I missed something.

**Comment by tshafer** [comment]
http://laravelcollective.com/docs/5.0/html#labels

**Comment by harrisoftware** [comment]
I was referring to the HTML::<helpers>
or are they not in this package/supported anymore?

**Comment by adamgoose** [comment]
@harrisoftware Can you please give an example of what you're referring to? The documentation was copied from the original Laravel package.

**Comment by tshafer** [comment]
You can also view all functions here

https://github.com/LaravelCollective/html/blob/5.0/src/HtmlBuilder.php

**Comment by adamgoose** [comment]
Never mind - I see what you mean. Let me look into this and see if we missed some documentation from Laravel. I'm pretty sure it wasn't documented in the Laravel docs. We may or may not add it at this point.

**Comment by tshafer** [comment]
We did miss some documentation.

Thanks for letting us know. I will will get this fixed either today or tomorrow.

**Comment by harrisoftware** [comment]
so it is supported::awesome

thanks

W

**Comment by vanquang9387** [comment]
@tshafer Sorry but I still don't see document about "HTML" helper at https://laravelcollective.com/docs/5.1/html

Or I miss something?

**Comment by tshafer** [comment]
https://github.com/LaravelCollective/html/blob/5.4/src/HtmlBuilder.php
