### ISSUE TITLE
HtmlBuilder

### ISSUE THREAD

**Issue by alesl** [LaravelCollective/html#241]
If macro method throws BadMethodCallException it is incorrectly wrapped in new BadMethodCallException exception with misleading error message.

Example:

```
Html::macro('test', function() {
   throw new BadMethodCallException('Something went wrong');
});

try {
  Html::test();
} catch(Exception $ex) {
 // Method test does not exist.
  echo $ex->getMessage();
}
```

Additional check `hasMacro` should be put put [here](https://github.com/LaravelCollective/html/blob/5.3/src/HtmlBuilder.php#L556) instead of wrapping it in try catch. This way it becomes unnecessary.

**Comment by vlakoff** [comment]
Submitted #247 to fix this.
