### ISSUE TITLE
Action Route Spoofing on Model

### ISSUE THREAD

**Issue by tylerwiegand** [LaravelCollective/html#243]
When I use the "standard" Form::model() method, it correctly spoofs for most actions. However (and I'm not sure if this is intended), when I point the action to my route of a resource, it still attempts to POST instead of the spoofed _put or _patch methods. I had to specify the method for it to talk to my route properly. The error indicator was:

```
MethodNotAllowedHttpException in RouteCollection.php line x:
in RouteCollection.php line x
at RouteCollection->methodNotAllowed(array('GET', 'HEAD', 'PUT', 'PATCH', 'DELETE')) in RouteCollection.php line x-13
```

Current, working form line:

```
{!! Form::model($role, ['action' => ['RolesController@update', $role->slug], 'method' => 'PUT']) !!}
```

Example, unworking form line:

```
Form::model($role, ['route' => ['roles.update', $role->id]])
```

Current pertinent route list line:

```
|        | PUT|PATCH | roles/{role}                            | roles.update  | App\Http\Controllers\RolesController@update                            | web,auth,acl |
```

Hope this helps someone.

**Comment by Benestar** [comment]
Stumbled upon the same issue. `Form::model` doesn't work very well with unsupported Http methods when using `Route::resource`. When looking at the source code, the library doesn't even try to find the correct method and just assumes `POST` when nothing is given. The `route` option is only used to determine the action url. [1]

However, one could try to fetch the actual `Route` object and the choose one of the methods provided [2] inside, eg. take the first one in the list.

[1] https://github.com/LaravelCollective/html/blob/5.3/src/FormBuilder.php#L955
[2] https://laravel.com/api/5.1/Illuminate/Routing/Route.html#method_getMethods

**Comment by mlantz** [comment]
So the idea here is that it should collect the method from the route/action provided?

**Comment by claytonrcarter** [comment]
If I'm understanding correctly, I just ran into the same thing. When we define routes, we have to specify the method. Then, if we use `Form::model()` and refer to that route by name (or Controller action name) it seems counterintuitive to have to re-specify the method. Having `Form::model()` lookup the method for us would be very nice.

**Comment by tshafer** [comment]
We accept pull requests.
