### ISSUE TITLE
Form input rules

### ISSUE THREAD

**Issue by parmap** [LaravelCollective/html#244]
Can you guys please add rules from request into form? As optional parameter e.g., or setter into HtmlBuilder and switch in methods as  `addRules=true|false`

Blade:
`{!! Form::text(name = 'foo', value = null, options = ['class' => 'form-control'], request = App\Http\Requests\FooRequest) !!}`

Request:
`['name' => 'required|max:50']`

Result:
`<input type="tex" name="foo" value="" class="form-control" required max="50">`

This would be possible for these rules, which are supported by html input or representable as pattern.

**Comment by akiyamaSM** [comment]
I don't know if it will be used or not, but I'm working on it

**Comment by akiyamaSM** [comment]
and its done 
#250

**Comment by akiyamaSM** [comment]
@mlantz would you check my contribution?
