### ISSUE TITLE
Checkboxes and attribute casting

### ISSUE THREAD

**Issue by Isigiel** [LaravelCollective/html#25]
When using Eloquent Attribute casting for an array the checkbox is not able to retrieve the model value. It thinks the model is an object but the accessed attribute is an array, that leads to the object_get method returning null. A possible quickfix is converting every model to an array.
```php
    /**
	 * Create a new model based form builder.
	 *
	 * @param  mixed  $model
	 * @param  array  $options
	 * @return string
	 */
	public function model($model, array $options = array())
	{
		$this->model = $model->toArray();

		return $this->open($options);
	}
```

Maybe someone can come up with a better way to manage that.

**Comment by tshafer** [comment]
Can you give me code examples of what you are doing?

**Comment by Isigiel** [comment]
I have a Model $user->role where role is eloquent casted to an array. Your way of determining if a checkbox is checked is to access the model based on its type, which is an object. But the levels under role are array ones, that causes the model access function to return null

**Comment by garygreen** [comment]
@Isigiel can you test if PR #33 fixes this issue?

**Comment by Isigiel** [comment]
I'll do, maybe takes some days ...
