### ISSUE TITLE
Form::old not returning any values

### ISSUE THREAD

**Issue by techn0guy** [LaravelCollective/html#251]
I'm trying to retrieve an old value of an object within a view. I'm using form model binding and yet nothing is returning. If I simply use a preset text field within the view the old data appears correctly as seen here:
`{!! Form::text('title',null,['class'=>'form-control']) !!}`

But if I try and call Form::old() nothing returns
`{!! Form::old('title') !!}`

Shouldn't this successfully return the old value?

**Comment by StefanPrintezis** [comment]
You need to flash your input to the session to access them using the old() function
request->flash($filter = null, $keys = [])
or
redirect()->withInput(...)
