### ISSUE TITLE
Shouldn't use Laravel's faulty e()

### ISSUE THREAD

**Issue by rudiedirkx** [LaravelCollective/html#254]
FormBuilder and HtmlBuilder use Laravel's `e()` helper:

```
return htmlentities($value, ENT_QUOTES, 'UTF-8', false);
```

The `false` means not everything is HTML encoded: `&amp;` stays `&amp;`. For literal values, like a form, that's very odd and very wrong. Currently, there's no way to type `&amp;` in a Laravel form, because it's saved as `&`. Laravel doesn't consider this a bug, so they won't change it. A form builder should be very very literal and exact, so this package shouldn't use `e()`.

In case you're wondering _Why would you ever type an `&amp;`?_: well, in this case, when I'm talking about `&amp;`. What I type should be stored and displayed literally, whatever the scenario, not with some magic sauce.

Instances where this truly is relevant:
- `FormBuilder::option()` uses `HtmlBuilder::attributes()` (and then `e()`) to encode the value, which is now wrong
- `FormBuilder::textarea()` prints the textarea value with `e()`
- And more...

**Comment by rudiedirkx** [comment]
Anyone home?

**Comment by Decadence** [comment]
Don't be surprised, this repo is so slow to react.

**Comment by StefanPrintezis** [comment]
It's fixed in #258

**Comment by garygreen** [comment]
@StefanPrintezis your fix has broken a lot of stuff for me and should not have been merged. Although I agree with the reason behind fixing (this issue) it's fix should be LIMITED to textareas and inputs that have literal text, not to everything (selects, etc).

**Comment by tshafer** [comment]
@garygreen are you still having issues?

**Comment by tshafer** [comment]
Closed due to inactivity.
