### ISSUE TITLE
autocomplete for Laravel

### ISSUE THREAD

**Issue by akoper** [LaravelCollective/html#255]
I use autocompletes a lot when I am making an application. There is a form, and the user needs to enter a value for one of the form fields from a list of values that are in a database table (foreign key relationship). Laravel makes text, radio, checkbox, etc. inputs. Can Laravel make an autocomplete input, too? This is becoming a very basic type of form field. The next-best, normal of way making autocompletes with jQuery UI autocomplete is messy and inelegant, with hidden form fields for the id, and hacking it so the name shows in the input field, etc. If Laravel had some elegant, beautiful, native way to make form field autocompletes, this would be a powerful selling point for developers; save a lot of work; be a great, legitimate use of the framework; and increase Laravel's adoptions and use.

**Comment by akiyamaSM** [comment]
it means to re implement it using javascript?

**Comment by jonasdiel** [comment]
something like https://twitter.github.io/typeahead.js/ working with Eloquent 
would be perfect

**Comment by akiyamaSM** [comment]
what about this #256
