### ISSUE TITLE
Replace htmlentities with htmlspecialchars

### ISSUE THREAD

**Issue by vlakoff** [LaravelCollective/html#265]
Laravel [has replaced](https://github.com/laravel/framework/pull/15159) `htmlentities` with `htmlspecialchars` in the `e()` helper. I couldn't agree more with this change :)

So, we may consider doing similar changes in the HTML builder.

Also refs the related #258.

**Comment by garygreen** [comment]
This should have been the proper fix for #258.

Also, could we use this issue as way of coming up with ideas to avoid all the `$escape = false` type arguments on the html/form builder functions? I think there are already too many arguments for a number of form builder functions. Laravel's `e()` function makes use of `HtmlString` object to determine if data is safe, maybe we could move towards that as an option for marking text as safe?
