### ISSUE TITLE
Form input lack string //avvv// 

### ISSUE THREAD

**Issue by thanhtungka91** [LaravelCollective/html#267]
Laravel Version: 5.0
PHP Version:5.4
Database Driver & Version:
Description:

in Input of form if value = //abbb/// -> it doesnt show all the full of value-> not save correct data to db.
example:
{!! Form::text('patternCode', , ['id' => 'pattern_code', //abbb///,'class' => 'ag__input']) !!}

Steps To Reproduce:

{!! Form::text('patternCode', , ['id' => 'pattern_code', //abbb///,'class' => 'ag__input']) !!}
Please refer this issue. 
https://github.com/laravel/framework/issues/16701

**Comment by thanhtungka91** [comment]
any support from the laravel team? @adamgoose

**Comment by thanhtungka91** [comment]
any support?

**Comment by Decadence** [comment]
Don't be surprised, this repo is so slow to react.

**Comment by mlantz** [comment]
I'm afraid I don't understand the root of the problem here. The examples provided do not make sense as is, nor does the example value. Also @decadence I understand we've been busy and have not been very responsive but I would appreciate a little slack given that all of the contributors have busy day jobs and contribute when they can spare some time.

**Comment by decadence** [comment]
@mlantz We all appreciate yours contributing and this package is very useful with Laravel development (by the way I don't fully understand why it was excluded from the core). But when I see 8 month old issues / PR without any reaction it makes me wonder maybe it's worth to find person with a little more time for some tasks. Anyway thanks and please no offense.

**Comment by mlantz** [comment]
Non taken @decadence sorry if I was snappy - I was reading that at like 4am - I'm trying to refocus some time so we don't end up with large time gaps like this again - its all about baby steps. I always appreciate help in sorting out valid and invalid issues - that can make all the difference in putting together releases.
