### ISSUE TITLE
Larvel creating html section

### ISSUE THREAD

**Issue by yashitripathi** [LaravelCollective/html#27]
laravel 5 it start to showing blank white page after adding 'Collective\Html\HtmlServiceProvider' in provider and   'Form' => 'Collective\Html\FormFacade','Html' => 'Collective\Html\HtmlFacade' for using form tag,I have  update the composer successfully .Im working linux (mint).Thanks in advance.

**Comment by tshafer** [comment]
Please check your apache or nginx logs.

**Comment by tshafer** [comment]
Any progress on this?
