### ISSUE TITLE
Is it possible to disable option on Form::select()?

### ISSUE THREAD

**Issue by deleugpn** [LaravelCollective/html#271]
Assume the following code: 

```
{!! Form::select('status', $status->toArray(), $ticket->status_id, ['class' => 'form-control', 'disabled' => [5, 6]]) !!}
```

Granted, the hard-coded `5` and `6` isn't ideal, but I'm not worrying about that right now, my goal is: is it possible to get options to be disabled using the package (based on value or display value or anything at all)?

Thanks.

**Comment by Decadence** [comment]
AFAIK no.
