### ISSUE TITLE
missed id for select field with name for multiple

### ISSUE THREAD

**Issue by EugeneG9** [LaravelCollective/html#272]
When I creating select field with `multiple` enabled, there are no default `id`
    `{{Form::label('skills', 'Skills')}}`
    `{{Form::select('skills', \App\Skill::pluck('name', 'id'), null, ['id' => 'skills', 'name' => 'skills[]', 'class' => 'select2-offscreen', 'multiple'])}}`

So i need to set id manually, What I am doing wrong?

**Comment by akiyamaSM** [comment]
the select input should have an id with name of 'skills'

**Comment by arcanedev-maroc** [comment]
Can you try this :

```blade
{{ Form::label('skills[]', 'Skills') }}
{{ Form::select('skills[]', \App\Skill::pluck('name', 'id'), null, ['class' => 'select2-offscreen', 'multiple']) }}
```

**Comment by tshafer** [comment]
Close due to inactivity.
