### ISSUE TITLE
Updating composer file

### ISSUE THREAD

**Issue by yashitripathi** [LaravelCollective/html#28]
While updating composer it shows Call to undefined method Illuminate\Foundat  
  ion\Application::getCachedCompilePath() in /var/www/laravel-project/vendor/  
  laravel/framework/src/Illuminate/Foundation/Console/ClearCompiledCommand.ph  
  p on line 28        .Working on linux fresh install    .

**Comment by tshafer** [comment]
Try deleting the compiled file in the vendor directory and regenerating it.

run `php artisan clear-compiled && composer update`

**Comment by tshafer** [comment]
Any update on this?
