### ISSUE TITLE
Laravel upgrade to 5.4

### ISSUE THREAD

**Issue by TheNerka** [LaravelCollective/html#281]
Can't upgrade Laravel to 5.4 because needs LaravelCollective/html 5.4

**Comment by PilloryBarnDesign** [comment]
https://github.com/LaravelCollective/html/pull/276

**Comment by indigoram89** [comment]
+1!!!

**Comment by Daniesy** [comment]
+1

**Comment by AmrAhmedFekry** [comment]
+1

**Comment by kossa** [comment]
How to install the version 5.4? from PR ?

**Comment by dilumdarshana** [comment]
Small issue comes up with laravel 5.4 in HtmlServiceProvider.php. Which is getToken() deprecated. We should use token() instead..
