### ISSUE TITLE
When will support laravel 5.4

### ISSUE THREAD

**Issue by Mahdi-Sahib** [LaravelCollective/html#287]
$ composer require "laravelcollective/annotations":"^5.3.0"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravelcollective/annotations ^5.3.0 -> satisfiable by laravelcollective/annotations[v5.3.0].
    - Conclusion: remove laravel/framework v5.4.4
    - Conclusion: don't install laravel/framework v5.4.4
    - laravelcollective/annotations v5.3.0 requires illuminate/filesystem 5.3.* -> satisfiable by illuminate/filesystem[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/filesystem v5.3.0|don't install laravel/framework v5.4.4
    - don't install illuminate/filesystem v5.3.16|don't install laravel/framework v5.4.4
    - don't install illuminate/filesystem v5.3.23|don't install laravel/framework v5.4.4
    - don't install illuminate/filesystem v5.3.4|don't install laravel/framework v5.4.4
    - Installation request for laravel/framework (locked at v5.4.4, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.4].

**Comment by adamgoose** [comment]
Please create this issue in laravelcollective/annotations.
