### ISSUE TITLE
Checkbox with value "true" returns "", in previous version it returned the correct 1

### ISSUE THREAD

**Issue by BadChoice** [LaravelCollective/html#291]
In the last update

`Form::checkbox("field",true)` comes to the request as `""` before it returned the proper `1`

however

`Form::checkbox("field", 1, $checked, $options)` works as always

**Comment by dantonel** [comment]
I'm having the same issue with Form::hidden.  This tag:
{!! Form::hidden('confirmed', true) !!}
was translating to
<input name="confirmed" type="hidden" value>

I reverted back to laravelcollective/html v5.2.4 and it was working propertly again:
<input name="confirmed" type="hidden" value="1">

**Comment by BadChoice** [comment]
Yeah, using `5.2.4` works

**Comment by mlantz** [comment]
This is working as expected in 5.4 as well.

**Comment by mlantz** [comment]
Ok, I found the root of the issue and all branches will be updated with the solution
