### ISSUE TITLE
Html style and script

### ISSUE THREAD

**Issue by gzai** [LaravelCollective/html#294]
Hello,

Can Html style or script looping just like this ?

{!! Html::style(
'style01.css',
'style02.css',
'style03.css',
'etc'
); !!}

{!! Html::script(
'script01.js',
'script02.js',
'script03.js',
'etc'
); !!}

I look in the vendor laravelcollective, both function just handle 1 data

**Comment by janstieler** [comment]
Hi,
I have the same question.

**Comment by tshafer** [comment]
We accept pull requests.
