### ISSUE TITLE
Escaping problems

### ISSUE THREAD

**Issue by garygreen** [LaravelCollective/html#296]
This issue is to unify all the escaping-related problems recently introduced by PR #258 

Following on from the above PR, there has been a series of PR's which add a `escape` parameter option to combat the automatic escaping.  #260 #292 and probably more will follow.

Other's haved noticed a problem too; #293 and http://stackoverflow.com/questions/42007328/laravel-blade-formselect-now-forcing-escape

Firstly, this change should not have been introduced as it was breaking change in a patch version.

Secondly, the automatic escaping is good for inputs which require literal text, but adding an `$escape` parameter to everything doesn't sound like an ideal thing.

Proposed fix:

1. Revert #258, it was breaking and should not have been put in.

2. **In 5.5?** Use Laravel's `e()` which has now switched to using `htmlspecialchars` and fixes the side effects introduced by #258 
3. **In 5.5?** Do away with the `$escape` parameters and instead make use of `HtmlString()` safe-objects instead. Laravel's `e()` has automatic support for it.

**Comment by StefanPrintezis** [comment]
I'm not really sure what to do with attributeElement(), because most values should be double encoded and some shouldn't. Now all the attributes are escaped, except the once statically set like the optgroup label=".

**Comment by mlantz** [comment]
Hey @garygreen it was an honest mistake to merge in the breaking change and an oversight on my part. In relation to that, we follow the versioning of Laravel with the 5.3, 5.4 etc so . You do have the option to use the previous version of 5.3 in order to prevent the breaks locally. That being said, I'm happy to fix things and update 5.3 and 5.4 branches to ensure that things are both functional and secure.

**Comment by vlakoff** [comment]
Thanks for linking to the various issues that arose.

Just one thing, the Laravel's switch from htmlentities to htmlspecialchars is unrelated to this. Your suggested fixes 1 and 2 are in fact the same.

**Comment by StefanPrintezis** [comment]
In my #258 PR I didn't think about support for html entities in labels for example, which could be fixed by adding support for Htmlable objects in htmlbuilder->entities() as @garygreen stated in his 3rd proposed solution. But then everyone will have to use Htmlable objects to display these entities, instead of doing it in their templating engine "{!!".

**Comment by adaur** [comment]
One more user affected here. If not reverted, this should definitely be mentionned somewhere in the docs.

**Comment by spamoom** [comment]
Happy for this to be re-introduced on a non-patch version. Have many sites showing `&hellip;` in fields at the moment due to this.

A revert is needed sooner rather than later imo

**Comment by vlakoff** [comment]
Agree. Let's just revert it, for now.

**Comment by mlantz** [comment]
Hey all, ok, I'm happy to revert it, will do and release asap.

**Comment by mlantz** [comment]
The PR in question is directed at 5.4 is everyone here having issues with 5.4 or with 5.3 just to clarify.

**Comment by spamoom** [comment]
The issue I'm having is with 5.3 at the moment - I'm sure devs will have issues with both though

**Comment by mlantz** [comment]
K, I'm going to do a full reversion across both branches and release tonight, thanks guys for the feedback, please keep me posted on anything critical like this.

**Comment by garygreen** [comment]
@mlantz any news on reverting the change? With that said, PR #297 looks like it would fix the problems people are experiencing with escaping.

**Comment by mlantz** [comment]
Yeah sorry my weekend went crazy, I'm hoping to work on this stuff tonight

**Comment by Mopster** [comment]
Also just encountered this problem when upgrading to 5.4, my ul list of links is no longer working.

```
{!! Html::ul([
    Html::linkRoute('group_voicemail'),
    Html::linkRoute('group_pin),
], ['style' => 'margin-bottom:0;'])  !!}
```

**Comment by rudiedirkx** [comment]
As an aside, I agree with 

> In 5.5? Do away with the `$escape` parameters and instead make use of `HtmlString()` safe-objects instead. Laravel's `e()` has automatic support for it.

More power to the developer.

**Comment by eness** [comment]
+1 here. Form::select() converts all entities in option's text parts.

**Comment by garygreen** [comment]
@mlantz @adamgoose @tshafer any news on when this can be reverted? It's been 2 months for this bug which is too long to wait for a fix. As mentioned before, it should not have been been merged in the first place and so many apps have been affected by it.

**Comment by mlantz** [comment]
@garygreen can you confirm that #315 fixes this issue. Trying to follow all these threads is getting crazy
