### ISSUE TITLE
Macro Not Functioning in 5.4

### ISSUE THREAD

**Issue by 19peaches** [LaravelCollective/html#301]
I needed to customize the placeholder option for my selects so I created a macro inside a service provider like so:

```php
/**
 * Bootstrap the application services.
 *
 * @return void
 */
public function boot()
{
    Form::macro('mselect', function($name, $list = [], $selected = null, $options = []) {
        $selected      = Form::getValueAttribute($name, $selected);
        $options['id'] = Form::getIdAttribute($name, $options);

        if (! isset($options['name'])) {
            $options['name'] = $name;
        }

        $html = [];

        if (isset($options['placeholder'])) {
            $html[] = $this->placeholderOption($options['placeholder'], $selected);
            unset($options['placeholder']);
        }

        foreach ($list as $value => $display) {
            $html[] = Form::getSelectOption($display, $value, $selected);
        }

        $options = Html::attributes($options);

        $list = implode('', $html);

        return Form::toHtmlString("<select{$options}>{$list}</select>");
    });
}

/**
 * Create a placeholder select element option.
 *
 * @param $display
 * @param $selected
 *
 * @return \Illuminate\Support\HtmlString
 */
protected function placeholderOption($display, $selected)
{
    $selected = Form::getSelectedValue(null, $selected);

    $options = compact('selected');
    $options['value'] = '';

    return Form::toHtmlString('<option disabled' . Html::attributes($options) . '>' . Html::escapeAll($display) . '</option>');
}
```

And then of course added the provider in my app config.

There are no docs for 5.4 so maybe something has changed, but I'm getting an error that `Method mselect does not exist. `

Why would my macro not be found?

**Comment by dakshhmehta** [comment]
+1 I can replicate same. Want to add one thing is that it is even going to macro function. Just not functioning at blade level.

**Comment by vlakoff** [comment]
I cannot reproduce it. The only explanation I can think of, is that maybe you did some mistake and the service provider isn't actually executed.

**Comment by mlantz** [comment]
Yeah I was having issues replicating this in a few ways. First I found that by having it do `return "<select{$options}>{$list}</select>"` made it work fine. You appear to be calling a protected method which is causing the system to break `toHtmlString` is protected. You will also notice that `getSelectedValue` is a protected method meaning you cannot access it which is causing the fails

**Comment by vlakoff** [comment]
Also note the [Macroable](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Support/Traits/Macroable.php) trait uses [`bindTo`](http://php.net/manual/en/closure.bindto.php), so in your macro callback, `$this` refers to the Form class instance, not the service provider.
