### ISSUE TITLE
Ampersand escaping in HTML attribute

### ISSUE THREAD

**Issue by mikerockett** [LaravelCollective/html#302]
I'm using this to output a text input:

```php
Form::text("name", null, [
    'role' => 'set_name',
    'data-titlecase' => 'ucfirst',
    'data-inputmask-type' => 'Regex',
    'data-inputmask-regex' => '[A-Za-z0-9\\s-\\(\\)&]{2,70}',
])
```

The package appears to be escaping the ampersand in the `data-inputmask-regex` attribute, resulting in:

```html
<input ... data-inputmask-regex="[A-Za-z0-9\s-\(\)&amp;]{2,70}">
```

At first, I thought it was the template engine (Twig), but using the `raw` filter didn't fix anything. (Note: above translated to PHP code for ease of reference.)

Is there something I can do to prevent this?

**Comment by mikerockett** [comment]
Update: this doesn't appear to affect Inputmaskss behaviour; it must be decoding the expression appropriately. However, could this still create potential issues? I'm not sure regarding the spec, but should ampersands be escaped inside attributes?

**Comment by mlantz** [comment]
Currently the attributes are wrapped in the Laravel e method. https://laravel.com/docs/5.4/helpers#method-e to prevent this, the only thing I can think of is to make a macro which could bypass it - something like this:


```Form::macro('data_field', function ($name, $value, $data) {
    $dataAttributes = '';
    foreach ($data as $key => $value) {
        $dataAttributes .= $key.'="'.$value.'"';
    }
    return '<input name="'.$name.'" type="text" value="'.$value.'" '.$dataAttributes.'>';
});```
