### ISSUE TITLE
Make package available for laravel 5.4

### ISSUE THREAD

**Issue by bantawa04** [LaravelCollective/html#306]
Please make the package available for laravel 5.4. Without this package we are stuck on  laravel 5.3

**Comment by ArondeParon** [comment]
Could you clarify on this? I am currently using this package with Laravel 5.4 without any issues.

**Comment by dhandarbeit-tk** [comment]
(The documentation does not state that yet.)

Just use composer ie like:
"laravelcollective/html": "5.4.*"
