### ISSUE TITLE
Type error: Argument 1 passed to Collective\Html\FormBuilder::setSessionStore() must be an instance of Illuminate\Contracts\Session\Session

### ISSUE THREAD

**Issue by biancaro** [LaravelCollective/html#309]
In trying to update from 5.3 to 5.4.1, I get the following error:
Type error: Argument 1 passed to Collective\Html\FormBuilder::setSessionStore() must be an instance of Illuminate\Contracts\Session\Session, instance of Illuminate\Session\Store given, called in /home/vagrant/Projects/projectname/vendor/laravelcollective/html/src/HtmlServiceProvider.php on line 54

In my composer.json file I am using:
"require": {
        "php": ">=5.6",
        "laravel/framework": "5.4.*",
        "laravelcollective/html": "5.4.1"
    },

Any ideas on why this error is occurring?

**Comment by trideout** [comment]
You need to delete ./bootstrap/cache/compiled.php
