### ISSUE TITLE
No need for CSRF hidden field

### ISSUE THREAD

**Issue by qodeboy** [LaravelCollective/html#312]
Hello,

```FormBuilder.php:1044``` says 

```
// If the method is something other than GET we will go ahead and attach the
// CSRF token to the form, as this can't hurt and is convenient to simply
// always have available on every form the developers creates for them.
```

But this actually can hurt. In case page is cached, token will be cached along with it resulting in ```TokenMismatchException```. Laravel is smart enough to look into ```X-XSRF-TOKEN``` cookie which is set automatically. So do we really need to put hidden field on forms after all?

Thanks,
Paul.

**Comment by mlantz** [comment]
I'm unable to replicate it that a form can be submitted without the csrf field in 5.4. I'm going to close this but if you can provide documentation or a use case I'd be happy to review. Thanks.
