### ISSUE TITLE
Default value in multiple selection

### ISSUE THREAD

**Issue by FuriosoJack** [LaravelCollective/html#313]
I want to know how I do it so that the multiple selection is a value that is selected by default.

I've this
`
{!!Form::select('rol[]', \App\Rol::pluck('description', 'id'), null, ['multiple' => true, 'id'=>'rolesLista']); !!}`

Which results in this
`
<select multiple="1" id="rolesLista" name="rol[]"><option value="1">Usuario</option><option value="2">Operador</option><option value="3">Administrador</option></select>`

I want it for example. Administrator and User. Already selected

**Comment by acorbeil-b367** [comment]
You have to change your null value by the selected values. This is the field for default value.

https://laravelcollective.com/docs/5.3/html#drop-down-lists

```php
{!! Form::select('rol[]', \App\Rol::pluck('description', 'id'), $selectedValues,[
    'multiple' => true, 'id'=>'rolesLista'
]); !!}
```

The default value can be an array with the id of Administrador and Usuario.

```php
{!! Form::select('rol[]', \App\Rol::pluck('description', 'id'), [1,3], [
    'multiple' => true, 'id'=>'rolesLista'
]); !!}
```
or
```php
$selectedValues = [1,3];
{!! Form::select('rol[]', \App\Rol::pluck('description', 'id'), $selectedValues, [
    'multiple' => true, 'id'=>'rolesLista'
]); !!}
```

**Comment by marcelogarbin** [comment]
@acorbeil-b367 Does not that work anymore?

**Comment by acorbeil-b367** [comment]
@marcelogarbin What do you mean? What doesn't work?

**Comment by marcelogarbin** [comment]
@acorbeil-b367 I'm using some JS packages, I believe it's some that's conflicting with multiple select. I am checking. Right now Everything is normal with the LaravelCollective/Html package. Thank's

**Comment by ryssbowh** [comment]
Hi,

I also have been struggling with this :
I was giving values as an array indexed by integers but not starting from 0.
my default values were an array of integers with index starting at 0 and wasn't working for some reason.
If my default values is an array of strings, then it works, here are two dumps of the following code :
`dump($this->options['items']);
dump($this->options['default']);
return FormFacade::select($name, $this->options['items'], $this->options['default'], $this->options['attributes']);`

Working :
![2](https://user-images.githubusercontent.com/6736613/56077751-de461f00-5dd7-11e9-9ec8-1102488227cb.png)

Not working:
![3](https://user-images.githubusercontent.com/6736613/56077772-fcac1a80-5dd7-11e9-9335-a298e20e94d7.png)

All I changed between the two is casting my default values as strings.
Hope that helps
