### ISSUE TITLE
link_to_action with html as anchor text?

### ISSUE THREAD

**Issue by stefkes** [LaravelCollective/html#316]
This shows the html and not the font awesome icon. How can I fix this?

```
{!! link_to_action(
'admin\MyController@edit', 
'<i class="fa fa-edit"></i>', 
$item['id'], 
$attributes = ['class' => 'btn btn-default btn-sm']) 
!!}
```

**Comment by veganista** [comment]
For that you would need to be able to pass the escape attribute to `link_to_action` which the library doesn't support.

You might be able to do it with:

```php
{!! link_to(
action('admin\MyController@edit'), 
'<i class="fa fa-edit"></i>', 
$item['id'], 
$attributes = ['class' => 'btn btn-default btn-sm'],
null,
false) 
!!}
```

Probably more readable to not use `link_to` in this instance though.

```html
<a href="{{ action('admin\MyController@edit', ['id' => $item['id']]) }}" class="btn btn-default btn-sm">
    <i class="fa fa-edit"></i>
</a>

```

**Comment by mlantz** [comment]
We're adding in the escape option which should resolve this.

**Comment by stefkes** [comment]
@mlantz is this available now or coming soon?
