### ISSUE TITLE
5.4 or 5.3 with Laravel 5.4 project?

### ISSUE THREAD

**Issue by piotrowski** [LaravelCollective/html#321]
Current branch here is 5.4, but the documentation on laravelcollective.com stops at 5.3: https://laravelcollective.com/docs/5.3/html 

What should someone (with a Laravel 5.4 project) looking into this project for the first time start with?

**Comment by mlantz** [comment]
I'm working on it :)

**Comment by mlantz** [comment]
There were no major changes between 5.3 and 5.4 it was mainly a Laravel version update

**Comment by piotrowski** [comment]
So if I install 5.4 I should be fine with the 5.3 docs?
Or better stay with 5.3 until the new docs are out?

(Really just asking, not pushing or whining)

**Comment by mlantz** [comment]
For any Laravel project follow the versions :) for a 5.4 project you want 5.4 html, and the docs will still be relevant from 5.3 and the new docs should be released in the next day or so.

**Comment by piotrowski** [comment]
Thanks.
