### ISSUE TITLE
Fails to get values from model when ConvertEmptyStringsToNull middleware is active

### ISSUE THREAD

**Issue by aygee** [LaravelCollective/html#325]
Fix in #307 breaks getting values from model when the form is new.

It needs to know whether the form is dirty, ie: is it a new form or has it come back from a validation error.

**Comment by mlantz** [comment]
Do you think its valid enough to assume if the error bag has content then its a return of the form?

**Comment by aygee** [comment]
I was thinking to check if oldInputIsEmpty() to determine whether it's a return of the form. But mocking that is a pita because will need to make a lot of changes in almost every test that is using a session.

I think error bag is a safe alternative.

**Comment by aygee** [comment]
@mlantz Thanks for the fix, confirming that the issue is fixed.
