### ISSUE TITLE
Value attribute is missing for input text, email etc

### ISSUE THREAD

**Issue by dinajpuri** [LaravelCollective/html#327]
Hello,
I'm having a strange issue with Laravel 5.4. When value is set null, the value attribute does not print. This happens in model binding 
my code
`{!! Form::text('title', null, [ 'class' => 'form-control' ]) !!}`

what it gives
![value](https://cloud.githubusercontent.com/assets/5769361/26051397/de80740e-3983-11e7-806a-ea635cde07e3.JPG)

Pls help me solve this peculiar issue.
Regards

**Comment by ericvanjohnson** [comment]
So if the value is set to null you would like to have a behavior that returns and empty string?

Just curious, is there some reason you don't want to use the following to achieve this;
`{!! Form::text('title', '', [ 'class' => 'form-control' ]) !!}`

**Comment by mlantz** [comment]
There were a couple issues with a recent release that may have caused the model value to not be displayed but these have been resolved and the release is going out today.
