### ISSUE TITLE
Problem scaping a Link

### ISSUE THREAD

**Issue by juanmiguel431** [LaravelCollective/html#328]
Hello guys,

Im traying to do this in Laravel 5.1 with Laravel Collective 5.1
`{!! link_to('#', 'Some text <span class="caret"></span>') !!}`

But, the title it had been scaped. Looks the result:
<a href="#">Some Text &lt;span class="caret"&gt;&lt;/span&gt;</a>

What can I do to solve this, please?

**Comment by ericvanjohnson** [comment]
If you want to wrap your link in a span like you are showing, I think what you are going to need to do is something like 
```
<span class="caret">{!! link_to('#', 'Some text') !!}</span>
```
Otherwise, you can add the class as part of the link using the following example 
```{!! link_to('#', 'Some text', ['class' => 'caret']) !!}```

**Comment by juanmiguel431** [comment]
I have some code like this:

```
{!! link_to_html('#', 'Juan Miguel <span class="caret"></span>',
 [
    'class' => 'dropdown-toggle',
    'data-toggle' => 'dropdown',
    'role' => 'button',
    'aria-expanded' => 'false'
 ]) !!}
```

I had to create my own function as a helper:

```
if (!function_exists('link_to_html')) {
    /**
     * Generate a HTML link.
     *
     * @param string $url
     * @param string $html
     * @param array  $attributes
     * @param bool   $secure
     *
     * @return string
     */
    function link_to_html($url, $html = null, $attributes = [], $secure = null)
    {
        //        return app('html')->link($url, $html, $attributes, $secure);
        //Se requiere para que genere una url sin escapar
        return '<a href="'.$url.'"'.app('html')->attributes($attributes).'>'.$html.'</a>';
    }
}
```
I think would be helpful Laravel Collective do it nativaly

**Comment by juanmiguel431** [comment]
I missed show you how would be the output:

`<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Juan Miguel <span class="caret"></span></a>`
