### ISSUE TITLE
5.4.2 breaks load of Blade directives for other packages

### ISSUE THREAD

**Issue by FrittenKeeZ** [LaravelCollective/html#330]
As of version 5.4.2 (commit https://github.com/LaravelCollective/html/commit/e9d7084769887cc641d71a76c356958880cee1e0) Blade directives from other packages loaded through `$this->app->afterResolving('blade.compiler', ... )` are nuked, thus only directives from this package persist.

You can easily replicate this problem by installing spatie/laravel-permissions package and see that their directives, like @ role, doesn't exist when fetching a list of directives using `Blade::getCustomDirectives()`.

The fix is to change how directives are registered from `Blade::directive( ... )` to `$this->app->afterResolving('blade.compiler', ... )`.

I'll submit a PR as soon as possible.

**Comment by mlantz** [comment]
👍  will fix
