### ISSUE TITLE
Call to a member function count() on null in /html/src/FormBuilder.php on line 1107

### ISSUE THREAD

**Issue by subakarank** [LaravelCollective/html#336]
`if ($hasNullMiddleware && is_null($this->old($name)) && $this->view->shared('errors')->count() > 0) {
                return null;
            }`
This line got error..
Call to a member function count() on null in /html/src/FormBuilder.php on line 1107

** Change to **
`if ($hasNullMiddleware && is_null($this->old($name)) && $this->view->shared('errors') && $this->view->shared('errors')->count() > 0) {
                return null;
            }`

Then no error

**Comment by trevorgehman** [comment]
Also seeing this issue
