### ISSUE TITLE
_token empty value in hidden input

### ISSUE THREAD

**Issue by mochalovserge** [LaravelCollective/html#339]
I'd updated version v5.4.5 from v5.4.1:
And I have the trouble with _token value:
`{{ Form::open(...) }}`
output html: 
`<form method="POST" action="/login" accept-charset="UTF-8"><input name="_token" type="hidden">`

**Comment by Rudonator** [comment]
I have the same problem with my project.

**Comment by DigicreateJens** [comment]
I'm having the same issue. Client couldn't log in anymore because the token field was empty.
Temporarily fixed this by manually adding `{{ csrf_field() }}` at the start of the form while waiting for a definite fix.

**Comment by nmkr** [comment]
+1 after update forms are breaking

**Comment by cojocaru3** [comment]
+1, reverted to 5.4.3 and will keep it until fix is confirmed

**Comment by mochalovserge** [comment]
well :-) 
simple way i think
first -- edit your composer.json, write to `"laravelcollective/html" : " v5.4.1"` 
second -- exec `$composer install`

**Comment by danielverissimo** [comment]
Same issue here
