### ISSUE TITLE
v5.4.7 throws "Call to undefined method Illuminate\Session\Store::getToken()"

### ISSUE THREAD

**Issue by matthew-muscat** [LaravelCollective/html#342]
Commit https://github.com/LaravelCollective/html/commit/37672ebf2fd54a5f8334b4c2d9c4654670efb070 (part of release v5.4.7) appears to have caused the following error to occur when attempting to use LaravelCollective/Html on Laravel 5.4

Laravel 5.3 appears to support calls to "getToken", however Laravel 5.4 does not has this function defined or available.

https://github.com/laravel/framework/blob/5.4/src/Illuminate/Session/Store.php#L588
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Session/Store.php#L678

**Comment by lazosweb** [comment]
Just change $app['session.store']->getToken() to $app['session.store']->token() for the time being.
