### ISSUE TITLE
problem updating 5.1.9 to 5.1.10

### ISSUE THREAD

**Issue by carlituxman** [LaravelCollective/html#346]
After updating to 5.1.10 from 5.1.9 y have problems with multiselect if array id is a string from integer array:

for example
$config['parameter1'] = [1=>'opt1',2=>'opt2']

in 5.1.9 works with in multiselect with '1' (string) value, but with 5.1.10 not working

**Comment by mlantz** [comment]
Will review

**Comment by dbpolito** [comment]
I'm also seeing this problem on latest `5.4`... this is basically related to https://github.com/LaravelCollective/html/blob/5.4/src/FormBuilder.php#L763 `in_array` `strict`

**Comment by tshafer** [comment]
We accept pull requests.
