### ISSUE TITLE
problem with placeholder attribute in select method

### ISSUE THREAD

**Issue by haiph95** [LaravelCollective/html#347]
can u revert code from 
```php
protected function placeholderOption($display, $selected)
{
        $selected = $this->getSelectedValue(null, $selected);

        $options = [
            'selected' => $selected,
            'disabled' => 'disabled',
            'hidden' => 'hidden',
            'value' => ''
        ];

        return $this->toHtmlString('<option' . $this->html->attributes($options) . '>' . e($display) . '</option>');
}
```
to
```php
protected function placeholderOption($display, $selected)
{
        $selected = $this->getSelectedValue(null, $selected);

        $options = compact('selected');
        $options['value'] = '';

        return $this->toHtmlString('<option' . $this->html->attributes($options) . '>' . $this->html->escapeAll($display) . '</option>');
}

```

**Comment by bradgenereux** [comment]
+1 for reverting this. I think it's bad UI as the user has no way to "undo" an action. I'm thinking of situations where the placeholder says something like "View All", or "Optional". Maybe this behaviour could be an option like `['hidePlaceholder' => true]`.

**Comment by oscarmorrison** [comment]
+1

**Comment by Dagiral** [comment]
+1

**Comment by yaykyle** [comment]
Ah yeah that is certainly a problem in that case! What if it only used the new behavior when the field is required? Would that work? @bradgenereux's idea is nice and simple, too.

**Comment by ilyadrv** [comment]
It screws up the whole app. Had to rollback on 5.4.6 version.
If still not possible to get back the previous placeholder behaviour, can you please add something like 'defaultOption' or whatever.

**Comment by thunberg** [comment]
This is a breaking change that additionally goes against the docs for drop-downs:

Generating a Drop-Down List With an Empty Placeholder
This will create an <option> element with no value as the very first option of your drop-down.
echo Form::select('size', ['L' => 'Large', 'S' => 'Small'], null, ['placeholder' => 'Pick a size...'

That's what the docs say, but now nothing shows up in Chrome so it's effectively dead weight.

In the interim, for anyone reading this that wants an easy temporary fix that replicates the previous behavior:

Before:

```php

{!! Form::select('batches[]', $batches, null, ['placeholder' => 'Select batch', 'class' => 'form-control']) !!}

```

Now:

```php

{!! Form::select('batches[]', [NULL => 'Select batch'] + $batches, null, ['class' => 'form-control']) !!}

```

**Comment by oscarmorrison** [comment]
For anyone interested I opened a PR to revert the behavior. Can just patch your version for the time being https://github.com/LaravelCollective/html/pull/358
