### ISSUE TITLE
Form input arrays not working.

### ISSUE THREAD

**Issue by nat-mystudiosessions** [LaravelCollective/html#348]
I have an input array: `{{Form::hidden('position_ids[]', $position_id)}}`

When I submit, I get an error:
```
ErrorException in C:\laragon\www\mystudiosessions\vendor\laravel\framework\src\Illuminate\Support\helpers.php line 533:
htmlspecialchars() expects parameter 1 to be string, array given
```
When I change it to `<input type="hidden" name="position_ids[]" value="{{$position_id}}"/>` it works fine.

Any ideas?

**Comment by decadence** [comment]
https://github.com/LaravelCollective/html/issues/122

**Comment by DarkCobalt** [comment]
+1

**Comment by decadence** [comment]
You should close it since it's duplicate of another issue which is resolved.

**Comment by DarkCobalt** [comment]
This is not resolve my problem, because i want create array without static index. Actually i must return to previous version of package.

**Comment by nat-mystudiosessions** [comment]
Thanks @decadence
