### ISSUE TITLE
Form::text Error.

### ISSUE THREAD

**Issue by ThunderBirdsX3** [LaravelCollective/html#356]
I think this error come with lasted release because of in first it can work.

I got `htmlspecialchars() expects parameter 1 to be string, array given`

From this code.
```
<?=Form::text('data_id[]', $_GET['data_id'][0] ?? NULL, ['class'=>'form-control', 'style'=>'padding:0 !important;text-align:center;'])?>
```
It will error when have data from `?data_id[]=xxxx` in url. No matter I did change `$_GET['data_id'][0] ?? NULL` to `NULL` or `''`.

But. yes but, I change input name to some thing is not `data_id` like `data_ids[]`, `data_idx[]`, `ss`, `data_i` or ***`data_id[0]`*** It will not got an error.

WTF is that.

This is example code.
```
{!! Form::open(['method' => 'GET', 'class' => 'form-horizontal']) !!}
  <div class="form-group{{ $errors->has('test') ? ' has-error' : '' }}">
    {!! Form::label('test', 'Input', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
      {!! Form::text('test[]', $GET['test'] ?? NULL, ['class' => 'form-control', 'required' => 'required']) !!}
      <small class="text-danger">{{ $errors->first('test') }}</small>
    </div>
  </div>

  <div class="btn-group pull-right">
    {!! Form::reset("Reset", ['class' => 'btn btn-warning']) !!}
    {!! Form::submit("Add", ['class' => 'btn btn-success']) !!}
  </div>
{!! Form::close() !!}

```

> Laravel Framework 5.4.24
> laravelcollective/html v5.4.8

**Comment by adam-boduch** [comment]
Same here. There is incompatibility between 5.3 and 5.4. Take a look at this code:

```
{!! Form::text('foo', 'test') !!}
```

I expect that input field `foo` has value `test` (always!).

Let's just say I make a request to: `/homepage?foo=wtf`. 
Expected result:

```html
<input name="foo" type="text" value="test">
```

Version 5.4:

```html
<input name="foo" type="text" value="132">
```

**Comment by tshafer** [comment]
We accept pull requests.
