### ISSUE TITLE
Multiple (dynamic) form fields - old input why not an array!?

### ISSUE THREAD

**Issue by matedon** [LaravelCollective/html#359]
Hi!

I have a dynamic form, like this:
https://codepen.io/matedon/pen/BZQymW

There are more input fields with the same name but with square bracket:
```
<input name="apartments[][price]">
<input name="apartments[][rooms]">
<input name="apartments[][price]">
<input name="apartments[][rooms]">
```
The output and the old() value should be that:
```
{
  "apartments": [
    {
      "price": "23000",
      "rooms": "12"
    },
    {
      "price": "42000",
      "rooms": "32"
    }
  ]
}
```
But there is an issue and I got this:
```
@php(dump(Form::old('apartments')))
array:1 [▼
  "price" => "23000"
]
```
I also tried Laravel's "native"  solution which is wrong too:
```
@php(dump(session()->getOldInput('apartments')))
array:4 [▼
  0 => array:1 [▼
    "price" => "23000"
  ]
  1 => array:1 [▼
    "rooms" => "12"
  ]
  2 => array:1 [▼
    "price" => "42000"
  ]
  3 => array:1 [▼
    "rooms" => "32"
  ]
]
```
What is the solution could be?
Thank you!

**Comment by matedon** [comment]
When I add numbers to squared inputs, all this works with session.
```
<input name="apartments[0][price]">
<input name="apartments[0][rooms]">
<input name="apartments[1][price]">
<input name="apartments[1][rooms]">
```
But there would no need numbers.

**Comment by alyjee** [comment]
I'm sailing the same ship, and I was hoping there's more laravel-ish way to re-populate dynamic inputs with old values upon validation errors?
