### ISSUE TITLE
Upgrade issues from 3.5.1 to 3.5.2

### ISSUE THREAD

**Issue by xitegr** [LaravelCollective/html#363]
My form was working fine in v.3.5.1,

After upgrading to 3.5.2 some fields in my form (not all don't get values). My code below.

`{!! Form::open(array('route' => 'pos.extras', 'class' => 'hidden', 'id' => 'form', 'method' => 'post')) !!}
			{!! Form::hidden('service_id', '123') !!}
			{!! Form::hidden('pickup_parking', 'test') !!}
{!! Form::close() !!}`

service_id doesn't get value, but pickup_parking does. (v.3.5.1 everything works fine). If i use pure html Form and input tags everything works fine also.

I also should mention that when i change the name of sevice_id to service_id2 for example, the field gets value. 

Any clues?

Thanks

**Comment by tshafer** [comment]
We don't have a version 3.
