### ISSUE TITLE
Support for laravel 5.5

### ISSUE THREAD

**Issue by JaxTerra** [LaravelCollective/html#364]
Hi

Just wondering if there is a release that is compatible Laravel 5.5 yet? Im aware that its still in dev, but as Laracasts already released the whats new in 5.5 i thought maybe there is a compatible collective release also?

**Comment by decadence** [comment]
There is no 5.5 branch so answer is "Not yet" :)

**Comment by decadence** [comment]
https://github.com/LaravelCollective/html/pull/361

**Comment by beitsafejax** [comment]
Thankyou @decadence!

**Comment by bobbybouwmann** [comment]
@mlantz Can you create the 5.5 branch? We are currently waiting for this!

**Comment by hohl** [comment]
Laravel 5.5 got released. Would be a great idea to provide an update with Laravel 5.5 support.

**Comment by plazari15** [comment]
I'm trying to use this with Laravel 5.5 but nothing available until now!

**Comment by thelfensdrfer** [comment]
Vote for it or create a pull request @plazari15!

**Comment by yuran93** [comment]
Well. Don't know this is the best practice but i put laravelcollective in to the vendor folder and updated composer.json

`
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/",
            **"Collective\\": "vendor/laravelcollective"**
        },`

**Comment by erayaydin** [comment]
I think this issue shouldn't be closed. So everyone can have notification when Laravel Collective released 5.5 branch :+1:

**Comment by hohl** [comment]
@erayaydin: There is already an release.

**Comment by ciscolybon** [comment]
how to do in this case figure

**Comment by ciscolybon** [comment]
that she is the version?

**Comment by leogouveia** [comment]
@ciscolybon I think it's already released. Check out [packagist](https://packagist.org/packages/laravelcollective/html). Maybe someone should update the official site.
