### ISSUE TITLE
Validation and multiple select

### ISSUE THREAD

**Issue by perskinet** [LaravelCollective/html#366]
Regarding to this issue https://github.com/LaravelCollective/html/issues/189 I still have the problem with getting values for multiple select after validation - there are no values in the form. 

Hello I've made some investigation and the problem is in method in laravelcollective/html/src/FormBuilder.php:

` protected function getSelectedValue($value, $selected)`
`    {`
`        if (is_array($selected)) {`
`            return in_array($value, $selected, true) ? 'selected' : null;`
`        } elseif ($selected instanceof Collection) {`
`            return $selected->contains($value) ? 'selected' : null;`
`        }`
` `
`        return ((string) $value == (string) $selected) ? 'selected' : null;`
`    } `

Especially:

` in_array($value, $selected, true) `

**If you turn off strict mode at in_array function everything works well, now the question is how to put right type of value to this method.** 

I am running code on php 7 if that helps.

`protected function getSelectedValue($value, $selected)`
`    {`
` `
`        echo gettype($value);`
`        echo gettype($selected[0]);`

Gives me integer and string

At $value is value from foreach for each select option, and at selected array there are selected values.

Maybe I am doing something wrong, any ideas?

**Comment by vvendin** [comment]
@perskinet, this is because of the commit https://github.com/LaravelCollective/html/commit/3dcf2185a1a329e6c19bb1eaa89de9cf91572145

**Comment by Vendin** [comment]
#368

**Comment by Vendin** [comment]
#368

**Comment by perskinet** [comment]
Thanks for your action, so it will be fixed with your pull request? :)

**Comment by Vendin** [comment]
In my opinion, yes.

**Comment by piperone** [comment]
Why is strict-mode for in_array necessary?

**Comment by jakjr** [comment]
This is a bug. Why is closed??
