### ISSUE TITLE
Parameter selected not working in select

### ISSUE THREAD

**Issue by projct1** [LaravelCollective/html#369]
I have url `/path?month=4`
```php
$options = [
  "" => "-"
  1 => "Январь",
  2 => "Февраль",
  3 => "Март",
  4 => "Апрель"
];

{!! Form::select('month', $options, '']) !!}
```
I want select first option (-), but whatever i pass in third parameter (false, '', '-', 'omg'), selected will 4 (as in url)

**Comment by andres9366ha** [comment]
Sorry, Could you be more explicit with your question? I want help you but I don't understand what you want...

**Comment by rorc** [comment]
@andres9366ha Ok 😄
1. My current `$_GET` parameter is `['month' => 4]`.
2. I want to set active first parameter on my html select field (`$options['']`).
3. For this goal i pass `''` as third parameter in `{{ Form::select }}` method.
4. But whatever i pass in third parameter (false, '', '-', 'omg', etc), selected value will always equal 4.

**Comment by andres9366ha** [comment]
Can you write exactly how do you want to see your select?

**Comment by rorc** [comment]
I want to see http://joxi.ru/KAgM6gdcgX0NJm, but i see http://joxi.ru/E2pkOEXcBa04Dm independent of third parameter.

**Comment by diego0037** [comment]
try this 
{!! Form::select('opts', array('opt1' =>'Option1', 
                    'opt2' => 'Option2', 'opt3' => 'Option3'), null, array('placeholder' => '-')) !!}

**Comment by rorc** [comment]
@diego0037 😒
You are totally not understand...

**Comment by diego0037** [comment]
{!! Form::select('month', $options, '']) !!}
there is an error in the line 
``

**Comment by decadence** [comment]
It's because you have Request with month variable.

Docs:
So, the priority looks like this:
Session Flash Data (Old Input)
Data From Current Request (via  Request::input method)
Explicitly Passed Value
Model Attribute Data

**Comment by rorc** [comment]
@decadence 
> But whatever i pass in third parameter (false, '', '-', 'omg', etc), selected value will always equal 4.

**Comment by decadence** [comment]
So what?
Request is on 2 place, value on the 3.

**Comment by rorc** [comment]
Its wrong priority?
I cant set selected item manually? Lol?

**Comment by decadence** [comment]
Maybe but you can rename input or Request variable for now.

**Comment by decadence** [comment]
https://github.com/LaravelCollective/html/pull/376
