### ISSUE TITLE
Facade Conflict

### ISSUE THREAD

**Issue by PatrickRose** [LaravelCollective/html#37]
Hi there,

I maintain Bootstrapper and someone's recently raised patricktalmadge/bootstrapper#279 which leads to our code conflicting since we typehint the Illuminate version of the components. We're still supporting Laravel 4 for a few more months (probably waiting until Twitter Bootstrap v4.0.0 and/or our cross framework project is completed).

Would it be possible for you to add an extra binding (say, `collective::html`) so that we can use the Laravel 5 version in the meantime? I'm happy to do some real work on compatibility fixing our code if there are issues in `illuminate/html` that are resolved in this fork that I'm unaware of but I'd like to avoid it if I can

**Comment by tshafer** [comment]
Can you use the 5.0 branch?

https://github.com/LaravelCollective/html/tree/5.0

**Comment by tshafer** [comment]
Closed due to inactivity.
