### ISSUE TITLE
Accessing model instance inside component

### ISSUE THREAD

**Issue by scs75** [LaravelCollective/html#370]
I build a custom Form input compent as the docs suggested:
https://laravelcollective.com/docs/5.4/html#custom-components

How can I acces the model instance of the form in the components blade template?
I see the Form facade has a setModel method, so it would be reasonable to implement a getModel() as well. 
Form::getModel()

**Comment by queryluke** [comment]
@scs75 

I was trying to do something similar and found the [`Form::getValueAttribute($name)`](https://github.com/LaravelCollective/html/blob/5.4/src/FormBuilder.php#L1137) method. It doesn't get you the entire model, but you can get values from the model by passing the model's attribute name as the `$name` param.

Hope that helps!

**Comment by tshafer** [comment]
We accept pull requests.
