### ISSUE TITLE
a Form isn't reset after successful submitting

### ISSUE THREAD

**Issue by Razip** [LaravelCollective/html#375]
I am using this [plugin](https://github.com/dwightwatson/bootstrap-form) which uses Laravel Forms, so I think ask my question here.

I have a route that handles both GET and POST requests and it is linked to the same action (a controller's method). There, I display my Blade view with a form which gets an empty model as an argument.

The issue is that no matter was the last submitting of a form successful or not, previous form's input values remain until I reload the page.

I realize that this is helpful to keep the values after submit fail, but it is not appropriate to keep the values all the time, or specifically when the submitting was successful in my case..

I've learned that the data from Request is always more prior than the one from the model by looking at this code:

```
    public function getValueAttribute($name, $value = null)
    {
        if (is_null($name)) {
            return $value;
        }

        $old = $this->old($name);


        if (! is_null($old) && $name != '_method') {
            return $old;
        }

        if (function_exists('app')) {
            $hasNullMiddleware = app("Illuminate\Contracts\Http\Kernel")
                ->hasMiddleware(ConvertEmptyStringsToNull::class);

            if ($hasNullMiddleware
                && is_null($old)
                && is_null($value)
                && !is_null($this->view->shared('errors'))
                && count($this->view->shared('errors')) > 0
            ) {
                return null;
            }
        }

        $request = $this->request($name);

// it uses request's data first

        if (!is_null($request)) {
            return $request;
        }

        if (! is_null($value)) {
            return $value;
        }

        if (isset($this->model)) {
            return $this->getModelValueAttribute($name);
        }
    }
```

So my question is: is there any chance I can force using the model's data instead of Request's when setting values for a form so empty values are set?

P.S. [here ](https://github.com/Razip/LaravelGuestBook)is all of my project's code.

**Comment by decadence** [comment]
https://github.com/LaravelCollective/html/pull/376

**Comment by nasirouwagana** [comment]
I still have a same issue with Laravel 5.5. Please How to fix it ?

**Comment by Razip** [comment]
Start using Yii.

**Comment by tshafer** [comment]
Is this still an issue?

**Comment by tshafer** [comment]
Closed due to inactivity.
