### ISSUE TITLE
Why model-form relations are so?

### ISSUE THREAD

**Issue by Razip** [LaravelCollective/html#381]
Related: https://github.com/LaravelCollective/html/issues/375

```
        $request = $this->request($name);

        if (!is_null($request)) {
            return $request;
        }

        if (! is_null($value)) {
            return $value;
        }

        if (isset($this->model)) {
            return $this->getModelValueAttribute($name);
        }
```

Whenever you've just submitted something, no matter what model's data you give to the form, it'll always fill the inputs with the data from the Request and that means it is totally hardcored!

Why does it have to be so?

Take a look at how it is done in Yii2 - you give a model to a form and it displays exactly what you give and nothing decides where to take the data from but you. Take a look:

```
    public function actionCustom() {
        $model = new Custom();

        // sending the Request's data to model
        $model->load(\Yii::$app->request->post());

        if ($model->validate()) {
            // emptying the model's data
            $model = new Custom();
        } else {

        }

        return $this->render('custom', [
            'model' => $model
        ]);
    }
```

You're free to do what you what in the example, is that good?

**Comment by decadence** [comment]
You don't need to create several similar issues.
PR that make fill from `Request` optional is already done.
So just wait because this repo maintainers don't peek here often.

**Comment by decadence** [comment]
https://github.com/LaravelCollective/html/pull/376

**Comment by Razip** [comment]
decadence, I don't like the idea that the form builder decides which data to use at all.

**Comment by Razip** [comment]
I think it would make more sense if we didn't have a behavior that ever needs to be prevented, but that's just my point.
