### ISSUE TITLE
Form::select() unable to set option attributes within option groups

### ISSUE THREAD

**Issue by illmatik007** [LaravelCollective/html#382]
Form::select() doesn't allow me to set option attributes for options within an option group.

**Comment by biscuide** [comment]
Fix patch
[FormBuilder.zip](https://github.com/LaravelCollective/html/files/1294218/FormBuilder.zip)

**Comment by illmatik007** [comment]
This fix resolves the issue, thanks, please create pull request.

**Comment by djh101** [comment]
See my PR #416.
