### ISSUE TITLE
Insert method field automatically

### ISSUE THREAD

**Issue by alvaromat** [LaravelCollective/html#397]
It would be cool that when using the Form::model() method with the route option, the method was automatically inserted depending on the route.
Now I do the following:
In the controller:
`'route' => ['users.questions.update', $question]`
In the view:

```
{!! Form::model($question, ['route' => $route]) !!}


@if(str_contains($route[0], 'update'))
    {{ method_field('PUT') }}
@endif
```

As the route is already defined the mehtod could be guessed and the last three lines could be omitted. 
The CSRF token is automatically included so I think that this is feasible.

**Comment by koslo** [comment]
No, this should be flexible in the future.
I think the intention is that you use for creation the `open` method and for edit the `model` method. If you want to prefill your inputs with the `model` function you can add to the option array a `method` which can handle your problem.
