### ISSUE TITLE
Form::number() does not exist.

### ISSUE THREAD

**Issue by sebdesign** [LaravelCollective/html#4]
Hi,

I'm getting the following exception when I try to use the `Form::number()` method:

```php
exception 'BadMethodCallException' with message 'Method number does not exist.'
in vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:87
```

Although the documentation [mentions](https://github.com/LaravelCollective/html/blob/5.0/readme.md#number) this method, I couldn't find the implementation in the source.

**Comment by adamgoose** [comment]
Yeah, Taylor removed this method for some reason, but never updated the docs. When I add the "number" method back for you, it will just be an alias for `Form::input('number'...` So you can just use that in the meantime. Thanks for letting us know!

**Comment by sebdesign** [comment]
Sure,

I actually use the `Form::input('number', ...)` method, I just thought the number method should be implemented, or be removed from the documentation, so I opened this issue. Thanks!

**Comment by driesvints** [comment]
Sent in a PR here: #8
