### ISSUE TITLE
Edit with get parameters

### ISSUE THREAD

**Issue by eastwbbk** [LaravelCollective/html#404]
Controller:
load entity from database for editing

Url:
{SITE_ROOT}/dashboard/projects/7/edit

view code:
{{ Form::text('name', $project->name(), ['id' => 'name', 'class' => 'form-control']) }}

As result a see text input with project name, for example "My New Project" and it's ok, but if I add GET param with same name it rewriting project name. For example:

Url:
{SITE_ROOT}/dashboard/projects/7/edit?name=supertest

As result I see not "My New Project", I see "supertest". And this repeating for any input and select in form.

**Comment by decadence** [comment]
https://github.com/LaravelCollective/html/pull/376

**Comment by djh101** [comment]
Seems that #376 is for 5.4 and hasn't made its way to 5.5 yet.

**Comment by tshafer** [comment]
Feel free to resubmit to master.
