### ISSUE TITLE
Opening A Form - Method Incorrect

### ISSUE THREAD

**Issue by Vulfoliac** [LaravelCollective/html#406]
Once I updated to the v.5.3.2 the getValueAttribute always returns GET when this function used to return the method that was specified when opening a form  

`Form::Model($model, ['url'=>'foo','method'='PUT'])`

Is this a potential bug? or is there a change? for now I'm going to move to an older version.

**Comment by StefanPrintezis** [comment]
It still returns the output of the open() function, beign a form element. It might be the syntax error you pasted thought.` 'method'='PUT' ` `=>`
