### ISSUE TITLE
How do I add a class to a checkbox?

### ISSUE THREAD

**Issue by peterbrinck** [LaravelCollective/html#407]
Hi!

With all the other input fileds, you can add a class.
Is there any way to do it with checkboxes and radio inputs?

**Comment by bradgenereux** [comment]
You can add an array of attributes just like any other input, but it's the 4th parameter for radios and checkboxes. The 3rd parameter needs to be defined as true/false (checked/unchecked).
```php
Form::checkbox('name', 'value', false, ['class' => 'my-class']);
```
