### ISSUE TITLE
Support for L5.5

### ISSUE THREAD

**Issue by Daniesy** [LaravelCollective/html#410]
All the topics handling this issue have been closed a while ago, but there are no updates.

**Comment by Braunson** [comment]
There's already a PR for this ready to go https://github.com/LaravelCollective/html/pull/409

**Comment by robertnicjoo** [comment]
@braunson with that pr i end up the error I've mentioned in my topic.

**Comment by andersondeoliveiramachado** [comment]
What would be the correct procedure for the installation?

suport@devel:/var/www/cli.wifigratis.com.br# composer require "laravelcollective/html":"^5.5.x-dev"
Do not run Composer as root/super user! See https://getcomposer.org/root for details
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package laravelcollective/html ^5.5.x-dev exists as laravelcollective/html[5.0.x-dev, 5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, dev-master, 5.5.x-dev, v5.0.0, v5.0.1, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.1.0, v5.1.1, v5.1.10, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2, v5.2.1, v5.2.2, v5.2.3, v5.2.4, v5.2.5, v5.2.6, v5.3.0, v5.3.1, v5.3.2, v5.4, v5.4.1, v5.4.2, v5.4.3, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8] but these are rejected by your constraint.


Installation failed, reverting ./composer.json to its original content.

**Comment by cmizzi** [comment]
The PR is not merged at all. You have to use the fork and `dev-master` version

**Comment by gofish543** [comment]
If only dev-master worked xD. Dev master requires the use of 5.5.x-dev, but most packages out there have removed this and made it 5.5.x. This is one of the few packages that doesn't do this. This prevents us developers from using this package until they click the merge button.

**Comment by cmizzi** [comment]
Not if you're using my PR fork, but I understand why you used `5.5.x-dev`, but it's not necessary anymore :)

**Comment by bradgenereux** [comment]
@cmizzi How do you use your PR fork?

**Comment by cmizzi** [comment]
See #411

**Comment by BAKTETE** [comment]
just upgraded my app from 5.4 to 5.5 but laravelcollective/html package is holding me from testing my app please support for laravel 5.5
