### ISSUE TITLE
can't install laravelcollective on laravel 5.5

### ISSUE THREAD

**Issue by robertnicjoo** [LaravelCollective/html#411]
when try to install in this way
"laravelcollective/html": "5.5.*"
get this error
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package laravelcollective/html ^5.5.0 is satisfiable by laravelcollective/html[5.5.x-dev] but these conflict with your requirements or minimum-stability.
```

**Comment by Braunson** [comment]
Duplicate https://github.com/LaravelCollective/html/issues/410

**Comment by robertnicjoo** [comment]
@braunson Used the pr and the error above was the result of that.

**Comment by cmizzi** [comment]
Have you updated your `composer.json` like that with a `"laravelcollective/html": "dev-master"` until the PR is merged ?

```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/cmizzi/html"
        },
    ]
```

**Comment by Hussam3bd** [comment]
@robertnicjoo  I have the same issue, did you solve it?

**Comment by lloricode** [comment]
same as mine

**Comment by cmizzi** [comment]
I have no problem using the temporary fork. Wait until PR is merged or use fork

**Comment by aios** [comment]
same...

**Comment by robertnicjoo** [comment]
@Hussam3bd No I didn't solve it I just removed  ` "laravelcollective/html": "^5.5.0",`  from my composer.jason also it's codes from `app.php` and upgraded my laravel.

It's better to just wait for merged PR.

**Comment by FaithPatrick** [comment]
Just wait for upgrading.

**Comment by hakimihamdan88** [comment]
fml

**Comment by AnowarCST** [comment]
eagerly waiting for update

**Comment by yajra** [comment]
Related issue: https://github.com/yajra/datatables/issues/1

**Comment by robertnicjoo** [comment]
any update on new version?

**Comment by lloricode** [comment]
This issue already solved by this merged [PR](https://github.com/LaravelCollective/html/pull/409).
:)

**Comment by robertnicjoo** [comment]
Intallation for laravel 5.5 `composer require laravelcollective/html`

**Comment by chisumo2016** [comment]
Hi Guys 

I was able to resolve the problem by adding    "firebase/php-jwt": "~3.0|~4.0|~5.0", in a  composer.json 

Then composer update --Works well on me

**Comment by khaiyam** [comment]
Go to - > https://laravelcollective.com/docs/master/html  
or
Copy this to you composer.json file     "laravelcollective/html":"^5.4.0"
Go to your command line and update your composer like  "  composer update "

and image added with this post you can follow it  :)
![laravel](https://user-images.githubusercontent.com/26525085/33511807-cf630f60-d74c-11e7-8748-98f34ead25dc.png)

**Comment by manfredjb** [comment]
@khaiyam , thank you!

**Comment by mahbubkhan88** [comment]
open your composer and copy paste this link composer require "laravelcollective/html":"5.4.0". That means remove "^" symbol. It will install current version rather than installing the latest. Then, composer update

**Comment by vvmspace** [comment]
Update your Laravel to Laravel 5.7:
    "require": {
        "php": ">=7.1.3",
        "fideloper/proxy": "~4.0",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "~1.0",
    },

composer install
