### ISSUE TITLE
Support 5.5

### ISSUE THREAD

**Issue by goyote** [LaravelCollective/html#412]
Problem 1
    - Conclusion: remove laravel/framework v5.5.0
    - Conclusion: don't install laravel/framework v5.5.0

**Comment by teddywest32** [comment]
Duplicate of: https://github.com/LaravelCollective/html/issues/410

**Comment by cmizzi** [comment]
Please see #409, #410 and #411 :smiley:

**Comment by balping** [comment]
It's been released !

**Comment by robertnicjoo** [comment]
@balpin where is that released that I can't find it?

**Comment by balping** [comment]
@robertnicjoo 

https://github.com/LaravelCollective/html/releases

**Comment by robertnicjoo** [comment]
@balping and any idea how to install it? :-D

**Comment by balping** [comment]
composer require laravelcollective/html
