### ISSUE TITLE
Enhance documentation to describe all method arguments

### ISSUE THREAD

**Issue by kwebble** [LaravelCollective/html#413]
Looking at https://laravelcollective.com/docs/5.2/html, but also the current version I miss a list of all arguments on the methods. For example for `Form::open` it describes `route`, `action`, the option to pass arguments, `url` and `files`. What I did not find and was how to set `class` and `id`.

The same for `Form::file`. It describes a single argument, without information what it is. I needed to set the `accept` attribute on the input element.

I had to google for the answers, it would be useful and quicker to find them in the documentation.

This may be the wrong place for this question, but I could not find a better one.

**Comment by tshafer** [comment]
We do accept PRs. Ill be going through all the repos this weekend and cleaning them up.
