### ISSUE TITLE
Test in Laravel 5.1

### ISSUE THREAD

**Issue by gravitano** [LaravelCollective/html#42]
Hi,

We know Laravel 5.1 has not been released yet. But, is there way to install this package in laravel 5.1 (dev-develop version). Or can you create a new branch for Laravel 5.1?

**Comment by adamgoose** [comment]
I pushed updates to `composer.json` that adds the branch alias and minimum stability.

**Comment by adamgoose** [comment]
Can you let me know if this installs properly? Will close when you confirm.

**Comment by gravitano** [comment]
Tested well in version `5.1@dev`. Thanks!
