### ISSUE TITLE
Form::*: option-array does not work with v-model

### ISSUE THREAD

**Issue by jozeflambrecht** [LaravelCollective/html#422]
I am using LaravelCollective 5.5.x to create my forms. I would like to add the `v-model` attribute
Here is my example: 
`{!! Form::text('name', null, ['class' => 'form-control', 'v-model' => 'name']) !!}`

When I look to the rendered code, it does not put the v-model attribute in the input field. 
If I would change `v-model` to `vmodel`, it works. So I cannot use a '-'?
Someone had this before?

**Comment by jozeflambrecht** [comment]
Still have the same issue. Can someone confirm this?

**Comment by tshafer** [comment]
Why would use you need the functionality of this package if you are using vue?

**Comment by dennykuo** [comment]
Try to use 
`{!! Form::text('name', null, ['class' => 'form-control', "v\-model" => 'name']) !!}`
