### ISSUE TITLE
htmlentities() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by Kolesar** [LaravelCollective/html#426]
When we have array of input fields usually get error:
`htmlentities() expects parameter 1 to be string, array given`
`vendor/laravelcollective/html/src/HtmlBuilder.php line 459`

I added one new condition in `getValueAttribute` for fix this issue. Please review it and add official code.

```
        $request = $this->request($name);
        if (!is_null($request) && !is_array($request)) {
            return $request;
        }
```

https://github.com/LaravelCollective/html/blob/5.5/src/FormBuilder.php#L1162

**Comment by djh101** [comment]
Take a look at the _request_ and _old_ functions. Those should be almost identical. Copy the contents of _old_ to _request_ and replace _$this->session_ with _$this->request_ and your issue will be resolved.

**Comment by Kolesar** [comment]
Yea, but in both case it is workaround. I expect it will be resolved in next release :)

**Comment by djh101** [comment]
Wouldn't your solution be the workaround? Seems like it just skips over any request values if they're arrays instead of actually putting them into the HTML.

**Comment by tshafer** [comment]
Closed due to inactivity.
