### ISSUE TITLE
Can you tag a new version, please?

### ISSUE THREAD

**Issue by jbruni** [LaravelCollective/html#43]
I am using laravelcollective/html as a dependency (through composer.json), but applying newest tests (current tests/FormBuilderTests.php) - and one test fails to pass (testFormRepopulationWithMixOfArraysAndObjects).

Current implementation of FormBuilder::getModelValueAttribute fixes it, while implementation of latest tagged version (5.0.4) fails to pass.

Can you please add a new version tag (5.0.5) so I can have a tests-proof version using composer?

Thank you.

**Comment by tshafer** [comment]
https://github.com/LaravelCollective/html/tree/v5.0.5

**Comment by jbruni** [comment]
@tshafer - I thank you for the immediate positive response to my request.

But to my surprise composer did not upgrade laravelcollective/html... I removed vendors, composer.lock, the composer cache... nothing worked.

I realized the cause of it is unmet dependencies from composer.json:
https://github.com/LaravelCollective/html/commit/f1eddc7a7834854a3cb147a7601547394d345213

I apologize for my ignorance, but... I could not found any of these "5.1" versions in the referred repositories... (illuminate/http, and so on) ...so, I can't understand why the change above have been made to composer.json...

**Comment by jbruni** [comment]
So... this explains all: https://github.com/LaravelCollective/html/issues/42 

Laravel 5.1 LTS release is very near...

Then it seems it is better to **remove** this 5.0.5 tag, because it does not match the changes done since https://github.com/LaravelCollective/html/commit/745c10226d9a28798cbc5ddba2a3af868b342a3c... the last commit it could apply was https://github.com/LaravelCollective/html/commit/a0a763779d357d37fa05997c9f60fef8d6e0de62...

Either delete 5.0.5 tag and forget it, or maybe this last applicable commit could be merged to 5.0, and receive the final 5.0.5 tag (it contains bug fixes compared to 5.0.4)... From there onwards it is 5.1...

I'm sorry for generation this situation. Project management lessons for everybody...

Both this 5.0.5 tag couldn't be applied at current situation... and that alias + dependencies upgrade could be better thought of... (finish 5.0 branch, create a 5.1 branch)... I don't know.

**Comment by jbruni** [comment]
@adamgoose - just calling attention... due to my request now you have a 5.0 tag in a 5.1 code... I'm sorry, please accept my apologies.

**Comment by tshafer** [comment]
My bad, I forgot he did this. I will be removing this tag.
