### ISSUE TITLE
AJAX parameters override input and select values

### ISSUE THREAD

**Issue by lazosweb** [LaravelCollective/html#438]
When you have an Ajax call that passes the following parameters to a url for example:
course_name: "Web Development 2017"
course_hours: 100

If I want the AJAX call to return an HTML Form with similar input names as above (course_name, course_hours) but I will set different values to the inputs my values will be overridden by the AJAX call because on your FormBuilder at line 1161 you are checking if the name exist in the request first and not if the user already set a value for the input. I believe first you need to return if the user set a value, then the model and keep the request for last.

**Comment by tshafer** [comment]
We accept pull requests.
