### ISSUE TITLE
{!! and {{ clarification in docs

### ISSUE THREAD

**Issue by elb98rm** [LaravelCollective/html#440]
Bit of a pedantic issue, but:

The documentation seems to jump between recommending `{!!` and `{{` for the way to echo the content.

Is there a requirement for `{!!`?

* if so, the reason and locations for this should be specified
* if not, my understanding is that it's probably best practice to use `{{`

Might be worth working on for version 5.5

**Comment by tshafer** [comment]
We accept pull requests.
