### ISSUE TITLE
Cannot pass id field to route array in Form::model in laravel 5.4

### ISSUE THREAD

**Issue by AbdulRaheemGhani** [LaravelCollective/html#446]
- Laravel Version: 5.4
- PHP Version: 7.1
- Database Driver & Version: mysql

**Description:**

When I pass the model id field as second parameter to controller action in Form::model, it gives me the following error:

`Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR) Type error: Too few arguments to function App\Http\Controllers\DoctorsController::update(), 1 passed and exactly 2 expected`

This is my code:
`{!! Form::model($doctor, ['route' => ['doctors.update', $doctor->id]]) !!}`

Here is the route:
`Route::post('/doctors/update', 'DoctorsController@update')->name('doctors.update');`

This is the controller action:
`public function update(Request $request, $id) { $this->validate($request, [ 'name' => 'required|max:50', 'percentage' => 'required|digits_between:1,2' ]); $doctor = Doctor::find($id); $doctor->name = $request->name; $doctor->percentage = $request->percentage; $doctor->save(); return redirect('/doctors'); }`

Please Help me.

**Comment by peterchaula** [comment]
You did not specify the `id` parameter in the route. Your route declaration should look like this 
`Route::post('/doctors/{id}/update',`

**Comment by AbdulRaheemGhani** [comment]
Ohhhh! Exactly this was the problem and now it is solved completely.
Thanks @peterchaula
