### ISSUE TITLE
Open form with https url

### ISSUE THREAD

**Issue by sicaboy** [LaravelCollective/html#447]
Anyone can tell me how to open form with https url

**Comment by tshafer** [comment]
https://github.com/LaravelCollective/html/blob/2c5db92f662bf5dfb7b198265168599941e29de6/src/HtmlBuilder.php#L177

**Comment by Razoxane** [comment]
> https://github.com/LaravelCollective/html/blob/2c5db92f662bf5dfb7b198265168599941e29de6/src/HtmlBuilder.php#L177

@tshafer your comment doesn't solve @sicaboy's question.

The `Html::secureLink` method generates a full hyperlink, including the `<a>` tag, with the provided URL as the href and content of the element if nothing else is provided.

```php
Form::open([
   'url' => Html::secureLink('submit-url'),
])
```
results in
```html
<form method="POST" action="http://localhost/<a href="https://localhost/submit-url">https://localhost.submit-url</a>">
```

A better solution would be to use the `url()->secure($path)` helper or `URL::secure($path)` facade when passing the stub to the `Form::open` method:
```php
Form::open([
   'url' => url()->secure('submit-url'),
])
```

It will get the job done, but could lead to problems in a local or dev environment that isn't using https.
It also seems like a deficiency in the `Form::open` method signature, and how it handles the action attribute. 
I would have thought that it would "just work" with whatever protocol is currently in use, like the rest of the routing in Laravel? 

Tracing the logic where an secure option could be passed in:

`Form::open()` method passes the options it's given to `getAction()`. 
https://github.com/LaravelCollective/html/blob/bcc317d21a7e04eebcc81c4109fa84feaab63590/src/FormBuilder.php#L135-L145
Ok, nothing to worry about yet, something might happen further down...

`Form::getAction()` only passes the url argument to `getUrlAction()` :(
https://github.com/LaravelCollective/html/blob/bcc317d21a7e04eebcc81c4109fa84feaab63590/src/FormBuilder.php#L1155-L1163
This could be a good place to check if there is a `secure` argument in the options, and pass it as a second parameter to `getUrlAction()`!

The `getUrlAction()` method calls the url helper's `to()` method, but only passes the first two arguments, it's the third argument in the `to()` method signature that controls the HTTPS protocol being added :(
https://github.com/LaravelCollective/html/blob/bcc317d21a7e04eebcc81c4109fa84feaab63590/src/FormBuilder.php#L1185-L1192
Making this support https urls would involve adding another argument, then either populating the third argument in the `to()` call, or alternatively calling the `url()->secure()` method instead, to make it more visually obvious.

The `to()` method from the [Illuminate/Routing repo](https://github.com/illuminate/routing/blob/f126b157fa80b1b429cb824957d854bd2170bcaa/UrlGenerator.php#L181-L212):
```php
    /**
     * Generate an absolute URL to the given path.
     *
     * @param  string  $path
     * @param  mixed  $extra
     * @param  bool|null  $secure
     * @return string
     */
    public function to($path, $extra = [], $secure = null)
    {
        // First we will check if the URL is already a valid URL. If it is we will not
        // try to generate a new one but will simply return the URL as is, which is
        // convenient since developers do not always have to check if it's valid.
        if ($this->isValidUrl($path)) {
            return $path;
        }

        $tail = implode('/', array_map(
            'rawurlencode', (array) $this->formatParameters($extra))
        );

        // Once we have the scheme we will compile the "tail" by collapsing the values
        // into a single string delimited by slashes. This just makes it convenient
        // for passing the array of parameters to this URL as a list of segments.
        $root = $this->formatRoot($this->formatScheme($secure));

        [$path, $query] = $this->extractQueryString($path);

        return $this->format(
            $root, '/'.trim($path.'/'.$tail, '/')
        ).$query;
    }
```

I've not yet delved into how this could be modified to make it auto-detect the protocol, but I'll come back to it when I have more time.
