### ISSUE TITLE
[UnexpectedValueException] when installing with Windows PowerShell

### ISSUE THREAD

**Issue by houcem-h** [LaravelCollective/html#457]
When I execute this command to install LaravelCollective using PowerShell:
> [UnexpectedValueException]Could not parse version constraint :5.4.0: Invalid version string ":5.4.0"

**Comment by tshafer** [comment]
I don't believe thats valid. Try this

`"laravelcollective/html": "^5.5",`

**Comment by oranges13** [comment]
I am using Laravel 5.4, so I cannot use forms version 5.5.

The command as written in the installation: `composer require "laravelcollective/html":"^5.4.0"` fails when using Windows Powershell

Here is the error message

```
[UnexpectedValueException]
Could not parse version constraint :5.4: Invalid version string ":5.4"
```

**Comment by saqibarfeen** [comment]
It works , when written like this in windows:-
``composer require "laravelcollective/html ^5.4.0"``
