### ISSUE TITLE
how to use for laravel5.5

### ISSUE THREAD

**Issue by hcweb** [LaravelCollective/html#459]
I can not use laravel5.5 through composer installation

**Comment by tshafer** [comment]
Do you get an errors?

**Comment by tshafer** [comment]
Closed due to inactivity.

**Comment by hcweb** [comment]
I'm sorry, just see, now resolved, is my own composer error, thanks!

**Comment by hcweb** [comment]
I'm sorry, just see, now resolved, is my own composer error, thanks!
