### ISSUE TITLE
Laravel 5.5 Model Binding

### ISSUE THREAD

**Issue by pkeogan** [LaravelCollective/html#466]
I know this isn't supported for laravel 5.5, but has anyone gotten in to work with it and use model binding?

**Comment by pkeogan** [comment]
disregard this, its working fine.

**Comment by darrencoutts118** [comment]
@pkeogan - how did you get this to work. I am still having issues.

**Comment by pkeogan** [comment]
What are your issues or errors your getting ?


---- On Tue, 30 Jan 2018 13:16:56 -0800 notifications@github.com wrote ----

@pkeogan - how did you get this to work. I am still having issues.

**Comment by darrencoutts118** [comment]
No bindings are actually being set. 

``` php
{!! Form::model($food, ['action' => 'FoodController@store']) !!}

                        <div class="form-group">
                            {!! Form::label('title', 'Title') !!}
                            {!! Form::text('title', '', ['class' => 'form-control']) !!}
                        </div>
```

`title` is set within `food` but the text box is empty on load

**Comment by mnabialek** [comment]
Are you sure you don't have `title` parameter in request? From 5.3 to 5.4/5.5 it was changed and now parameter from request take precedence over attribute from model.

**Comment by danieluyo** [comment]
```blade
{!! Form::model($food, ['action' => 'FoodController@update']) !!}
    <div class="form-group">
        {!! Form::label('title', 'Title') !!}
        {!! Form::text('title', null, ['class' => 'form-control']) !!}
     </div>
```

**Comment by pkeogan** [comment]
> No bindings are actually being set.
> 
> {!! Form::model($food, ['action' => 'FoodController@store']) !!}
> 
>                         <div class="form-group">
>                             {!! Form::label('title', 'Title') !!}
>                             {!! Form::text('title', '', ['class' => 'form-control']) !!}
>                         </div>
> title is set within food but the text box is empty on load

You need to pass a value to your Form::text. Your currently passing a unset object, which then the model binding doesnt occur. Attempt **danieluyo** fix by changing 
`{!! Form::text('title', '', ['class' => 'form-control']) !!}` to `{!! Form::text('title', '', ['class' => 'form-control']) !!}`
