### ISSUE TITLE
Can't overwrite form field value on model binding

### ISSUE THREAD

**Issue by lucabartoli** [LaravelCollective/html#48]
The following doesn't work: (text field has not TEST value)
```php
{!! Form::model($page, array('method'=>'PATCH', 'files'=>true, 'route' => array( 'admin.pages.update', $page->id ) )) !!}
		{!! Form::text('parent_text','TEST',array('class'=>'form-control parent')) !!}
{!! Form::close() !!}
```
Seems that second field parameter is ignored if old input is present. Weird behaviour as in L4 you could keep old input passing null, or overwrite it passing a value.

**Comment by osaris** [comment]
+1 another use case : you can't format a value if old input exists

**Comment by tshafer** [comment]
Why are you trying to do this? Form modal was made to automatically fill in fields if they exist, even if they are old.
