### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by meyer59** [LaravelCollective/html#481]
Hi,
Any support for laravel 5.6 ? Unable to upgrade to 5.6

**Comment by tabacitu** [comment]
If this helps at all, just tested ```dev-master``` with Larave 5.6 and it works like a charm. Would be awesome if we could have the current ```master``` tagged and released as ```5.5.2```.

Cheers! Thanks for a great package!

**Comment by phh** [comment]
Added a PR for setting the version back to the latest stable: https://github.com/LaravelCollective/html/pull/482

**Comment by tshafer** [comment]
5.6 will most likely be released next week. We do accept pull requests.
