### ISSUE TITLE
html::style attributes always default

### ISSUE THREAD

**Issue by jva91** [LaravelCollective/html#504]
In the latest version of html for laravel 5.5 the array_merge of the style function merges attributes in the wrong order.

Example:
`{!! HTML::style('path/to/css/file.css', ['media' => 'print']) !!}`
Current style merging: HtmlBuilder.php line 95-97
```
$defaults = ['media' => 'all', 'type' => 'text/css', 'rel' => 'stylesheet'];
$attributes = array_merge($attributes, $defaults);
```
the given $attibutes will be overwritten by the $defaults

For this example the css file for print will be always shown because of the media attibute is always 'all'.

Fix change the order of merging:
HtmlBuilder.php line 97
`$attributes = array_merge($defaults, $attributes);`
Now the defaults will be overwritten by the given attributes

**Comment by crlcu** [comment]
Any idea when this is going to be fixed?

**Comment by tshafer** [comment]
Feel free to send a pull request.

**Comment by crlcu** [comment]
@tshafer - I have created the pull request.
