### ISSUE TITLE
Composer not installing the latest versions

### ISSUE THREAD

**Issue by miclf** [LaravelCollective/html#506]
On [Packagist](https://packagist.org/packages/laravelcollective/html), version `5.6.3` is listed as the latest release of the package. However, on [GitHub](https://github.com/LaravelCollective/html/releases), two more recent versions has been published.

As a result, when instructed to use `^5.6` as a version constraint, Composer cannot install anything newer than `5.6.3`, which is incorrect.

I’m not super aware of the details involved when publishing packages on Packagist, but I guess you simply forgot to instruct it to use your last two versions of `laravelcollective/html`, or something along those lines. Could you please have a look? Thanks :)

**Comment by tshafer** [comment]
Interesting. I'll take a peek

**Comment by tshafer** [comment]
Fixed
