### ISSUE TITLE
HTML helper documentation for dropdown menues 

### ISSUE THREAD

**Issue by zachsa** [LaravelCollective/html#51]
In the "Labels" section there is reference to how to create additional HTML attributes.

In the Drop-down-lists section it would be clearer to mention that there must be a default value before an array for HTML attributes (even if null).

i.e. echo Form::select('size', array('L' => 'Large', 'S' => 'Small'), 'S');

**Comment by tshafer** [comment]
This seems to be here already.

http://laravelcollective.com/docs/5.1/html#drop-down-lists
