### ISSUE TITLE
Form model binding not working in blade components

### ISSUE THREAD

**Issue by zsoltgyure** [LaravelCollective/html#510]
Form model binding is not working when you create a form component:

```
@component('components.form', ['model' => $product ?? null, 'route' => 'products'])
  @component('components.form-group', ['name' => 'name', 'label' => 'Product name:'])
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
  @endcomponent
@endcomponent
```

And `components/form.blade.php` looks like this:
```
{!! Form::model($model, ['method' => 'PATCH', 'route' => [$route . '.update', $model->id]]) !!}
  {!! $slot !!}
{!! Form::close() !!}
```

In this case the field values are not populating (the attributes are exist in the `$model` object). When I use `Form::model()` just where I make the fields, it's working fine. If I `@include` the form opener part, it's also working fine.

Thank you.

**Comment by baihaqyaviq** [comment]
can anyone help?

**Comment by fagner-alves** [comment]
Hi @zsoltgyure, how are you?

did you get a solution to your problem? if yes, could you share with me?

I'm having the same problem over here.

Could anyone help?

**Comment by zoltiecodes** [comment]
Hi @fagner-alves, 

I decided to use a workaround back then. I created a partial blade file and included it , so I didn't use component.

This was my `formOpen.blade.php`
```
{!! isset($model) ? Form::model($model, ['method' => 'PATCH', 'route' => [$route . '.update', $model->id]]) : Form::open(['route' => $route . '.store']) !!}
```

And I used it like this:
```
@include('partials.formOpen', ['model' => $product ?? null, 'route' => 'products'])
```
