### ISSUE TITLE
how can i pass the action attribute in the form using laravel

### ISSUE THREAD

**Issue by alishahbaz344** [LaravelCollective/html#524]
Hi please can anybody tell me how can i pass the action attribute in the form using laravel. I made a form in the laravel but i cannot understand how can i add a action attribute in the form. Without passing the action attribute the form send me an error. The error was is this: MethodNotAllowedHttpException in RouteCollection.php line 251

**Comment by tshafer** [comment]
Please provide code examples of what you have tried.
