### ISSUE TITLE
How to fix this error in laravel?

### ISSUE THREAD

**Issue by alishahbaz344** [LaravelCollective/html#525]
hi please help me to fix this this error, when i try to update the data form user this error showed up.
MethodNotAllowedHttpException in RouteCollection.php line 251.

i attached the files, the files name are:

1. edit.blade.php
2. ApplicantsController.php
3. web.php

please look at this files and tell me how to fix this error
[files.zip](https://github.com/LaravelCollective/html/files/2034666/files.zip)

**Comment by ronappleton** [comment]
You need to read through more examples, you have duplicate routes in web.php, also your form action is empty, you should not try to post and get to the same controller method, you should have an edit action for the get request to show the edit form with the users data, then you should have a update method also, then in your route file (web.php) you should have a Route::put not a post as you are including the PUT, however for updating a record you should be using a patch not a put.
