### ISSUE TITLE
HTML tags inside Anchor tag

### ISSUE THREAD

**Issue by a-komarev** [LaravelCollective/html#53]
I need to create link which will contain not only plain text, but icon in addition, what is a best approach to make it?

```
{!! link_to('/home', '<i class="fa fa-home></i> Main page"') !!}
```

Using this way symbols `<` and `>` decoded and icon isn't displaying because of it.

Thanks.

**Comment by adamgoose** [comment]
All of the HTML builders pass the text through the `e()` helper function, which escapes them. Thus, this cannot be done. You're best bet is to create the `<a>` manually.

Keep in mind, you can also use the `route()` helper function. For example:

```html
<a href="{{ route('home') !!}">
    <i class="fa fa-home"></a> Main Page
</a>
```

**Comment by a-komarev** [comment]
yep... and the second way - create macro for it.
