### ISSUE TITLE
Repopulating form from a get request not working on 5.6.9

### ISSUE THREAD

**Issue by chrisGeonet** [LaravelCollective/html#531]
Using the following form
`{!! Form::open(array('method'=>'GET')) !!}`
`	{!! Form::text('text', null) !!}`
`{!! Form::close() !!}`

then accessing the page with a querystring of ?text=whatever
5.6.8 populates the input
5.6.9 does not

**Comment by decadence** [comment]
https://github.com/LaravelCollective/html/pull/522

That was made optional because many people don't like repopulating from Request by default.

**Comment by chrisGeonet** [comment]
Oh, ok.

How do I make it repopulate? I can't see this in the documentation.

**Comment by decadence** [comment]
Form::considerRequest(true)

**Comment by chrisGeonet** [comment]
Thanks for that. Works a treat.

**Comment by webtechnick** [comment]
Is there a way to turn it back on globally?

**Comment by webtechnick** [comment]
For those wondering, I was able to globally turn it on via the `AppServiceProvider::boot()` method.

```
public function boot()
{
    $this->app->make('form')->considerRequest(true);
}
```

**Comment by decadence** [comment]
Yes. AppServiceProvider or Base Controller constructor can be used fot that.

**Comment by webtechnick** [comment]
My only concern with that is I'm being forced to instantiate the form on every request even if I only need it for half of the requests. Would be much nicer if I could just set a configuration instead and it would set it on construct.

So, I did that and made a PR. I'm certainly open to other ways. I'm certainly a little frustrated by this breaking change in a minor update.

**Comment by decadence** [comment]
Package is not fully supported (I mean it gets not much time) so BC will happen sometimes. Initially I made it optional long time ago. While maintainers considers it few new version of Laravel and this package were released so I needed to make new PR for actual branch.

**Comment by webtechnick** [comment]
I get that and appreciate the continued work on it. I use this package in all my Laravel projects and have been very happy with it. I rely on the previous behavior of considering the request and was just caught off guard that the default changed on a minor composer version update.

Hope you'll consider my PR, if not, no worries.

**Comment by decadence** [comment]
I get your point and agree that BC in minor update should not happen.
About this BC: many people don't like this feature by default (you can find many issues) so I decided to fix this. Obviously there are people who like this feature by default :)
Maybe this repo needs some contribution guide.

P.S. I am not a maintainer.

**Comment by tshafer** [comment]
@decadence Want to be a maintainer?

**Comment by decadence** [comment]
@tshafer thanks. I don't have much experience in maintaining open source but I will try

**Comment by tshafer** [comment]
@decadence Everyone has to learn sometime. :) I don't have a lot of free time these days. Could use the help.

**Comment by decadence** [comment]
@tshafer 👍

**Comment by desthercz** [comment]
Adding a feature is great, but you should really keep defaults as they are and let people change the behaviour if they want, not vice versa. Especially when there is no upgrade guide. I think this is best practice anyway.

**Comment by Spodnet** [comment]
Also, took me a few hours of working out this morning, #522 also broke old() functionality.

```
{{ Form::text('my_field', old('my_field', 'default value')) }}
```

Wasn't re-populating my_field when the page re-loaded
