### ISSUE TITLE
Form select not creating option groups if sub-arrays are collections and not plain array.

### ISSUE THREAD

**Issue by kentdahl** [LaravelCollective/html#535]
Ran into this when populating the select from database values. Instead of working as expected, the collections came out as JSON string.

Example code:
```
# Fails:
[
  "Standard reports" => $user->globalReportTypes()->get()->pluck('name', 'id'),
  "Custom reports"  => $user->userReportTypes()->get()->pluck('name', 'id'),
]

# Works:
[
  "Standard reports" => $user->globalReportTypes()->get()->pluck('name', 'id')->toArray(),
  "Custom reports"  => $user->userReportTypes()->get()->pluck('name', 'id')->toArray(),
]
```

The line in question:

https://github.com/LaravelCollective/html/blob/fda9d3dad85ecea609ef9c6323d6923536cf5643/src/FormBuilder.php#L740

**Comment by tshafer** [comment]
How is this a problem?

**Comment by kentdahl** [comment]
Inconsistency mainly. Sending a collection to the list argument top-level works, but once you put it in a sub-entry for option group it fails in a (for me atleast) surprising manner.

If the rest of Form builder is collection agnostic in general (and thus passing collections working is more of a "pleasent surprise") then this probably should stay the way it is.

**Comment by tshafer** [comment]
I’d accept a pull request with tests.

**Comment by tautvydasr** [comment]
I faced a similar issue some time ago, submitted a pull-request that I guess should solve the issue.
