### ISSUE TITLE
Class "Form" not found when custom folder view

### ISSUE THREAD

**Issue by bocanhcam** [LaravelCollective/html#536]
Hi. I'm using this package nWidart/laravel-modules to manage modules. 
So my view blade now like this Modules/Admin/Resources/views/index.blade.php
My code is simple like this
`{!! Form::select('category_ids[]', $categories, $category_ids, [
                            'class'=>'form-control select2',
                            'id'   => 'category_ids',
                            'required' => true,
                            'multiple' => true,
                            ] ) !!}`
And I got the error Class "Form" not found. Can you help me fix it out

PHP V7
Laravel v5.4
LaravelCollective/html v5.3.0
nWidart/laravel-modules v3

**Comment by tshafer** [comment]
You need register the facade. Check the docs to see how.
