### ISSUE TITLE
Fresh 5.1+ installation - Class 'Collective\Html\HtmlServiceProvider' not found

### ISSUE THREAD

**Issue by black-snow** [LaravelCollective/html#54]
Hi,

I made a fresh laravel 5.1+ installtion via `laravel new` and did the steps required for this package (composer, providers, aliases).

=>

    [Symfony\Component\Debug\Exception\FatalErrorException]  
    Class 'Collective\Html\HtmlServiceProvider' not found  

Composer require section:

    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "laravelcollective/html": "5.1.*"
    },

Any guesses?

**Comment by hardkiffeur** [comment]
Same here, what I've done to pass this error :
1) Remove the laravelcollective require from the composer.json
2) Run a composer update before readd the line
It's ok for me

**Comment by 0x1ad2** [comment]
Try to add the providers and aliases like they did in there installation docs http://laravelcollective.com/docs/5.1/html#installation should work.

**Comment by black-snow** [comment]
@0x1ad2 we did that already

**Comment by 0x1ad2** [comment]
@black-snow and still the same error? Maybe you need to use the `composer dump-autoload` command.

> If you need to update the autoloader because of new classes in a classmap package for example, you can use "dump-autoload" to do that without having to go through an install or update.

**Comment by black-snow** [comment]
I'll try that this evening

**Comment by abaterdene** [comment]
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework 5.2.x-dev
    - laravelcollective/html 5.1.x-dev requires illuminate/support 5.1.* -> satisfiable by illuminate/support[5.1.x-dev, v5.1.1, v5.1.2].
    - laravelcollective/html v5.1.0 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[5.1.x-dev, v5.1.1, v5.1.2].
    - laravelcollective/html v5.1.1 requires illuminate/support 5.1.* -> satisfiable by illuminate/support[5.1.x-dev, v5.1.1, v5.1.2].
    - don't install illuminate/support 5.1.x-dev|don't install laravel/framework 5.2.x-dev
    - don't install illuminate/support v5.1.1|don't install laravel/framework 5.2.x-dev
    - don't install illuminate/support v5.1.2|don't install laravel/framework 5.2.x-dev
    - Installation request for laravel/framework 5.2.* -> satisfiable by laravel/framework[5.2.x-dev].
    - Installation request for laravelcollective/html 5.1.* -> satisfiable by laravelcollective/html[5.1.x-dev, v5.1.0, v5.1.1].
```

I get this error, when i tried to composer update after I required laravelcollective/html in json file.

**Comment by 0x1ad2** [comment]
@abaterdene looks like you are using the latest version of Laravel that's unstable see their repo to get the stable version(5.1.3) https://github.com/laravel/laravel

**Comment by teqizm** [comment]
@black-snow. The error "Class 'Collective\Html\HtmlServiceProvider' not found" could mean that you have included it in the ServiceProvider in config/app.php file before upgrading. You should go to the file (app.php) and remove this (Collective\Html\HtmlServiceProvider::class,) line then save the file and run "composer upgrage" again.

**Comment by tshafer** [comment]
@0x1ad2 and @black-snow have the right idea

**Comment by andresrivas1506** [comment]
in composer.json->scripts change this:
```javascript
"pre-update-cmd": [
    "php artisan clear-compiled"
],
"post-update-cmd": [
    "php artisan optimize"
],
```
for this:
```javascript
"post-update-cmd": [
    "php artisan clear-compiled",
    "php artisan optimize"
],
```

**Comment by tduru** [comment]
@andresrivas1506 it worked, thank you.

**Comment by andresrivas1506** [comment]
@tduru Until now I have not seen any.

**Comment by andela-fokosun** [comment]
Thanks all! Finally, i got it working. Thanks to you all. I simply just had to start over again following the documentation  every step of the way http://laravelcollective.com/docs 5.1/html#installation

**Comment by gabouh** [comment]
@andresrivas1506 it worked, thanks a lot :)

**Comment by abiodunsulaiman694** [comment]
Thanks @teqizm, removing 'Collective\Html\HtmlServiceProvider' from ServiceProvider in config/app.php worked for me.

**Comment by vanisreerehash** [comment]
FatalErrorException in 4479bc8de6a7c2824192235d15e389f376f539a2.php line 8:
Class 'Form' not found

Still facing this issue after composer updating and adding htmlServiceprovider in config/app.php laravel 5.2

**Comment by arivasvera** [comment]
@vanisreerehash do you add the class aliases to the `aliases` array of `config/app.php` ?
 ```php
 'aliases' => [
    // ...
      'Form' => Collective\Html\FormFacade::class,
      'Html' => Collective\Html\HtmlFacade::class,
    // ...
  ],
```

**Comment by chamsedine-bouhouch** [comment]
I faced the same problem installing LarvelCollective to Laravel 5.2:
the main problem was with composer installation it should be linked to an old php version (php5.*.*)

> 1.  I reinstalled composer with php7.1.26 in my case then
 

> 2. I run `composer require "laravelcollective/html":"^5.2.0" ` on cmd

> 3. I modified  the app.php as in the documentation [:](https://laravelcollective.com/docs/5.2/html) 

 **### and it worked**



This is how my composer.json  looks like
    ` "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "laravelcollective/html": "^5.2.0"}, `

**Comment by laratuto** [comment]
[Solved Here code small error](http://laratuto.com)
