### ISSUE TITLE
Select, relationships and lists

### ISSUE THREAD

**Issue by pacoorozco** [LaravelCollective/html#55]
I'm using the FormBuilder and have a select named the same thing as one of my model's relationships (a many-to-many relationship), but when using form model binding, it ignores any attempts I make to manually override the status of whether it's selected or not.

    {!! Form::select('usergroups[]', $groups, $user->groups->lists('id'), array('multiple' => 'multiple') !!}

Doing this, I would expect it a select with some selected values, depending my relationship piece. Instead, no select is selected.

This is User model relationship:

    public function groups()
    {
        return $this->belongsToMany('SSHAM\Usergroup');
    }

And this my controller wich calls the view:

    public function edit(User $user)
    {
        // Get all existing user groups
        $groups = Usergroup::lists('name', 'id');
        return view('user.edit', compact('user', 'groups'));
    }

And my view:

    {!! Form::model($user, ['route' => ['users.update', $user->id], 'method' => 'put']) !!}
    {!! Form::select('usergroups[]', $groups, $user->groups->lists('id'), array('multiple' => 'multiple') !!}
    {!! Form::close() !!}

Am I missing something about how to get this to work or have I stumbled across an issue?

**Comment by tshafer** [comment]
What version of laravel?

**Comment by pacoorozco** [comment]
Oh sorry... Laravel 5.1 :D

**Comment by tshafer** [comment]
lists() has changed with 5.1, it now returns a collection, you need to add all() toto grab them.

Try this

$user->groups->lists('id')->all();

**Comment by pacoorozco** [comment]
@tshafer It works great, thanks for your support I haven't see this change on release notes from 5.0. :smile:
