### ISSUE TITLE
v5.6.9 possible select bug

### ISSUE THREAD

**Issue by misog** [LaravelCollective/html#556]
Hi, select changed behavior when I upgraded from v5.6.8 to v5.6.9 Form::select

``@form_select('per_page', [10=>10, 20=>20, 30=>30], null, ['class'=>'form-control'])``

This takes  submitted value in a request into account in v5.6.8 - if per_page is 20 when a form is submitted then selected attribute is inserted to option with value 20.

However in v5.6.9 the submitted value from the request is ignored and no selected attribute is inserted into HTML so the select has always default value 10.

**Comment by decadence** [comment]
https://github.com/LaravelCollective/html/issues/531
