### ISSUE TITLE
Format::label doesnt print 0 as value

### ISSUE THREAD

**Issue by Slipy90** [LaravelCollective/html#559]
If i call
```php
{{ Form::label('label_name', 0) }}
```
i get
```html
<label for="label_name">Label Name</label>
```
but i need
```html
<label for="label_name">0</label>
```

I checked the code and i found this method
```php
    /**
     * Format the label value.
     *
     * @param  string      $name
     * @param  string|null $value
     *
     * @return string
     */
    protected function formatLabel($name, $value)
    {
        return $value ?: ucwords(str_replace('_', ' ', $name));
    }
```
which evaluates 0 as false and that's why i get the name of label as value instead of 0.

I think it's not a big problem but a little bit frustrating.

**Comment by mnokin** [comment]
I got exactly the same problem. I fixed it with:

`
    /**
     * Format the label value.
     *
     * @param  string      $name
     * @param  string|null $value
     *
     * @return string
     */
    protected function formatLabel($name, $value)
    {
        return ($value === null? ucwords(str_replace('_', ' ', $name)):$value);
    }
`

**Comment by Slipy90** [comment]
@mnokin Ty for suggestion.

I've created a custom service provider which extends the original collective service provider and override the registerFormBuilder method to load my patched FormBuilder. 
Is there any better way to do it?

**Comment by mnokin** [comment]
Until it's fixed, that's the way to go imho. Meanwhile, I opened a pull request #563
