### ISSUE TITLE
deploying to heroku -  PHP fatal error: Class 'Collective\Html\HtmlServiceProvider' not found

### ISSUE THREAD

**Issue by markat1** [LaravelCollective/html#56]
Hello

I'm trying to deploy my laravel project to heroku. Application works fine locally, but when I try to deploy it on heroku i get the following error:

Writing objects: 100% (9/9), 1.01 KiB | 0 bytes/s, done.
Total 9 (delta 6), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Fetching custom git buildpack... done
remote: -----> PHP app detected
remote: -----> Resolved composer.lock requirement for PHP to version 5.6.10.
remote: -----> Installing system packages...
remote:        - PHP 5.6.10
remote:        - Apache 2.4.10
remote:        - Nginx 1.6.0
remote: -----> Installing PHP extensions...
remote:        - mbstring (composer.lock; bundled)
remote:        - zend-opcache (automatic; bundled)
remote: -----> Installing dependencies...
remote:        Composer version 1.0.0-alpha10 2015-04-14 21:18:51
remote:        Loading composer repositories with package information
remote:        Installing dependencies from lock file
remote:        Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
remote:          - Installing jakub-onderka/php-console-color (0.1)
remote:            Downloading: 100%
remote:
remote:          - Installing vlucas/phpdotenv (v1.1.1)
remote:            Downloading: 100%
remote:
remote:          - Installing symfony/var-dumper (v2.7.1)
remote:            Downloading: 100%
remote:
remote:          - Installing symfony/translation (v2.7.1)
remote:            Downloading: 100%
remote:
remote:          - Installing symfony/routing (v2.7.1)
remote:            Downloading: 100%
remote:
remote:          - Installing symfony/process (v2.7.1)
remote:            Downloading: 100%
remote:
remote:          - Installing symfony/http-foundation (v2.7.1)
remote:            Downloading: 100%
remote:
remote:          - Installing symfony/event-dispatcher (v2.7.1)
remote:            Downloading: 100%
remote:
remote:          - Installing psr/log (1.0.0)
remote:            Downloading: 100%
remote:
remote:          - Installing symfony/debug (v2.7.1)
remote:            Downloading: 100%
remote:
remote:          - Installing symfony/http-kernel (v2.7.1)
remote:            Downloading: 100%
remote:
remote:          - Installing symfony/finder (v2.7.1)
remote:            Downloading: 100%
remote:
remote:          - Installing symfony/dom-crawler (v2.7.1)
remote:            Downloading: 100%
remote:
remote:          - Installing symfony/css-selector (v2.7.1)
remote:            Downloading: 100%
remote:
remote:          - Installing symfony/console (v2.7.1)
remote:            Downloading: 100%
remote:
remote:          - Installing swiftmailer/swiftmailer (v5.4.1)
remote:            Downloading: 100%
remote:
remote:          - Installing nikic/php-parser (v1.3.0)
remote:            Downloading: 100%
remote:
remote:          - Installing jakub-onderka/php-console-highlighter (v0.3.2)
remote:            Downloading: 100%
remote:
remote:          - Installing dnoegel/php-xdg-base-dir (0.1)
remote:            Downloading: 100%
remote:
remote:          - Installing psy/psysh (v0.4.4)
remote:            Downloading: 100%
remote:
remote:          - Installing nesbot/carbon (1.20.0)
remote:            Downloading: 100%
remote:
remote:          - Installing mtdowling/cron-expression (v1.0.4)
remote:            Downloading: 100%
remote:
remote:          - Installing monolog/monolog (1.14.0)
remote:            Downloading: 100%
remote:
remote:          - Installing league/flysystem (1.0.4)
remote:            Downloading: 100%
remote:
remote:          - Installing jeremeamia/superclosure (2.1.0)
remote:            Downloading: 100%
remote:
remote:          - Installing doctrine/inflector (v1.0.1)
remote:            Downloading: 100%
remote:
remote:          - Installing danielstjules/stringy (1.9.0)
remote:            Downloading: 100%
remote:
remote:          - Installing symfony/filesystem (v2.7.1)
remote:            Downloading: 100%
remote:
remote:          - Installing classpreloader/classpreloader (1.4.0)
remote:            Downloading: 100%
remote:
remote:          - Installing laravel/framework (v5.1.3)
remote:            Downloading: 100%
remote:
remote:        Generating optimized autoload files
remote:        PHP Fatal error:  Class 'Collective\Html\HtmlServiceProvider' not found in /tmp/build_44f0e34f5ede5fd47193377db8b28292/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146
remote:
remote:
remote:
remote:          [Symfony\Component\Debug\Exception\FatalErrorException]
remote:          Class 'Collective\Html\HtmlServiceProvider' not found
remote:
remote:
remote:
remote:        Script php artisan clear-compiled handling the post-install-cmd event returned with an error
remote:
remote:
remote:                                                                                                                                  
remote:          [RuntimeException]                                                                                                      
remote:          Error Output: PHP Fatal error:  Class 'Collective\Html\HtmlServiceProvider' not found in /tmp/build_44f0e34f5ede5fd47193377db8b28292/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146
remote:                                                                                                                                  
remote:
remote:
remote:        install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [packages1] ... [packagesN]
remote:
remote:
remote:
remote:  !     Push rejected, failed to compile PHP app
remote:
remote: Verifying deploy...
remote:
remote: !       Push rejected to alican.
remote:

**Comment by GrahamCampbell** [comment]
That;s because it's not in your composer file as you can see by it not being downloaded...

**Comment by markat1** [comment]
well, this is my composer file:

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "nesbot/carbon": "^1.19"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1",
        "laravelcollective/html": "5.1.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ],
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}

**Comment by GrahamCampbell** [comment]
You need to move "laravelcollective/html": "5.1.*" from require-dev to require.

**Comment by GrahamCampbell** [comment]
Also you should remove "nesbot/carbon": "^1.19".

**Comment by markat1** [comment]
oh ok. Silly me, I'm new to this. I will try it out!. thank you so much!

**Comment by markat1** [comment]
btw - why should I delete nesbot/carbon?

**Comment by GrahamCampbell** [comment]
Because laravel already requires it.

**Comment by markat1** [comment]
ok, thank you so much - normally I would use stackoverflow, but I thought it was a bigger problem.

**Comment by GrahamCampbell** [comment]
No problem. :)

**Comment by raokaleemullah** [comment]
I am getting the error when i am going to develop a project .
 FatalErrorException in ProviderRepository.php line 146:
Class 'Illuminate\Html\HtmlServiceProvider' not found

Plz give the solution if any one know about how to resolve this issue
