### ISSUE TITLE
laravel/framework 5.7.x-dev Issue

### ISSUE THREAD

**Issue by bhargav960143** [LaravelCollective/html#562]
Problem 1
    - Conclusion: remove laravel/framework 5.7.x-dev
    - Conclusion: don't install laravel/framework 5.7.x-dev

**Comment by cve** [comment]
+1

**Comment by virusphp** [comment]
i think so, i can't install laravelcollective 5.4
in laravel 5.7

**Comment by repat** [comment]
Install 5.6

**Comment by decadence** [comment]
5.7 branch is out now
