### ISSUE TITLE
Please open for Laravel 5.7. 

### ISSUE THREAD

**Issue by kemalovska** [LaravelCollective/html#564]
We need to wait till there is a 5.7 version of laravelcollective/html because the current latest is locked to 5.6.

**Comment by nickurt** [comment]
Yeah, would be nice ... cc @tshafer

**Comment by PheRum** [comment]
@tshafer ping

**Comment by repat** [comment]
We need this soon as well :)

**Comment by BassemN** [comment]
Please add support for Laravel 5.7

**Comment by n-osennij** [comment]
+1

**Comment by BassemN** [comment]
A temporary solution until LaravelCollective release a new update, open your composer.json file and add the following:
```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/BassemN/laravelcollectivehtml"
        }
    ],
```
then run `composer update` command

**Comment by n-osennij** [comment]
Pull request - #565

**Comment by kemalovska** [comment]
Heyyyyyy anyone can you do it? Hear us pleeeaaasseee!

**Comment by n-osennij** [comment]
@kemalovska it's done 15 days ago

**Comment by decadence** [comment]
5.7 branch is created

**Comment by hassy008** [comment]
using this commad....and it's working with **Laravel 5.7**
composer require laravelcollective/html

**Comment by hassy008** [comment]
`asd`

**Comment by layepythagore** [comment]
> 
> 
> using this commad....and it's working with **Laravel 5.7**
> composer require laravelcollective/html

it's working, thanks

**Comment by xlcrr** [comment]
changing composer.json to

        "laravelcollective/html": "5.7.*",

and running composer update worked for me

**Comment by Shweta-Kalariya** [comment]
> changing composer.json to
> 
> ```
>     "laravelcollective/html": "5.7.*",
> ```
> and running composer update worked for me

It worked for me too.. Thanks

**Comment by rasel21088** [comment]
how to install laravelcollective/html in laravel version 5.8.16
