### ISSUE TITLE
jquery-editable-select - selected

### ISSUE THREAD

**Issue by sinergycode** [LaravelCollective/html#572]
Hi i am using LaravelCollective and jQuery Editable Select.
The Form::select not show the selected element:
file.blade
Form::select('filter',$filters, $data['filter'], ['id' => 'editable'])
<script>
    $('#editable').editableSelect();
</script>
Help please to resolve the problem...

**Comment by decadence** [comment]
Post your HTML output. Maybe `$data['filter']` doesn't have value that in $filters.

**Comment by sinergycode** [comment]
Thks for fast answer!
I maked the next:
```
<select name="filter" id="editable">
                @foreach($filters as $item)
                  <option {{ ($item == $data['filter']) ? "selected" : ''}}>
                    {{$item}}
                  </option>
                @endforeach
            </select>
```
and i get this:
![image](https://user-images.githubusercontent.com/30791491/47371249-22d9e300-d6f0-11e8-9623-a652310d8210.png)
All it's working, but there are spaces on the sides of the string.

**Comment by decadence** [comment]
Try write it in one string `<option {{ ($item == $data['filter']) ? "selected" : ''}}>{{$item}}</option>`
Or use `trim` function.

Anyway it's issue belongs to jQuery Editable Select. Maybe it is not trimming values.
