### ISSUE TITLE
Form:textarea documentation seems a little misleading!

### ISSUE THREAD

**Issue by MaddyGit** [LaravelCollective/html#579]
[Larvel Collective Documentation](https://laravelcollective.com/docs/master/html#text) for Form & HTML says 

> The hidden and textarea methods have the same signature as the text method.

which can easily be perceived as _"Form::textarea() does not exists, Form::text() should be used for all three being text, textarea and hidden"_, Whereas for textarea the method _Form::textarea()_ actually exists, which obviously does not have the same signature as _Form::text()_.

So my opinion is the documentation should rather read as 
> The hidden and textarea methods have the **similar** signature as the text method.

**Comment by decadence** [comment]
> which can easily be perceived as "Form::textarea() does not exists
> The hidden and textarea **methods** have the same signature as the text method.

"Methods" means that methods exist.

Anyway you are free to open PR to https://github.com/LaravelCollective/docs repository.
