### ISSUE TITLE
After upgrade to Laravel 5.7, Forms submit empty inputs return Null

### ISSUE THREAD

**Issue by marwan2** [LaravelCollective/html#586]

**Comment by marwan2** [comment]
After upgrade my project from 5.2 to 5.7 The submit of forms not working properly
In the past, empty fields was return empty string, but not it return NULL

`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'details_en' cannot be null `

**Comment by sanderdekroon** [comment]
This is a default functionality of Laravel now, to turn empty strings into null for requests. I believe the ConvertEmptyStringsToNull middleware handles this. This middleware is loaded in app/Http/Kernel.php in the $middleware property.

Try to remove that middleware and see if that resolves your issue.

**Comment by decadence** [comment]
It's because of `ConvertEmptyStringsToNull`. Not a laravelcollective/html issue.
https://laravel-news.com/laravel-5-4-middleware

**Comment by marwan2** [comment]
Thanks, ya the middleware is the reason
