### ISSUE TITLE
Add Support for 5.8

### ISSUE THREAD

**Issue by hebbet** [LaravelCollective/html#587]
Laravel 5.8 is going to be released tomorrow

**Comment by n-osennij** [comment]
#588 Pull Request

**Comment by armagedan** [comment]
I literally just dropped all my work and came here to say that its not supported. Please do a merge so I can get back to smashing keyboard.

**Comment by brianwozeniak** [comment]
Please merge! 5.8 was released a few days ago now!

**Comment by Behinder** [comment]
Please merge!

**Comment by lorvent** [comment]
having more than 10+ famous dependencies... i am getting a feeling,
either we should fork or stop depending on too many packages.

i have visited this repo more than 100 times after 5.8 released in a hope that, it supports 5.8 and i am still waiting.

**Comment by armagedan** [comment]
As long as the dependencies are updated and running well with laravel releases, then I do not exactly see a reason why we should remove anything. Besides, removing meaning more tweaks. I like it the way it is as it is stable as of now and much much easier to work with. Then again, I maybe wrong. Hope this gets merged soon :)

**Comment by lorvent** [comment]
I agree with you, that is the reason why we use packages, it saves our time.

but again for each release....for 4-5days we have to chase each package to provide support for new version, which is kinda becoming frustrating.

i can understand this is OS package but......

**Comment by haneef5k** [comment]
Please merge the PR, waiting for Laravel 5.8 Support.

**Comment by repat** [comment]
Just checking in, we also _really_ need this merged asap please!

**Comment by eflames** [comment]
Saldy I will need to refactor my app to use single blade forms instead this package. All of the packages of my app has added 5.8 except this. :(

**Comment by celcius-jochen** [comment]
Give the guy a break, he mentioned on twitter being on his honeymoon with his wife and now doing the best he can to get everything ready before the weekend.

**Comment by lorvent** [comment]
oops! 😍

**Comment by RalphMRivera** [comment]
As a temporary solution, you can use the forked version here: https://github.com/ranabd36/laravelcollective

It's on Packagist now.

I ran `composer require ranabd36/laravelcollective` and it works great as a holdover until this package is updated over the weekend.

**Comment by eflames** [comment]
> As a temporary solution, you can use the forked version here: https://github.com/ranabd36/laravelcollective
> 
> It's on Packagist now.
> 
> I ran `composer require ranabd36/laravelcollective` and it works great as a holdover until this package is updated over the weekend.

Thanks bro!

**Comment by ranabd36** [comment]
You can use my forked repo through composer. 
`composer require ranabd36/laravelcollective`

**Comment by armagedan** [comment]
Great workaround guys

**Comment by Behinder** [comment]
Taylor shoul really consult his releasing plans with people's honeymoons :)

**Comment by mlantz** [comment]
The code has been merged and released. Next week the website will be updated with a statement regarding my intentions and the next steps with Laravel Collective.

**Comment by johnef** [comment]
> 
> 
> As a temporary solution, you can use the forked version here: https://github.com/ranabd36/laravelcollective
> 
> It's on Packagist now.
> 
> I ran `composer require ranabd36/laravelcollective` and it works great as a holdover until this package is updated over the weekend.

Not working any Idea

**Comment by mikebronner** [comment]
@johnef That work-around should no longer be necessary. The official package has been updated for 5.8 for quite some time now.

**Comment by johnef** [comment]
> 
> 
> @johnef That work-around should no longer be necessary. The official package has been updated for 5.8 for quite some time now.

I try to use it but not working where can I find the official package documents please. for L5.8

**Comment by armagedan** [comment]
@johnef The package was updated to work with the latest laravel version about 3 months ago. Please use the official composer package. Everything works as expected. Please open a new issue if you are having issues

**Comment by johnef** [comment]
> 
> 
> @johnef The package was updated to work with the latest laravel version about 3 months ago. Please use the official composer package. Everything works as expected. Please open a new issue if you are having issues

do I the only one who see this on the official website??

>Hello World,

This is a brief letter to all of those who have used Laravel Collective packages for the past few years. Laravel Collective was created as a group to support components of the Laravel Framework which were removed and no longer supported by the core team. Though this served many developers well, it has in our opinion run its course in its current form.

We’re now looking at what will serve the community best. We are currently starting development of a whole new website, with some exciting features we hope will inspire the Laravel community worldwide. We will post updates regarding that via Twitter @LaraCollective. As for the packages themselves, we have had to make some tough decisions. But we’ve looked our rough download numbers and they just don’t lie.

    HTML: ~16000 Daily Downloads
    Remote: ~900 Daily Downloads
    Annotations: ~115 Daily Downloads
    Bus: ~85 Daily Downloads
    Iron-queue: ~2 Daily Downloads

**Comment by armagedan** [comment]
@johneh. Sorry it took this long. Try this link

https://drive.google.com/drive/folders/1eNyXRmdn1Ob9yj1ETEA3eIl-bGr6YPvV

It points to my google drive. The file is an export of a markdown readme file of laravel
Collective which was updated on 2015. Please note that this doc file is
Outdated but it should be enough to get you started and get a better Idea of how things work. 

    //basic open and close
    { !! Form::open(‘action’ => ‘someController,, ‘method’ => ‘POST’) !! }
    { !! From::close() !! }

    //model binding (this is normally used for stuff like when you want to auto fill the text fields when you are editing a post or something. It will automatically fill those fields with existing data. Note: doesn’t work on checkbox, radio or dropdowns
    { !! Form::model($edit, [‘action’ => ‘[‘someController@update’, $edit->id]]’, ‘method’ => ‘PUT’ !! }

    //basic text field
    { !! Form::text(‘firstName’, null, [‘class’ => ‘style-class’] !! }
    //here is the output <input type=“text” class=“style-class” />. Remember the “null” is the default value of the input field and i let it null because I don’t want a default value 

Same goes for checkbox and other html tags. Hope this helped. I’m in the hospital bed typing on a phone so again, sorry. Hope this helps. The official docs will be release soon I hope. Till then, I hope this gets you started. Happy coding :)

**Comment by Behinder** [comment]
We wish you good health then and quick recovery

**Comment by johnef** [comment]
it's working, but still some IDE like PHPstorm says
>undefined class Form
and also no auto-complete like before.
any idea.

**Comment by armagedan** [comment]
@johnef Phpstorm does not auto correct or suggest everything. It’s an IDE issue when it says undefined. If it’s working, I do not see any issues. It is common for IDE’s to popup these errors. Ignore it

**Comment by johnef** [comment]
@armagedan Thanks man, suddenly working perfect.
