### ISSUE TITLE
https://laravelcollective.com showing invalid certificate

### ISSUE THREAD

**Issue by enefgee** [LaravelCollective/html#592]
In Google Chrome - MacOS High Sierra
The SSL certificate is showing invalid
![image](https://user-images.githubusercontent.com/15147458/53698016-a649c600-3dad-11e9-904c-74dda2ea5eac.png)

**Comment by sohelkarimju** [comment]
Same issue

**Comment by mmjjb** [comment]
Google Chrome on Windows, the same.

**Comment by mmjjb** [comment]
Google Chrome on Windows, the same.
@adamgoose

**Comment by LeRoyJulian** [comment]
Owners of this repository are a joke.

**Comment by mlantz** [comment]
That's kind of you @LeRoyJulian. Adam was inundated due to an issue between him and Google. I have since moved the site over to a new server and set the domain accordingly. I will, moving forward, be dedicating time to this repository.
