### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by DA40** [LaravelCollective/html#594]
Readme.md says "Official documentation for Forms & Html for The Laravel Framework can be found at the LaravelCollective website" and that website says it's here on github!

**Comment by decadence** [comment]
Looks like guys are going to make new site so I changed link in README for now. Current site doesn't contain any docs.
Ping @mlantz just in case.
https://github.com/LaravelCollective/html/pull/595

P.S. Looks like my push access to this repo has been disabled so I can't merge this PR by myself.

**Comment by jeremiahsherrill** [comment]
This is dead, I would move on from this project.

**Comment by tshafer** [comment]
It's not dead, please read the docs repo.

**Comment by OssiPesonen** [comment]
fyi docs can be found here now: https://github.com/LaravelCollective/docs

**Comment by marymvlg28** [comment]
Would someone be so kind to explain how do I see Laravel collective docs ?

**Comment by tshafer** [comment]
https://github.com/LaravelCollective/docs

**Comment by ashowalter-r7** [comment]
Docs are gone.  FYI.

**Comment by fbingha** [comment]
Yes, no docs.

**Comment by tshafer** [comment]
The documents are here people.

https://github.com/LaravelCollective/docs

**Comment by fbingha** [comment]
Why don't you try following the links to the docs, then come back and say that again.

**Comment by tshafer** [comment]
Done


https://github.com/LaravelCollective/docs/blob/5.6/html.md

**Comment by fbingha** [comment]
You can see that people tend to click the file called "docs.md" and get a 404, right?

**Comment by ashowalter-r7** [comment]
I can see the docs there now here: https://github.com/LaravelCollective/docs and clicking the html link.  Thank you

**Comment by Linkerty** [comment]
I have searched a while to find this here. I would like if this is directly linked in the readme, so everyone know at first glance, where to look.
