### ISSUE TITLE
Updated to 5.8

### ISSUE THREAD

**Issue by johnef** [LaravelCollective/html#605]
I updated to 5.8.0 but still can't understand some points as the Website documentation is closed.

Do I have to register `providers`

`Collective\Html\HtmlServiceProvider::class,`
and the `aliases`
~~~
'Form'                => Collective\Html\FormFacade::class,
'Html'                => Collective\Html\HtmlFacade::class,
~~~

even so if I did it dose not work as expected

**Comment by armagedan** [comment]
Please refer to this and let me know [https://github.com/LaravelCollective/html/issues/587#issuecomment-497086556](‘Comment’)

**Comment by johnef** [comment]
Suddenly working perfect. thanks
