### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by lorvent** [LaravelCollective/html#607]
Hello,
I still remember 5.8 update time problems of dev :(

he is going through some personal problems and people are waiting here for 5.8 support, so i really don't feel like posting this issue

BUT have no choice... :(

laravel 6 is around corner and i am sure 1000s of developers rely on this package, so i hope you can make it compatible with laravel 6.

thanks.

**Comment by daveatpeta** [comment]
https://github.com/LaravelCollective/html/tree/6.0

https://packagist.org/packages/laravelcollective/html#6.0.x-dev

**Comment by hebbet** [comment]
it is released:
https://github.com/LaravelCollective/html/releases/tag/v6.0
