### ISSUE TITLE
[L5.1] Is this the best way to use Autofocus ?

### ISSUE THREAD

**Issue by dogrocker** [LaravelCollective/html#62]
Hello, I'm trying to use `autofocus` with partial form.

Did I do the right thing ? Or it has an easy way to do this ?

```
{!! Form::text('firstname', isset($user->firstname) ? $user->firstname : '', ['autofocus' => '']) !!}
```

Thanks.

**Comment by tshafer** [comment]
You can simply do ['autofocus']

```{!! Form::text('firstname', isset($user->firstname) ? $user->firstname : '', ['autofocus']) !!} ```

**Comment by dogrocker** [comment]
Thanks @tshafer .
