### ISSUE TITLE
Form::model not working properly

### ISSUE THREAD

**Issue by atudz** [LaravelCollective/html#630]
I have a page with 2 tabs in it, each tab has a Form::model. I set the the Form::text component value to null so that the Form::model will handle it. When i submit one of the form and laravel returns an error, I noticed that the other form that wasn't submitted the values became empty/nulll. After digging in the vendor code i found this line of code which i don't know what's the purpose. 

        if (function_exists('app')) {
            $hasNullMiddleware = app("Illuminate\Contracts\Http\Kernel")
                ->hasMiddleware(ConvertEmptyStringsToNull::class);

            if ($hasNullMiddleware
                && is_null($old)
                && is_null($value)
                && !is_null($this->view->shared('errors'))
                && count(is_countable($this->view->shared('errors')) ? $this->view->shared('errors') : []) > 0
            ) {
                return null;
            }
        }

**Comment by mlantz** [comment]
This code is fine, your issue is with form submissions and processing.
