### ISSUE TITLE
[bug] Unexpected behavior with error bags

### ISSUE THREAD

**Issue by damms005** [LaravelCollective/html#638]
The way errors are handled in [FormBuilder.php](https://github.com/LaravelCollective/html/blob/6.0/src/FormBuilder.php) is based on the assumption that whenever error bag is not empty, a `redirect()->back()` on validation error is what is happening and thus `old(...)` will always contain flashed data. 

However, I hit a bug when I did an ordinary `redirect()->route()->withError(...)`. Since this does not have anything inside `old()`, form fields did not get auto-filled with model properties.

I believe this bug can be fixed by moving [this line](https://github.com/LaravelCollective/html/blob/6.0/src/FormBuilder.php#L1293-L1305) to the very end, after the model would have been checked; which brings me to the next point: is that [`if(...)`](https://github.com/LaravelCollective/html/blob/6.0/src/FormBuilder.php#L1293) check necessary at all? I mean if all what that does is to ensure that `null` is returned, this effectively ensures that the model will never get a chance to pre-populate the form like in the bug I explained above, why is that `if()` check needed at all since the expected behaviour is suppose to be to finally fallback to the model's values?

**Comment by themuddfamily** [comment]
I think in this case you should use ->withInput()
