### ISSUE TITLE
Error with form model binding on a field named 'visible'

### ISSUE THREAD

**Issue by imade-nl** [LaravelCollective/html#64]
When I hava a table with two columns `active` tinyint(1) and `visible` tinyint(1) and try to populate a form with model binding the `active` field displays correctly and the `visible` field stays empty.

When I changed out `{!! Form::checkbox('visible', true) !!}` for `{!!  Form::text('visible'']) !!}` I get an error:` ErrorException in helpers.php line 454: htmlentities() expects parameter 1 to be string, array given` formed in:  `HtmlBuilder->attributes(array('class' => 'form-control', 'required', 'name' => 'visible', 'type' => 'text', 'value' => array(), 'id' => null)) in FormBuilder.php line 248`

I think it might use the protected property of the Eloquent Model?

The workaround I used for now was to cast the Eloquent result to an array and then back to an object:
```
$user = $User::find(1);
$user = (object) $user->toArray();
```

**Comment by adamgoose** [comment]
Your examples have a few typos. Double check the docs and make sure you're calling the methods correctly. This has always worked fine for me.
