### ISSUE TITLE
Not able to use @error blade directive in Form::text

### ISSUE THREAD

**Issue by anilkreddy** [LaravelCollective/html#643]
When trying to include `@error('profile.firstname') is-invalid @enderror` within `{!! Form::text('profile[firstname]', null, ['placeholder' => 'First name', 'class' => 'form-control']); !!}` getting an error.

syntax error, unexpected '<' (View: 

Is there a way to use `@error` to add `is-invalid` class to Form fields?

**Comment by mlantz** [comment]
You cannot do that please read Laravel's docs on using {!! !!} and blade directives.

**Comment by anilkreddy** [comment]
Any other solution? to have validation error handling for laravelcollective?

**Comment by brucebrophy** [comment]
@mlantz Is it possible to add support for conditional error classes to the options array?
