### ISSUE TITLE
6.1 BC compatibility

### ISSUE THREAD

**Issue by bytestream** [LaravelCollective/html#647]
Please do not bump the PHP version requirement in a minor release. That's not semantic versioning.

There was no reason to bump the PHP version in order to add Laravel 7 support

**Comment by yeabuu** [comment]
Am nat getting how github works

**Comment by mlantz** [comment]
Not exactly true, we had it specified as 7.2 compatible, whereas Laravel 7.x requires PHP ^7.2.5 therefore PHP 7.2.0, 7.2.1, 7.2.2, 7.2.3, 7.2.4 would have been incompatible.

**Comment by bytestream** [comment]
@mlantz sorry you've misunderstood. `6.1` of this package supports both Laravel 6 and 7. Laravel 6 is compatible with PHP 7.2.0. By bumping the version requirement to min 7.2.5 you're effectively dropping support for PHP 7.2.0 - 7.2.4. While it's highly unlikely that anyone is going to be using those versions, the fact remains the same.

**Comment by bytestream** [comment]
The only reason this affects me and possibly others is because I hardcode my composer requirements to `7.2.0` and now I can't use `6.1` or above of this package, despite it being a minor, backwards compatible, release.

**Comment by ghost** [comment]
This was a breaking change for me as well. The server is running PHP `7.2.2`, so I can not update to `6.1` of this package.
