### ISSUE TITLE
Changes to "route" parameter in Form::open in v6.1.1

### ISSUE THREAD

**Issue by rogermui** [LaravelCollective/html#648]
With pull request #627, the way of passing multiple route parameters to `Form::open` changed under the guise of a bug fix from:
`Form::open(['route' => ['route.name', 'id' => 1, 'foo' => 'bar']])`
to:
`Form::open(['route' => ['route.name', ['id' => 1, 'foo' => 'bar']]])`

Can we maintain backwards compatibility?

@ChrisThompsonTLDR @mlantz

**Comment by ChrisThompsonTLDR** [comment]
https://laravel.com/docs/7.x/routing#named-routes

> If the named route defines parameters, you may pass the parameters as the second argument to the route function.

`Form::open(['route' => ['route.name', 'id' => 1, 'foo' => 'bar']])` doesn't seem to follow that?

**Comment by rogermui** [comment]
Yes, the `['route.name', 'id' => 1, 'foo' => 'bar']` syntax is undocumented. Yes, it doesn't match `route()`.

But this syntax was supported deliberately with the use of `array_slice` and has been around since `laravel/framework` v4.0 (laravel/framework@2bc08fe) from 7 years ago. It should not be dropped for such reasons.

**Comment by rogermui** [comment]
Please do not risk compromising 7 years of people's code to facilitate one developer's use cases. #627 didn't even update `getControllerAction`, which should be consistent with `getRouteAction`.

**Comment by dayio** [comment]
I don't know what was going on until my deployment failed after the update.

I manage a lot of web app that are in production, and lately it seems that everything broke :sweat_smile: and i know my comment is not useful at all but i agree with @rogermui, i use collective for 5 years now and it's not safe to change those 'legacy' behaviors, at least this one, which is a real breaking change !

So, for my part, i was a huge fan of this library but i think this time i'll have to write my own forms or change the way url are managed with forms.

i'll revert to the 6.1.0 and change my 'route' to 'url' and use Laravel own route helper.

**Comment by ChrisThompsonTLDR** [comment]
I apologize for breaking this package for so many people.  I wasn't aware that it was being used in an undocumented way.

I attempted to be clear in #627 with what I was attempting to fix.

I agree that a pull request shouldn't break existing functionality.

**Comment by mlantz** [comment]
Sorry all for causing any issues. I was doing reviews and should have dug deeper into this PR. Mistakes happen, v6.1.2 contains the PR which reverted the impacts.
