### ISSUE TITLE
[Proposal] About Form::text();

### ISSUE THREAD

**Issue by dogrocker** [LaravelCollective/html#66]
Hello, I've used

```
Form::text($name, $value, $attributes);
```

may it switch to ?

```
Form::text($name, $attributes, $value);
```

I think I alway use `class` or `id` and `placeholder` `$attributes` more than the `$value`,

Because people usually use `Form::model` and when they used `Form::model` and want to use `$attributes`

they alway do the long string of this.

```
{!! Form::text('name', isset($category->name) ? $category->name : '', ['class' => 'someclass' , 'id' => 'name']) !!}
```

But if we switch to

they will be use like this

```
if they don't want value
{!! Form::text('name', ['class' => 'someclass' , 'id' => 'name']) !!}

// if they want value
{!! Form::text('name', [], 'somevalue') !!}
or
{!! Form::text('name', ['class' => 'someclass' , 'id' => 'name'], 'somevalue') !!}
```

It will be shorten than the first one right ?

Best regards.

**Comment by tshafer** [comment]
Can you make a pull request please?

**Comment by adamgoose** [comment]
Sorry, but we will not be changing the method signature for the `Form::text()` method.

**Comment by tshafer** [comment]
Sorry about that Adam. Thanks!
