### ISSUE TITLE
put angular tag in form input value

### ISSUE THREAD

**Issue by infacq** [LaravelCollective/html#67]
`{!! Form::hidden($param->ip_id, @{{ angularModel }}) !!}`

this will not work. How do I do that for Angular?

**Comment by tshafer** [comment]
Try this,

Change the angular tags.
https://scotch.io/quick-tips/quick-tip-using-laravel-blade-with-angularjs

Then wrap it in quotes

{!! Form::hidden($param->ip_id, '<% angularModel %>') !!}

**Comment by arthurkirkosa** [comment]
or simply create an raw html input tag and use the old helper if you need the flashed value.
