### ISSUE TITLE
is there a way to add an id to a checkbox?

### ISSUE THREAD

**Issue by danielzzz** [LaravelCollective/html#682]
hello,

I have 
```
echo Form::checkbox('name', 'value', true);
```
but this does not generate an element with an id.

I have tried 
```
echo Form::checkbox('name', 'value', true. ['id'=>'testId']);
```
but it does not work.

is there a way to add an id to the element?

thanks, cheers, dan

**Comment by danielzzz** [comment]
sorry, somehow it is working now..

**Comment by ndemafia** [comment]
Sorry for not replying to your message.
