### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by alexandre-butynski** [LaravelCollective/html#69]
There is no code formatting convention in this packages. This is a real issue because it complicates merges (I experienced that this morning), it produces useless diffs (see this one : https://github.com/LaravelCollective/html/commit/9c4fea1f045c6fb9d888b4766f460b77e09f7917) and it gives a bad example to newcomers about our quality standards.

There are files indented with 2 spaces, 4 spaces or tabs. Sometimes a mix of two of this options.

I suggest to use the Laravel 5.1 convention : PSR-2. At least, the indentation should be harmonized ! I think that this should be done in 5.1 and master branches (they are very close).

I can do it if you have not time for that but I wait for your *go* for now.

**Comment by tshafer** [comment]
This is a good point, after Laracon, Adam and I will clean up the repo and use PSR-2.

**Comment by alexandre-butynski** [comment]
Great. Thanks.
