### ISSUE TITLE
Laravel 9 support - illuminate/view

### ISSUE THREAD

**Issue by arborrow** [LaravelCollective/html#702]
In preparation for the release of Laravel 9:

Problem 1
    - Conclusion: don't install laravel/framework v9.0.0-beta.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.4 (conflict analysis result)
    - illuminate/view[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.0.15) does not satisfy that requirement.
    - illuminate/view[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.0.15) does not satisfy that requirement.
    - illuminate/view[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.0.15) does not satisfy that requirement.
    - laravelcollective/html[v6.2.0, ..., 6.x-dev] require **illuminate/view ^6.0|^7.0|^8.0** -> satisfiable by illuminate/view[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/view[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v9.0.0-beta.1, ..., 9.x-dev]. laravel/framework replaces illuminate/view and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^9.0 -> satisfiable by laravel/framework[v9.0.0-beta.1, ..., 9.x-dev].
    - Root composer.json requires laravelcollective/html ^6.2 -> satisfiable by laravelcollective/html[v6.2.0, v6.2.1, 6.x-dev].

**Comment by oriceon** [comment]
Any news?

**Comment by karlhillx** [comment]
Yes: https://twitter.com/LaraCollective/status/1491066331453886470

**Comment by arborrow** [comment]
It looks like this was resolved with this PR https://github.com/LaravelCollective/html/pull/700
