### ISSUE TITLE
{{  }} not working properly in Laravel 5

### ISSUE THREAD

**Issue by JFSolorzano** [LaravelCollective/html#71]
As far as i understood ```{{ }} == echo```, but when using it with a ```Form::select``` in Laravel 5 it just doesn't work, it prints to screen the html code, but when using ```<?php echo Form::select ... ?>```

**Comment by adamgoose** [comment]
Laravel 5 escapes all content inside `{{ }}` tags. See the updates to the Laravel documentation here: https://github.com/laravel/docs/commit/caa13f344d0fd32d297654ec50666aa5b6500ba3

**Comment by JFSolorzano** [comment]
@adamgoose so that means that i have to use ```<?php echo ?> ``` to be able to use laravelCollective html dropdown?

**Comment by adamgoose** [comment]
No, I'm sorry I didn't make myself clear.

As of Laravel 5, the `{{ }}` tags evaluate to an escaped version of the input. This means that whatever you're passing through the tags (Form::select() in your case), is passed through PHP's HTML Entities function. In Laravel 4, the syntax for this behavior was `{{{ }}}`.

In Laravel 5, `{{ }}` renders escaped text, and `{!! !!}` renders raw text. Thus, you should use the latter for rendering HTML content.
