### ISSUE TITLE
date field not formatted when using Form::model()

### ISSUE THREAD

**Issue by borys-p** [LaravelCollective/html#80]
Hi,

I'm using date mutators in a model passed to Form::model(). Unfortunately the date is not formatted to the Y-m-d form, because the formatting is performed only on the DateTime object passed directly to the date() function. Maybe this code should be placed in the getValueAttribute() function with additional check on the field type? Or there is a better place?

**Comment by tshafer** [comment]
Can you please paste your model?

**Comment by borys-p** [comment]
Sure. First, simplified version of my model:

```
use Illuminate\Database\Eloquent\Model;

class Ad extends Model
{
	/**
	 * The attributes that should be mutated to dates.
	 *
	 * @var array
	 */
	protected $dates = ['created_at', 'updated_at', 'active_to', 'promo_to']; 
}
```

`active_to` and `promo_to` are nullable `DATE` columns.

Then, there's my edit form (create form uses simple `Form::open()`):

```
{!! Form::model($ad, ['route' => ['admin.ad.update', $ad->id], 'method' => 'put']) !!}

{!! Form::label('active_to', 'Ogłoszenie aktywne do dnia:') !!}
{!! Form::date('active_to', null, ['class' => 'date']) !!}

{!! Form::label('promo_to', 'Ogłoszenie promowane do dnia:') !!}
{!! Form::date('promo_to', null, ['class' => 'date']) !!}

{!! Form::close() !!}
```

And as the result I get "2015-09-11 00:00:00" in those fields. Which is not surprising, as the `if ($value instanceof DateTime)` test gets the `null` value, the real DateTime is pulled later from the model.

**Comment by jvdlaar** [comment]
Did you find a solution to this, as I have the same issue.

**Comment by borys-p** [comment]
@jvdlaar what I made is more an ugly hack than a real solution, but it works. I had to extend the FormBuilder for other reasons, so I just put it there as well:

```
    /**
     * Create a date input field with quick & dirty fix for improper DateTime handling.
     *
     * @param  string $name
     * @param  string $value
     * @param  array  $options
     * @return string
     */
    public function date($name, $value = null, $options = [])
    {
        return str_replace(' 00:00:00', '', parent::date($name, $value, $options));
    }
```

**Comment by jvdlaar** [comment]
I've done this:

    /**
     * Get the Client Since attribute with the right formatting.
     */
    public function getClientSinceFormAttribute($value)
    {
        return $this->client_since->format('Y-m-d');
    }

So in the form I call client_since_form instead of client_since.

**Comment by borys-p** [comment]
Does it work with mutators?

**Comment by jvdlaar** [comment]
Yes it is a mutator.

**Comment by borys-p** [comment]
I meant the Laravel's built-in date mutators. I never tried to use attributes mutators together with date mutators - does it work? I'd expect that a DateTime object is returned.

**Comment by jvdlaar** [comment]
Perhaps I'm misunderstanding what you mean (started with Laravel 1 week ago). My model has this:
`protected $dates = ['client_since', 'client_until'];`

So $organization->client_since is a Carbon object extending DateTime. So the mutator receives this and allows me to do `->format`.

**Comment by borys-p** [comment]
Ok, it should work, but you have to remember to add a mutator to each date column. We need a fix directly in the FormBuilder.

**Comment by tflight** [comment]
@jvdlaar I tried to use the method you suggested, but could never get it to work properly. While I could output the properly formatted date in a view directly, as soon as I put it in either Form::text or Form::date the format would change. I've ended up just skipping the Form builder for that field and then used the model function you described-- works fine.

**Comment by adamgoose** [comment]
Something we're planning for the 5.2 release might include a way to provide form-specific mutators on your model attributes. This would allow you to pass a form-safe date format to the form builder, and a human-readable date form to your views.

**Comment by iWader** [comment]
Perhaps being able to just supply a format to the relevant functions on the form builder. Quite often I like forms to be able to input a human readable format, but they're stored using the databases default format. For example

```PHP
public function date($name, $value = null, $options = [], $format = 'Y-m-d')
{
    if ($value instanceof DateTime)
    {
        $value = $value->format($format);
    }

    return $this->input('date', $name, $value, $options);
}
```

Happy to submit a pull request if theres an agreed implementation.

**Comment by borys-p** [comment]
@iWader: I don't see the point of this. The "date" field is formatted according to the browser's locale, but ISO is the only allowed underlying format.

If you want non-standard behavior, then you can extend text fields and convert the values manually.

**Comment by iWader** [comment]
Good point, entirely overlooked that. I've extended the form builder so date and datetime output as text fields as browser implementations for date and datetime is horrible currently, so forgot about that.

**Comment by adamgoose** [comment]
In 5.2, you can now define form-specific accessors on your models. https://laravelcollective.com/docs/5.2/html#form-model-accessors

**Comment by borys-p** [comment]
@adamgoose this doesn't fix the root cause of invalid handling of DateTime objects in date() method. Even now you can create custom accessors and get the formatted value. But you have to do it for each attribute, instead of just using date mutators and passing your model directly to the form, which will fetch the required ISO value itself.

**Comment by bit9labs** [comment]
The real problem is the form model binding skips the helper function of the FormBuilder class. As you can see if you inspect \Collective\Html\FormBuilder::date

```
/**
 * Create a date input field.
 *
 * @param  string $name
 * @param  string $value
 * @param  array  $options
 *
 * @return \Illuminate\Support\HtmlString
 */
public function date($name, $value = null, $options = [])
{
    if ($value instanceof DateTime) {
        $value = $value->format('Y-m-d');
    }

    return $this->input('date', $name, $value, $options);
}
```
It is correctly formatting date to 'Y-m-d' as specified in HTML5 spec. However at this point $value is actually null. So you have to update the generic input function.

```
/**
 * Create a form input field.
 *
 * @param  string $type
 * @param  string $name
 * @param  string $value
 * @param  array  $options
 *
 * @return \Illuminate\Support\HtmlString
 */
public function input($type, $name, $value = null, $options = [])
{
    ...

    //$value is null here
    if (! in_array($type, $this->skipValueTypes)) {

        //$value is fetched based on hierarchy set by
        $value = $this->getValueAttribute($name, $value);

        //I added this necessary duplicate code to format date value
        if ($type == 'date' && $value instanceof DateTime) {
            $value = $value->format('Y-m-d');
        }
    }

    ...
}
```

**Comment by fretelweb** [comment]
Please pull the code of @bit9labs it work as spected

**Comment by Code-DigitalArt** [comment]
> Please pull the code of @bit9labs it work as spected. I can't modify anytime I update composer.

Tested and agreed! please merge this update, this is a time-wasting bug!
