### ISSUE TITLE
Html::image() class not found but Form::image() works. but why?

### ISSUE THREAD

**Issue by arafatx** [LaravelCollective/html#81]
Before this, I used laravel illuminate/html with the Html::image() tag and it worked fine. This package doesn't seem to support the Html::image() because when I try to use Html::image(), the view return an error and complains that: 'Class 'HTML' not found' 

I can use Form::image() with LaravelCollective/html and it works perfetcly but, Form::image() is not what I want because it generates form input instead of a displaying a normal image on the view. For example:
       
     {!! Form::image('image/icons/like.png','success', array( 'width' => 32, 'height' => 32 ))  !!}

is actually this:

     <input width="32" height="32" src="http://testdomain.com/images/icons/like.png" name="success" type="image">

Of course the disadvantage is that you will have a clickable icon on the image.

I have declared the following allias in the app.php
 'Html' => Collective\Html\HtmlFacade::class,

It seems like there is no example either in the documentation how to use Html::image(). Does it exist? Should I install illuminate/html and remove the laravelcollective html facade? Please suggest, not sure if this is just a bug.

**Comment by tshafer** [comment]
Make sure you are registering the service provider.

html Image does exist.

https://github.com/LaravelCollective/html/blob/5.1/src/HtmlBuilder.php#L101

**Comment by arafatx** [comment]
I reinstalled the this package and now it works! Yes I did register the service provider. I tried composer dump-autoload did not work too. Not sure why. Thanks @tshafer
