### ISSUE TITLE
How to use trans() function with Forms?

### ISSUE THREAD

**Issue by intrepido** [LaravelCollective/html#84]
How to use trans() function with Forms?

**Comment by adamgoose** [comment]
Not sure which function you're referring to. Using PHPStorm, I can't find a `transfer()` symbol in Laravel at all.

**Comment by RobinMalfait** [comment]
@adamgoose he means trans() for translating stuff

**Comment by joaoffm** [comment]
To use the translations from lang/*/validation.php

```php
   'attributes' => array(
        'email'             => 'E-mail',
    ),
```

```php
Form::label('email', trans('validation.attributes.email'))
```
