### ISSUE TITLE
Providing a route name to Form::open does not automatically specify the _method for me

### ISSUE THREAD

**Issue by Glutnix** [LaravelCollective/html#86]
If I have the route: 
```php
Route::put('cart/add', ['as' => 'cart.add', 'uses' => 'CartController@addProduct']);
```

and in a view I have:
```php
{!! Form::open(['route' => 'cart.add']) !!}
```

I expect the output: 
```html
<form method="POST" action="http://localhost:8000/cart/add" accept-charset="UTF-8">
<input name="_method" type="hidden" value="PUT">
<input name="_token" type="hidden" value="wL3...">
```

But it does not create the `_method` hidden field. It should detect that the route is a PUT, and automatically output the `_method` hidden field.

This should work for every non-POST route: GET, PUT, PATCH, DELETE.

Backwards compatibility shouldn't be an issue, as if people have named routes that aren't POST they're already creating their own `_method` field which will override the one Form::open would create.

Is this something that would be accepted as a pull request?

**Comment by adamgoose** [comment]
Sorry, but this isn't possible. Currently, and I do it frequently, one can use the same route name on two different HTTP methods. Thus, it's not possible to determine, with adequate certainty, which verb to use.

Close

**Comment by Glutnix** [comment]
You use the same route name on two different methods: Are you sure you don't mean the URI fragments? It seems weird to have two named routes with the same name: what's the point?

**Comment by adamgoose** [comment]
Yes, I mean the same route name. I use the HTTP verb to differentiate. Whether you use this strategy or not, it's still impossible to ensure that it would resolve correctly.

**Comment by Glutnix** [comment]
Okay, thanks. Glad I asked before writing a PR :)

**Comment by adamgoose** [comment]
I appreciate the effort, though! Thanks for contributing. :)

**Comment by Glutnix** [comment]
Maybe I could clarify this in the documentation? Something along the lines of:

When using named routes be aware that Form::open will not inspect the route to determine the route's method. Be sure to specify the method yourself.
