### ISSUE TITLE
Why do default value is prefered to model value ?

### ISSUE THREAD

**Issue by Gael42** [LaravelCollective/html#87]
When having a value defined in old input it will take precedence over default value, sounds logical.

But when having a value defined in the model, default value will take precedence over model value, I don't understand that, isn't default value intended to be used when there is no other value available ? (in the model or the old input)

Why do default value is prefered to model value ?

Did i do something the wrong way ? ("1" is the default value here) :
```{!! Form::number('field_name', 1, ['class' => 'form-control']) !!}```

I fix'd it this way, but that's ugly, I must had misunderstood something :
```{!! Form::number('field_name', (!empty($model) && $model->field_name !== null)?$model->field_name:1, ['class' => 'form-control']) !!}```

**Comment by adamgoose** [comment]
The `Form::model()` method is designed to allow you to pass `null`s into your forms and still have them populate. The way I like to do it is like this:

```php
{!! Form::model($model, [$routeInfo]) !!}

    {!! Form::text('name', isset($model) ? null : 'Default Value', ['class' => 'form-control']) !!}

{!! Form::close() !!}
```

**Comment by Gael42** [comment]
Thanks a lot for your answer !

I still do not undetstand why default value is prefered to model value ? it should be the opposite no ?

**Comment by adamgoose** [comment]
No, I feel that providing a default value should take precedence.

**Comment by Gael42** [comment]
May you develop ? no troll, i just really want to understand why

**Comment by adamgoose** [comment]
Here's how I see it...

If you use `Form::model()` and the provided model value takes precedence, then you have absolutely no way to override that value when using `Form::text()` or any other method. Thus, you lose control over your form to some extent. In my opinion, that's not acceptable.

Either way, changing the way this works will surely break backwards compatibility.

**Comment by Gael42** [comment]
Even if it feel strange that a 'default' value is prefered to any another one that make sense, and yes, change that will definitely break backwards compat.

Thanks again for your answer :-)

**Comment by nicolasbinet** [comment]
I had the same problem and finished modifying the getValueAttribute

- First if the default if $name is not provided
- Get the value that was submitted
- If not the value from special fields "_token" & "_method" & $model is set ,get the value
- Else, get the default value


```
public function getValueAttribute($name, $value = null)
{
    if (is_null($name)) return $value;

    if (! is_null($this->old($name))) {
        return $this->old($name);
    }

    if ($name != '_token' && $name != '_method' && isset($this->model)) {
        return $this->getModelValueAttribute($name);
    }

    if (!is_null($value)) return $value;
}
```
