### ISSUE TITLE
Form::button allows HTML, Form::submit doesn't.

### ISSUE THREAD

**Issue by arjankapteijn** [LaravelCollective/html#88]
```
{!! Form::button('<i class="fa fa-plus"></i> '.Lang::get('location.button_create'), array('class' => 'btn btn-primary')) !!}
```

^^ OK!

```
{!! Form::submit('<i class="fa fa-plus"></i> '.Lang::get('location.button_create'), array('class' => 'btn btn-primary')) !!}
```
^^ doesn't work.

![schermafbeelding 2015-09-16 om 14 55 37](https://cloud.githubusercontent.com/assets/8143550/9905091/04d78370-5c83-11e5-9f48-6c909c6abb47.png)

The only difference is the submit v.s. button. Is this a bug? Or am I missing something?

**Comment by Daniesy** [comment]
Same for `link_to` method. I tryed this
    {!! link_to('bla/', '<i class="fa fa-building"></i> Text') !!}
and it displays text instead of html.

**Comment by hurrycaner** [comment]
Reset buttons are not working as well... just like submit buttons:
`{!! Form::reset('<i class="fa fa-plus"></i> '.Lang::get('location.button_create'), array('class' => 'btn btn-primary')) !!}`

**Comment by adamgoose** [comment]
The `Form::submit()` method returns `<input>` tags, which do not allow HTML inside the `value` attribute. Same goes for the `Form::reset()` method. Use a button.

**Comment by adamgoose** [comment]
@Daniesy Please create a separate Issue for this.
