### ISSUE TITLE
Select to check selected values from a collection

### ISSUE THREAD

**Issue by rumeau** [LaravelCollective/html#89]
Hello, i'm using FormBuilder to add a couple of select elements

This select fields are tied to a model relation.

Currently i workaround this with a custom attribute to retrieve the selected elements from the relation and converting them to an array so https://github.com/LaravelCollective/html/blob/5.1/src/FormBuilder.php#L660 can read this options.

I'm thinking of adding a pull request for this to be taken care on the same method to allow for collections to be interpreted directly on the model.

IE.

```
    if(is_array($selected))
    {
      return in_array($value, $selected) ? 'selected' : null;
    }
    elseif($selected instanceof Collection)
    {
      return $selected->contains('id', $value) ? 'selected' : null;
    }
```

The problem is that a many-to-many relation should be indexed by the 'id' field following laravel convention, but might be a case where the id actually calls ie. "company_id", in this case the 'id' field would be hardcoded on the condition.

My final issue is should i add this pull request or this should be handled by developers on their own models or views? Is this an issue to someone else or does this have enough support?

Thanks

**Comment by fhferreira** [comment]
+1

**Comment by eullercristian** [comment]
+1

**Comment by albertboada** [comment]
Crashed into this bug as well, makes the helper unusable with 5.2.

Shouldn't `$selected` always be a plain array holding the ids (e.g. `[3, 4, 65]`), even on many to many relationships? If so, the fix should be like yours with a slight difference:

 ```php
if (is_array($selected)) {
    return in_array($value, $selected) ? 'selected' : null;
}
else if ($selected instanceof Collection) {
    return $selected->contains($value) ? 'selected' : null;
}
```

I'm still learning, but this one matches the Laracasts approach for the many to many usecase.
