### ISSUE TITLE
after updating to 5.1.6 checkbox model value not showing

### ISSUE THREAD

**Issue by tmihetec** [LaravelCollective/html#92]
Hi, maybe i'm doing something wrong, but after update to 5.1.6 (from 5.1.4) checkbox will not be checked if model value is '1'... 

Form::model($mymodel ...)
Form::checkbox('field','1',false)

any other way to set checbox to checked if value is ==1 ?
tnx

**Comment by adamgoose** [comment]
I think you have your method signature wrong.

`public function checkbox($name, $value, bool $checked = false, array $attributes = [])`

**Comment by tmihetec** [comment]
i don't think so... same code works with 5.1.4 but fails on 5.1.6
it looks like it's not translating 1 or 0 to bool $checked. ( 1 or 0 are values that model has for $name property)
