### ISSUE TITLE
Cannot pass multiple route parameters to Form::open

### ISSUE THREAD

**Issue by pavsid** [LaravelCollective/html#93]
It seems you cannot do the following..

```
{!! Form::model($model, ['route' => ['my.named.route', [$id, $other]]]) !!}
```

..but sometimes you need to pass in more than one parameter to the named route, even if it's just GET variables

**Comment by adamgoose** [comment]
Try the following:

`{!! Form::model($model, ['route' => ['my.named.route', $id, $other]]) !!}`

**Comment by sabau** [comment]
This method works fine. But the parameters order is 
It would be nice to give the parameter names like the classical action:
    action('MyController@edit', ['type' => $type, 'other' => $stuff, 'id' => $id])

**Comment by adamgoose** [comment]
This should be an issue related to the [Illuminate\Routing\UrlGenerator](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Routing/UrlGenerator.php).
