### ISSUE TITLE
Problem form binding radio inputs

### ISSUE THREAD

**Issue by garygreen** [LaravelCollective/html#95]
In the below I would expect it to select the `Any` option but instead it selects the `Closed` one. 

```
{!! Form::model(['status' => '']) !!}
	{!! Form::radio('status', '') !!} Any
	{!! Form::radio('status', 'Open') !!} Open
	{!! Form::radio('status', 'Closed') !!} Closed
{!! Form::close() !!}
```

This is due to a non strict type check on https://github.com/LaravelCollective/html/blob/5.1/src/FormBuilder.php#L792

It's essentially doing `'' == 0` which returns true, so selects the 'Closed' option.

Do you think empty strings should be handled explicitly?

**Comment by adamgoose** [comment]
I'd recommend passing `null` instead of an empty string.

**Comment by garygreen** [comment]
Passing null has the same problem.
