### ISSUE TITLE
getModelValueAttribute not loads the appropriate model value when using field names that has the model as other core attribute

### ISSUE THREAD

**Issue by gabka913** [LaravelCollective/html#98]
Sorry for my english, I hope you will understand :)

Exact issue:
I named a field in database as "visible".
Eloquent model has a protected attribute with same name: protected $visible = [];

When form builder tries to get this field value from model instance, it returns this protected attribute, instead of the data field.

```
  protected function getModelValueAttribute($name)
  {
if ($name=='visible') dd(data_get($this->model, $this->transformKey($name))); // returns array(0) instead of "1" or "0".
    return data_get($this->model, $this->transformKey($name));
  }
```

It's because the core eloquent model has ArrayAccess interface. 
The data_get helper function runs into this case:

```
......
            } elseif ($target instanceof ArrayAccess) {
                [DEBUG HERE]
                if (! isset($target[$segment])) {
                    return value($default);
                }
....
```

DEBUG:
d($target['visible']) => array(0)
d($target->visible) => 1 (correct database value)
When I dump entire $target, the model instance is fine, and the visible attribute too.

Probably would be the same with guarded, fillable, etc fields.

method call: {!! Form::radio('visible', 1) !!}

Maybe this was the same issue: https://github.com/LaravelCollective/html/issues/64

Thanks

**Comment by obarlas** [comment]
One of my sql field is named "original" and I have exactly the same issue. I had to change it to "origin" to bypass this bug for now, but I don't know how it will affect me in the future.
