### ISSUE TITLE
[proposal] Return view expressions

### ISSUE THREAD

**Issue by JosephSilber** [LaravelCollective/html#99]
Can we return [view expressions](https://github.com/laravel/framework/blob/5.1/src/Illuminate/View/Expression.php) from all form/html builder methods, so that people don't have to use raw tags for them?

For example, see Laravel's built-in [`csrf_field`](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/helpers.php#L208) and [`method_field`](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/helpers.php#L419) methods.

Raw tags are not pleasant on the eye and look scary. They're intentionally designed to grab your attention, to alert you to the fact that you're doing something that might potentially be a security risk.

Anything that returns non-user-generated HTML shouldn't be looking this threatening :smile:

**Comment by thomastkim** [comment]
:+1:

**Comment by tshafer** [comment]
Done.
https://github.com/LaravelCollective/html/commit/e70854b5238bc8f92190f570aa83a9b6ecaee439

**Comment by adamgoose** [comment]
Will be released with v5.2, at the same time as @laravel/laravel 's release.
